// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializeblock")
public inline fun block(block: app.pochical.v1.BlockKt.Dsl.() -> kotlin.Unit): app.pochical.v1.Block =
  app.pochical.v1.BlockKt.Dsl._create(app.pochical.v1.Block.newBuilder()).apply { block() }._build()
/**
 * ```
 * Someone the user has blocked, in every group they share: one value per
 * person, the latest.
 * ```
 *
 * Protobuf type `pochical.v1.Block`
 */
public object BlockKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.Block.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.Block.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.Block = _builder.build()

    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * ```
     * Blocked, or unblocked since.
     * ```
     *
     * `bool on = 2 [json_name = "on"];`
     */
    public var on: kotlin.Boolean
      @kotlin.jvm.JvmName("getOn")
        get() = _builder.on
      @kotlin.jvm.JvmName("setOn")
        set(value) {
        _builder.on = value
      }
    /**
     * ```
     * Blocked, or unblocked since.
     * ```
     *
     * `bool on = 2 [json_name = "on"];`
     */
    public fun clearOn() {
      _builder.clearOn()
    }
  }
}
public inline fun app.pochical.v1.Block.copy(block: `app.pochical.v1`.BlockKt.Dsl.() -> kotlin.Unit): app.pochical.v1.Block =
  `app.pochical.v1`.BlockKt.Dsl._create(this.toBuilder()).apply { block() }._build()

