// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializechange")
public inline fun change(block: app.pochical.v1.ChangeKt.Dsl.() -> kotlin.Unit): app.pochical.v1.Change =
  app.pochical.v1.ChangeKt.Dsl._create(app.pochical.v1.Change.newBuilder()).apply { block() }._build()
/**
 * ```
 * A value as the DO now holds it, at the cursor it got when it last
 * changed.
 * ```
 *
 * Protobuf type `pochical.v1.Change`
 */
public object ChangeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.Change.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.Change.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.Change = _builder.build()

    /**
     * `uint64 cursor = 1 [json_name = "cursor"];`
     */
    public var cursor: kotlin.Long
      @kotlin.jvm.JvmName("getCursor")
        get() = _builder.cursor
      @kotlin.jvm.JvmName("setCursor")
        set(value) {
        _builder.cursor = value
      }
    /**
     * `uint64 cursor = 1 [json_name = "cursor"];`
     */
    public fun clearCursor() {
      _builder.clearCursor()
    }

    /**
     * `.pochical.v1.DayValue day = 2 [json_name = "day"];`
     */
    public var day: app.pochical.v1.DayValue
      @kotlin.jvm.JvmName("getDay")
        get() = _builder.day
      @kotlin.jvm.JvmName("setDay")
        set(value) {
        _builder.day = value
      }
    /**
     * `.pochical.v1.DayValue day = 2 [json_name = "day"];`
     */
    public fun clearDay() {
      _builder.clearDay()
    }
    /**
     * `.pochical.v1.DayValue day = 2 [json_name = "day"];`
     * @return Whether the day field is set.
     */
    public fun hasDay(): kotlin.Boolean {
      return _builder.hasDay()
    }

    /**
     * `.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];`
     */
    public var pattern: app.pochical.v1.PatternValue
      @kotlin.jvm.JvmName("getPattern")
        get() = _builder.pattern
      @kotlin.jvm.JvmName("setPattern")
        set(value) {
        _builder.pattern = value
      }
    /**
     * `.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];`
     */
    public fun clearPattern() {
      _builder.clearPattern()
    }
    /**
     * `.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];`
     * @return Whether the pattern field is set.
     */
    public fun hasPattern(): kotlin.Boolean {
      return _builder.hasPattern()
    }

    /**
     * `.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];`
     */
    public var patternOrder: app.pochical.v1.PatternOrder
      @kotlin.jvm.JvmName("getPatternOrder")
        get() = _builder.patternOrder
      @kotlin.jvm.JvmName("setPatternOrder")
        set(value) {
        _builder.patternOrder = value
      }
    /**
     * `.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];`
     */
    public fun clearPatternOrder() {
      _builder.clearPatternOrder()
    }
    /**
     * `.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];`
     * @return Whether the patternOrder field is set.
     */
    public fun hasPatternOrder(): kotlin.Boolean {
      return _builder.hasPatternOrder()
    }

    /**
     * ```
     * On a Group DO socket: a member's shared days and patterns, as their
     * User DO pushes them (spec/sync-protocol.md, Group projection).
     * ```
     *
     * `.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];`
     */
    public var memberDay: app.pochical.v1.MemberDay
      @kotlin.jvm.JvmName("getMemberDay")
        get() = _builder.memberDay
      @kotlin.jvm.JvmName("setMemberDay")
        set(value) {
        _builder.memberDay = value
      }
    /**
     * ```
     * On a Group DO socket: a member's shared days and patterns, as their
     * User DO pushes them (spec/sync-protocol.md, Group projection).
     * ```
     *
     * `.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];`
     */
    public fun clearMemberDay() {
      _builder.clearMemberDay()
    }
    /**
     * ```
     * On a Group DO socket: a member's shared days and patterns, as their
     * User DO pushes them (spec/sync-protocol.md, Group projection).
     * ```
     *
     * `.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];`
     * @return Whether the memberDay field is set.
     */
    public fun hasMemberDay(): kotlin.Boolean {
      return _builder.hasMemberDay()
    }

    /**
     * `.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];`
     */
    public var memberPattern: app.pochical.v1.MemberPattern
      @kotlin.jvm.JvmName("getMemberPattern")
        get() = _builder.memberPattern
      @kotlin.jvm.JvmName("setMemberPattern")
        set(value) {
        _builder.memberPattern = value
      }
    /**
     * `.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];`
     */
    public fun clearMemberPattern() {
      _builder.clearMemberPattern()
    }
    /**
     * `.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];`
     * @return Whether the memberPattern field is set.
     */
    public fun hasMemberPattern(): kotlin.Boolean {
      return _builder.hasMemberPattern()
    }

    /**
     * `.pochical.v1.RepeatOrders repeat_orders = 7 [json_name = "repeatOrders"];`
     */
    public var repeatOrders: app.pochical.v1.RepeatOrders
      @kotlin.jvm.JvmName("getRepeatOrders")
        get() = _builder.repeatOrders
      @kotlin.jvm.JvmName("setRepeatOrders")
        set(value) {
        _builder.repeatOrders = value
      }
    /**
     * `.pochical.v1.RepeatOrders repeat_orders = 7 [json_name = "repeatOrders"];`
     */
    public fun clearRepeatOrders() {
      _builder.clearRepeatOrders()
    }
    /**
     * `.pochical.v1.RepeatOrders repeat_orders = 7 [json_name = "repeatOrders"];`
     * @return Whether the repeatOrders field is set.
     */
    public fun hasRepeatOrders(): kotlin.Boolean {
      return _builder.hasRepeatOrders()
    }

    /**
     * `.pochical.v1.CoworkerValue coworker = 8 [json_name = "coworker"];`
     */
    public var coworker: app.pochical.v1.CoworkerValue
      @kotlin.jvm.JvmName("getCoworker")
        get() = _builder.coworker
      @kotlin.jvm.JvmName("setCoworker")
        set(value) {
        _builder.coworker = value
      }
    /**
     * `.pochical.v1.CoworkerValue coworker = 8 [json_name = "coworker"];`
     */
    public fun clearCoworker() {
      _builder.clearCoworker()
    }
    /**
     * `.pochical.v1.CoworkerValue coworker = 8 [json_name = "coworker"];`
     * @return Whether the coworker field is set.
     */
    public fun hasCoworker(): kotlin.Boolean {
      return _builder.hasCoworker()
    }

    /**
     * `.pochical.v1.CoworkerOrder coworker_order = 9 [json_name = "coworkerOrder"];`
     */
    public var coworkerOrder: app.pochical.v1.CoworkerOrder
      @kotlin.jvm.JvmName("getCoworkerOrder")
        get() = _builder.coworkerOrder
      @kotlin.jvm.JvmName("setCoworkerOrder")
        set(value) {
        _builder.coworkerOrder = value
      }
    /**
     * `.pochical.v1.CoworkerOrder coworker_order = 9 [json_name = "coworkerOrder"];`
     */
    public fun clearCoworkerOrder() {
      _builder.clearCoworkerOrder()
    }
    /**
     * `.pochical.v1.CoworkerOrder coworker_order = 9 [json_name = "coworkerOrder"];`
     * @return Whether the coworkerOrder field is set.
     */
    public fun hasCoworkerOrder(): kotlin.Boolean {
      return _builder.hasCoworkerOrder()
    }

    /**
     * ```
     * On a Group DO socket: a member's repeating orders, so the group works
     * their days out as their own devices do.
     * ```
     *
     * `.pochical.v1.MemberRepeatOrders member_repeat_orders = 10 [json_name = "memberRepeatOrders"];`
     */
    public var memberRepeatOrders: app.pochical.v1.MemberRepeatOrders
      @kotlin.jvm.JvmName("getMemberRepeatOrders")
        get() = _builder.memberRepeatOrders
      @kotlin.jvm.JvmName("setMemberRepeatOrders")
        set(value) {
        _builder.memberRepeatOrders = value
      }
    /**
     * ```
     * On a Group DO socket: a member's repeating orders, so the group works
     * their days out as their own devices do.
     * ```
     *
     * `.pochical.v1.MemberRepeatOrders member_repeat_orders = 10 [json_name = "memberRepeatOrders"];`
     */
    public fun clearMemberRepeatOrders() {
      _builder.clearMemberRepeatOrders()
    }
    /**
     * ```
     * On a Group DO socket: a member's repeating orders, so the group works
     * their days out as their own devices do.
     * ```
     *
     * `.pochical.v1.MemberRepeatOrders member_repeat_orders = 10 [json_name = "memberRepeatOrders"];`
     * @return Whether the memberRepeatOrders field is set.
     */
    public fun hasMemberRepeatOrders(): kotlin.Boolean {
      return _builder.hasMemberRepeatOrders()
    }

    /**
     * ```
     * On the User DO socket: a group the user is in, for their list of
     * groups (spec/sync-protocol.md, Groups).
     * ```
     *
     * `.pochical.v1.Membership membership = 11 [json_name = "membership"];`
     */
    public var membership: app.pochical.v1.Membership
      @kotlin.jvm.JvmName("getMembership")
        get() = _builder.membership
      @kotlin.jvm.JvmName("setMembership")
        set(value) {
        _builder.membership = value
      }
    /**
     * ```
     * On the User DO socket: a group the user is in, for their list of
     * groups (spec/sync-protocol.md, Groups).
     * ```
     *
     * `.pochical.v1.Membership membership = 11 [json_name = "membership"];`
     */
    public fun clearMembership() {
      _builder.clearMembership()
    }
    /**
     * ```
     * On the User DO socket: a group the user is in, for their list of
     * groups (spec/sync-protocol.md, Groups).
     * ```
     *
     * `.pochical.v1.Membership membership = 11 [json_name = "membership"];`
     * @return Whether the membership field is set.
     */
    public fun hasMembership(): kotlin.Boolean {
      return _builder.hasMembership()
    }

    /**
     * ```
     * On a Group DO socket: the group's name and mark, and who is in it.
     * ```
     *
     * `.pochical.v1.GroupProfile group_profile = 12 [json_name = "groupProfile"];`
     */
    public var groupProfile: app.pochical.v1.GroupProfile
      @kotlin.jvm.JvmName("getGroupProfile")
        get() = _builder.groupProfile
      @kotlin.jvm.JvmName("setGroupProfile")
        set(value) {
        _builder.groupProfile = value
      }
    /**
     * ```
     * On a Group DO socket: the group's name and mark, and who is in it.
     * ```
     *
     * `.pochical.v1.GroupProfile group_profile = 12 [json_name = "groupProfile"];`
     */
    public fun clearGroupProfile() {
      _builder.clearGroupProfile()
    }
    /**
     * ```
     * On a Group DO socket: the group's name and mark, and who is in it.
     * ```
     *
     * `.pochical.v1.GroupProfile group_profile = 12 [json_name = "groupProfile"];`
     * @return Whether the groupProfile field is set.
     */
    public fun hasGroupProfile(): kotlin.Boolean {
      return _builder.hasGroupProfile()
    }

    /**
     * `.pochical.v1.Member member = 13 [json_name = "member"];`
     */
    public var member: app.pochical.v1.Member
      @kotlin.jvm.JvmName("getMember")
        get() = _builder.member
      @kotlin.jvm.JvmName("setMember")
        set(value) {
        _builder.member = value
      }
    /**
     * `.pochical.v1.Member member = 13 [json_name = "member"];`
     */
    public fun clearMember() {
      _builder.clearMember()
    }
    /**
     * `.pochical.v1.Member member = 13 [json_name = "member"];`
     * @return Whether the member field is set.
     */
    public fun hasMember(): kotlin.Boolean {
      return _builder.hasMember()
    }

    /**
     * ```
     * On a Group DO socket: a line of a chat, and how far a member has
     * read one (spec/sync-protocol.md, Chat).
     * ```
     *
     * `.pochical.v1.ChatLine chat_line = 14 [json_name = "chatLine"];`
     */
    public var chatLine: app.pochical.v1.ChatLine
      @kotlin.jvm.JvmName("getChatLine")
        get() = _builder.chatLine
      @kotlin.jvm.JvmName("setChatLine")
        set(value) {
        _builder.chatLine = value
      }
    /**
     * ```
     * On a Group DO socket: a line of a chat, and how far a member has
     * read one (spec/sync-protocol.md, Chat).
     * ```
     *
     * `.pochical.v1.ChatLine chat_line = 14 [json_name = "chatLine"];`
     */
    public fun clearChatLine() {
      _builder.clearChatLine()
    }
    /**
     * ```
     * On a Group DO socket: a line of a chat, and how far a member has
     * read one (spec/sync-protocol.md, Chat).
     * ```
     *
     * `.pochical.v1.ChatLine chat_line = 14 [json_name = "chatLine"];`
     * @return Whether the chatLine field is set.
     */
    public fun hasChatLine(): kotlin.Boolean {
      return _builder.hasChatLine()
    }

    /**
     * `.pochical.v1.ReadMark read_mark = 15 [json_name = "readMark"];`
     */
    public var readMark: app.pochical.v1.ReadMark
      @kotlin.jvm.JvmName("getReadMark")
        get() = _builder.readMark
      @kotlin.jvm.JvmName("setReadMark")
        set(value) {
        _builder.readMark = value
      }
    /**
     * `.pochical.v1.ReadMark read_mark = 15 [json_name = "readMark"];`
     */
    public fun clearReadMark() {
      _builder.clearReadMark()
    }
    /**
     * `.pochical.v1.ReadMark read_mark = 15 [json_name = "readMark"];`
     * @return Whether the readMark field is set.
     */
    public fun hasReadMark(): kotlin.Boolean {
      return _builder.hasReadMark()
    }

    /**
     * ```
     * On the User DO socket: how many of a chat's lines the user has not
     * read, from the group, for badges without a socket to each group
     * (spec/sync-protocol.md, Unread summary).
     * ```
     *
     * `.pochical.v1.UnreadCount unread_count = 16 [json_name = "unreadCount"];`
     */
    public var unreadCount: app.pochical.v1.UnreadCount
      @kotlin.jvm.JvmName("getUnreadCount")
        get() = _builder.unreadCount
      @kotlin.jvm.JvmName("setUnreadCount")
        set(value) {
        _builder.unreadCount = value
      }
    /**
     * ```
     * On the User DO socket: how many of a chat's lines the user has not
     * read, from the group, for badges without a socket to each group
     * (spec/sync-protocol.md, Unread summary).
     * ```
     *
     * `.pochical.v1.UnreadCount unread_count = 16 [json_name = "unreadCount"];`
     */
    public fun clearUnreadCount() {
      _builder.clearUnreadCount()
    }
    /**
     * ```
     * On the User DO socket: how many of a chat's lines the user has not
     * read, from the group, for badges without a socket to each group
     * (spec/sync-protocol.md, Unread summary).
     * ```
     *
     * `.pochical.v1.UnreadCount unread_count = 16 [json_name = "unreadCount"];`
     * @return Whether the unreadCount field is set.
     */
    public fun hasUnreadCount(): kotlin.Boolean {
      return _builder.hasUnreadCount()
    }

    /**
     * ```
     * Someone the user has blocked, or no longer (spec/chat.md, Reporting
     * and blocking); User DO only.
     * ```
     *
     * `.pochical.v1.Block block = 17 [json_name = "block"];`
     */
    public var block: app.pochical.v1.Block
      @kotlin.jvm.JvmName("getBlock")
        get() = _builder.block
      @kotlin.jvm.JvmName("setBlock")
        set(value) {
        _builder.block = value
      }
    /**
     * ```
     * Someone the user has blocked, or no longer (spec/chat.md, Reporting
     * and blocking); User DO only.
     * ```
     *
     * `.pochical.v1.Block block = 17 [json_name = "block"];`
     */
    public fun clearBlock() {
      _builder.clearBlock()
    }
    /**
     * ```
     * Someone the user has blocked, or no longer (spec/chat.md, Reporting
     * and blocking); User DO only.
     * ```
     *
     * `.pochical.v1.Block block = 17 [json_name = "block"];`
     * @return Whether the block field is set.
     */
    public fun hasBlock(): kotlin.Boolean {
      return _builder.hasBlock()
    }
    public val kindCase: app.pochical.v1.Change.KindCase
    @kotlin.jvm.JvmName("getKindCase")
      get() = _builder.kindCase

    public fun clearKind() {
      _builder.clearKind()
    }
  }
}
public inline fun app.pochical.v1.Change.copy(block: `app.pochical.v1`.ChangeKt.Dsl.() -> kotlin.Unit): app.pochical.v1.Change =
  `app.pochical.v1`.ChangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val app.pochical.v1.ChangeOrBuilder.dayOrNull: app.pochical.v1.DayValue?
  get() = if (hasDay()) getDay() else null

public val app.pochical.v1.ChangeOrBuilder.patternOrNull: app.pochical.v1.PatternValue?
  get() = if (hasPattern()) getPattern() else null

public val app.pochical.v1.ChangeOrBuilder.patternOrderOrNull: app.pochical.v1.PatternOrder?
  get() = if (hasPatternOrder()) getPatternOrder() else null

public val app.pochical.v1.ChangeOrBuilder.memberDayOrNull: app.pochical.v1.MemberDay?
  get() = if (hasMemberDay()) getMemberDay() else null

public val app.pochical.v1.ChangeOrBuilder.memberPatternOrNull: app.pochical.v1.MemberPattern?
  get() = if (hasMemberPattern()) getMemberPattern() else null

public val app.pochical.v1.ChangeOrBuilder.repeatOrdersOrNull: app.pochical.v1.RepeatOrders?
  get() = if (hasRepeatOrders()) getRepeatOrders() else null

public val app.pochical.v1.ChangeOrBuilder.coworkerOrNull: app.pochical.v1.CoworkerValue?
  get() = if (hasCoworker()) getCoworker() else null

public val app.pochical.v1.ChangeOrBuilder.coworkerOrderOrNull: app.pochical.v1.CoworkerOrder?
  get() = if (hasCoworkerOrder()) getCoworkerOrder() else null

public val app.pochical.v1.ChangeOrBuilder.memberRepeatOrdersOrNull: app.pochical.v1.MemberRepeatOrders?
  get() = if (hasMemberRepeatOrders()) getMemberRepeatOrders() else null

public val app.pochical.v1.ChangeOrBuilder.membershipOrNull: app.pochical.v1.Membership?
  get() = if (hasMembership()) getMembership() else null

public val app.pochical.v1.ChangeOrBuilder.groupProfileOrNull: app.pochical.v1.GroupProfile?
  get() = if (hasGroupProfile()) getGroupProfile() else null

public val app.pochical.v1.ChangeOrBuilder.memberOrNull: app.pochical.v1.Member?
  get() = if (hasMember()) getMember() else null

public val app.pochical.v1.ChangeOrBuilder.chatLineOrNull: app.pochical.v1.ChatLine?
  get() = if (hasChatLine()) getChatLine() else null

public val app.pochical.v1.ChangeOrBuilder.readMarkOrNull: app.pochical.v1.ReadMark?
  get() = if (hasReadMark()) getReadMark() else null

public val app.pochical.v1.ChangeOrBuilder.unreadCountOrNull: app.pochical.v1.UnreadCount?
  get() = if (hasUnreadCount()) getUnreadCount() else null

public val app.pochical.v1.ChangeOrBuilder.blockOrNull: app.pochical.v1.Block?
  get() = if (hasBlock()) getBlock() else null

