// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializechanges")
public inline fun changes(block: app.pochical.v1.ChangesKt.Dsl.() -> kotlin.Unit): app.pochical.v1.Changes =
  app.pochical.v1.ChangesKt.Dsl._create(app.pochical.v1.Changes.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.Changes`
 */
public object ChangesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.Changes.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.Changes.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.Changes = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChangesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .pochical.v1.Change changes = 1 [json_name = "changes"];`
     */
     public val changes: com.google.protobuf.kotlin.DslList<app.pochical.v1.Change, ChangesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.changesList
      )
    /**
     * `repeated .pochical.v1.Change changes = 1 [json_name = "changes"];`
     * @param value The changes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addChanges")
    public fun com.google.protobuf.kotlin.DslList<app.pochical.v1.Change, ChangesProxy>.add(value: app.pochical.v1.Change) {
      _builder.addChanges(value)
    }
    /**
     * `repeated .pochical.v1.Change changes = 1 [json_name = "changes"];`
     * @param value The changes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignChanges")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<app.pochical.v1.Change, ChangesProxy>.plusAssign(value: app.pochical.v1.Change) {
      add(value)
    }
    /**
     * `repeated .pochical.v1.Change changes = 1 [json_name = "changes"];`
     * @param values The changes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllChanges")
    public fun com.google.protobuf.kotlin.DslList<app.pochical.v1.Change, ChangesProxy>.addAll(values: kotlin.collections.Iterable<app.pochical.v1.Change>) {
      _builder.addAllChanges(values)
    }
    /**
     * `repeated .pochical.v1.Change changes = 1 [json_name = "changes"];`
     * @param values The changes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllChanges")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<app.pochical.v1.Change, ChangesProxy>.plusAssign(values: kotlin.collections.Iterable<app.pochical.v1.Change>) {
      addAll(values)
    }
    /**
     * `repeated .pochical.v1.Change changes = 1 [json_name = "changes"];`
     * @param index The index to set the value at.
     * @param value The changes to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setChanges")
    public operator fun com.google.protobuf.kotlin.DslList<app.pochical.v1.Change, ChangesProxy>.set(index: kotlin.Int, value: app.pochical.v1.Change) {
      _builder.setChanges(index, value)
    }
    /**
     * `repeated .pochical.v1.Change changes = 1 [json_name = "changes"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearChanges")
    public fun com.google.protobuf.kotlin.DslList<app.pochical.v1.Change, ChangesProxy>.clear() {
      _builder.clearChanges()
    }
  }
}
public inline fun app.pochical.v1.Changes.copy(block: `app.pochical.v1`.ChangesKt.Dsl.() -> kotlin.Unit): app.pochical.v1.Changes =
  `app.pochical.v1`.ChangesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

