// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializechatMute")
public inline fun chatMute(block: app.pochical.v1.ChatMuteKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ChatMute =
  app.pochical.v1.ChatMuteKt.Dsl._create(app.pochical.v1.ChatMute.newBuilder()).apply { block() }._build()
/**
 * ```
 * A chat whose notifications the user turned off, or back on: one value
 * per chat, the latest.
 * ```
 *
 * Protobuf type `pochical.v1.ChatMute`
 */
public object ChatMuteKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.ChatMute.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.ChatMute.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.ChatMute = _builder.build()

    /**
     * `string group_id = 1 [json_name = "groupId"];`
     */
    public var groupId: kotlin.String
      @kotlin.jvm.JvmName("getGroupId")
        get() = _builder.groupId
      @kotlin.jvm.JvmName("setGroupId")
        set(value) {
        _builder.groupId = value
      }
    /**
     * `string group_id = 1 [json_name = "groupId"];`
     */
    public fun clearGroupId() {
      _builder.clearGroupId()
    }

    /**
     * `string thread_id = 2 [json_name = "threadId"];`
     */
    public var threadId: kotlin.String
      @kotlin.jvm.JvmName("getThreadId")
        get() = _builder.threadId
      @kotlin.jvm.JvmName("setThreadId")
        set(value) {
        _builder.threadId = value
      }
    /**
     * `string thread_id = 2 [json_name = "threadId"];`
     */
    public fun clearThreadId() {
      _builder.clearThreadId()
    }

    /**
     * ```
     * Off, or on again since.
     * ```
     *
     * `bool muted = 3 [json_name = "muted"];`
     */
    public var muted: kotlin.Boolean
      @kotlin.jvm.JvmName("getMuted")
        get() = _builder.muted
      @kotlin.jvm.JvmName("setMuted")
        set(value) {
        _builder.muted = value
      }
    /**
     * ```
     * Off, or on again since.
     * ```
     *
     * `bool muted = 3 [json_name = "muted"];`
     */
    public fun clearMuted() {
      _builder.clearMuted()
    }
  }
}
public inline fun app.pochical.v1.ChatMute.copy(block: `app.pochical.v1`.ChatMuteKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ChatMute =
  `app.pochical.v1`.ChatMuteKt.Dsl._create(this.toBuilder()).apply { block() }._build()

