// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: pochical/v1/chat.proto
//
package app.pochical.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  What a chat asks the server beyond its socket (spec/chat.md).
 */
public interface ChatServiceClientInterface {
  /**
   *  A link's preview, read by the server so people's addresses are not
   *  sent to the sites (spec/chat.md, Reading a page), cached by URL for a
   *  day. Signed-in users only. The preview is unset when no page was
   *  found; INVALID_ARGUMENT for a URL that is not http(s) on 80 or 443.
   */
  public suspend fun getLinkPreview(request: GetLinkPreviewRequest, headers: Headers = emptyMap()): ResponseMessage<GetLinkPreviewResponse>
}
