// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializechatVote")
public inline fun chatVote(block: app.pochical.v1.ChatVoteKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ChatVote =
  app.pochical.v1.ChatVoteKt.Dsl._create(app.pochical.v1.ChatVote.newBuilder()).apply { block() }._build()
/**
 * ```
 * The member can come on one of a poll's days (行ける), or takes it
 * back: anyone in the group, on as many days as they like, until the
 * poll is settled.
 * ```
 *
 * Protobuf type `pochical.v1.ChatVote`
 */
public object ChatVoteKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.ChatVote.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.ChatVote.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.ChatVote = _builder.build()

    /**
     * `string thread_id = 1 [json_name = "threadId"];`
     */
    public var threadId: kotlin.String
      @kotlin.jvm.JvmName("getThreadId")
        get() = _builder.threadId
      @kotlin.jvm.JvmName("setThreadId")
        set(value) {
        _builder.threadId = value
      }
    /**
     * `string thread_id = 1 [json_name = "threadId"];`
     */
    public fun clearThreadId() {
      _builder.clearThreadId()
    }

    /**
     * `uint64 seq = 2 [json_name = "seq"];`
     */
    public var seq: kotlin.Long
      @kotlin.jvm.JvmName("getSeq")
        get() = _builder.seq
      @kotlin.jvm.JvmName("setSeq")
        set(value) {
        _builder.seq = value
      }
    /**
     * `uint64 seq = 2 [json_name = "seq"];`
     */
    public fun clearSeq() {
      _builder.clearSeq()
    }

    /**
     * `string day = 3 [json_name = "day"];`
     */
    public var day: kotlin.String
      @kotlin.jvm.JvmName("getDay")
        get() = _builder.day
      @kotlin.jvm.JvmName("setDay")
        set(value) {
        _builder.day = value
      }
    /**
     * `string day = 3 [json_name = "day"];`
     */
    public fun clearDay() {
      _builder.clearDay()
    }

    /**
     * `bool on = 4 [json_name = "on"];`
     */
    public var on: kotlin.Boolean
      @kotlin.jvm.JvmName("getOn")
        get() = _builder.on
      @kotlin.jvm.JvmName("setOn")
        set(value) {
        _builder.on = value
      }
    /**
     * `bool on = 4 [json_name = "on"];`
     */
    public fun clearOn() {
      _builder.clearOn()
    }
  }
}
public inline fun app.pochical.v1.ChatVote.copy(block: `app.pochical.v1`.ChatVoteKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ChatVote =
  `app.pochical.v1`.ChatVoteKt.Dsl._create(this.toBuilder()).apply { block() }._build()

