// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializechatUnsend")
public inline fun chatUnsend(block: app.pochical.v1.ChatUnsendKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ChatUnsend =
  app.pochical.v1.ChatUnsendKt.Dsl._create(app.pochical.v1.ChatUnsend.newBuilder()).apply { block() }._build()
/**
 * ```
 * One of the member's own lines taken back (送信取消).
 * ```
 *
 * Protobuf type `pochical.v1.ChatUnsend`
 */
public object ChatUnsendKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.ChatUnsend.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.ChatUnsend.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.ChatUnsend = _builder.build()

    /**
     * `string thread_id = 1 [json_name = "threadId"];`
     */
    public var threadId: kotlin.String
      @kotlin.jvm.JvmName("getThreadId")
        get() = _builder.threadId
      @kotlin.jvm.JvmName("setThreadId")
        set(value) {
        _builder.threadId = value
      }
    /**
     * `string thread_id = 1 [json_name = "threadId"];`
     */
    public fun clearThreadId() {
      _builder.clearThreadId()
    }

    /**
     * `uint64 seq = 2 [json_name = "seq"];`
     */
    public var seq: kotlin.Long
      @kotlin.jvm.JvmName("getSeq")
        get() = _builder.seq
      @kotlin.jvm.JvmName("setSeq")
        set(value) {
        _builder.seq = value
      }
    /**
     * `uint64 seq = 2 [json_name = "seq"];`
     */
    public fun clearSeq() {
      _builder.clearSeq()
    }
  }
}
public inline fun app.pochical.v1.ChatUnsend.copy(block: `app.pochical.v1`.ChatUnsendKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ChatUnsend =
  `app.pochical.v1`.ChatUnsendKt.Dsl._create(this.toBuilder()).apply { block() }._build()

