// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializechatPage")
public inline fun chatPage(block: app.pochical.v1.ChatPageKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ChatPage =
  app.pochical.v1.ChatPageKt.Dsl._create(app.pochical.v1.ChatPage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Up to chatRules.pageSize lines of a chat before the asked one, oldest
 * first.
 * ```
 *
 * Protobuf type `pochical.v1.ChatPage`
 */
public object ChatPageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.ChatPage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.ChatPage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.ChatPage = _builder.build()

    /**
     * `string thread_id = 1 [json_name = "threadId"];`
     */
    public var threadId: kotlin.String
      @kotlin.jvm.JvmName("getThreadId")
        get() = _builder.threadId
      @kotlin.jvm.JvmName("setThreadId")
        set(value) {
        _builder.threadId = value
      }
    /**
     * `string thread_id = 1 [json_name = "threadId"];`
     */
    public fun clearThreadId() {
      _builder.clearThreadId()
    }

    /**
     * `uint64 before_seq = 2 [json_name = "beforeSeq"];`
     */
    public var beforeSeq: kotlin.Long
      @kotlin.jvm.JvmName("getBeforeSeq")
        get() = _builder.beforeSeq
      @kotlin.jvm.JvmName("setBeforeSeq")
        set(value) {
        _builder.beforeSeq = value
      }
    /**
     * `uint64 before_seq = 2 [json_name = "beforeSeq"];`
     */
    public fun clearBeforeSeq() {
      _builder.clearBeforeSeq()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LinesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .pochical.v1.ChatLine lines = 3 [json_name = "lines"];`
     */
     public val lines: com.google.protobuf.kotlin.DslList<app.pochical.v1.ChatLine, LinesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.linesList
      )
    /**
     * `repeated .pochical.v1.ChatLine lines = 3 [json_name = "lines"];`
     * @param value The lines to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addLines")
    public fun com.google.protobuf.kotlin.DslList<app.pochical.v1.ChatLine, LinesProxy>.add(value: app.pochical.v1.ChatLine) {
      _builder.addLines(value)
    }
    /**
     * `repeated .pochical.v1.ChatLine lines = 3 [json_name = "lines"];`
     * @param value The lines to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignLines")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<app.pochical.v1.ChatLine, LinesProxy>.plusAssign(value: app.pochical.v1.ChatLine) {
      add(value)
    }
    /**
     * `repeated .pochical.v1.ChatLine lines = 3 [json_name = "lines"];`
     * @param values The lines to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllLines")
    public fun com.google.protobuf.kotlin.DslList<app.pochical.v1.ChatLine, LinesProxy>.addAll(values: kotlin.collections.Iterable<app.pochical.v1.ChatLine>) {
      _builder.addAllLines(values)
    }
    /**
     * `repeated .pochical.v1.ChatLine lines = 3 [json_name = "lines"];`
     * @param values The lines to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllLines")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<app.pochical.v1.ChatLine, LinesProxy>.plusAssign(values: kotlin.collections.Iterable<app.pochical.v1.ChatLine>) {
      addAll(values)
    }
    /**
     * `repeated .pochical.v1.ChatLine lines = 3 [json_name = "lines"];`
     * @param index The index to set the value at.
     * @param value The lines to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setLines")
    public operator fun com.google.protobuf.kotlin.DslList<app.pochical.v1.ChatLine, LinesProxy>.set(index: kotlin.Int, value: app.pochical.v1.ChatLine) {
      _builder.setLines(index, value)
    }
    /**
     * `repeated .pochical.v1.ChatLine lines = 3 [json_name = "lines"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearLines")
    public fun com.google.protobuf.kotlin.DslList<app.pochical.v1.ChatLine, LinesProxy>.clear() {
      _builder.clearLines()
    }

    /**
     * ```
     * The page reaches the chat's first line.
     * ```
     *
     * `bool at_start = 4 [json_name = "atStart"];`
     */
    public var atStart: kotlin.Boolean
      @kotlin.jvm.JvmName("getAtStart")
        get() = _builder.atStart
      @kotlin.jvm.JvmName("setAtStart")
        set(value) {
        _builder.atStart = value
      }
    /**
     * ```
     * The page reaches the chat's first line.
     * ```
     *
     * `bool at_start = 4 [json_name = "atStart"];`
     */
    public fun clearAtStart() {
      _builder.clearAtStart()
    }
  }
}
public inline fun app.pochical.v1.ChatPage.copy(block: `app.pochical.v1`.ChatPageKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ChatPage =
  `app.pochical.v1`.ChatPageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

