// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializeclientFrame")
public inline fun clientFrame(block: app.pochical.v1.ClientFrameKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ClientFrame =
  app.pochical.v1.ClientFrameKt.Dsl._create(app.pochical.v1.ClientFrame.newBuilder()).apply { block() }._build()
/**
 * ```
 * Every binary WebSocket message from a client is one ClientFrame.
 * ```
 *
 * Protobuf type `pochical.v1.ClientFrame`
 */
public object ClientFrameKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.ClientFrame.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.ClientFrame.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.ClientFrame = _builder.build()

    /**
     * `.pochical.v1.Hello hello = 1 [json_name = "hello"];`
     */
    public var hello: app.pochical.v1.Hello
      @kotlin.jvm.JvmName("getHello")
        get() = _builder.hello
      @kotlin.jvm.JvmName("setHello")
        set(value) {
        _builder.hello = value
      }
    /**
     * `.pochical.v1.Hello hello = 1 [json_name = "hello"];`
     */
    public fun clearHello() {
      _builder.clearHello()
    }
    /**
     * `.pochical.v1.Hello hello = 1 [json_name = "hello"];`
     * @return Whether the hello field is set.
     */
    public fun hasHello(): kotlin.Boolean {
      return _builder.hasHello()
    }

    /**
     * `.pochical.v1.Ping ping = 2 [json_name = "ping"];`
     */
    public var ping: app.pochical.v1.Ping
      @kotlin.jvm.JvmName("getPing")
        get() = _builder.ping
      @kotlin.jvm.JvmName("setPing")
        set(value) {
        _builder.ping = value
      }
    /**
     * `.pochical.v1.Ping ping = 2 [json_name = "ping"];`
     */
    public fun clearPing() {
      _builder.clearPing()
    }
    /**
     * `.pochical.v1.Ping ping = 2 [json_name = "ping"];`
     * @return Whether the ping field is set.
     */
    public fun hasPing(): kotlin.Boolean {
      return _builder.hasPing()
    }

    /**
     * ```
     * The owner's own day edits, from their outbox; User DO socket only.
     * ```
     *
     * `.pochical.v1.DayEdits day_edits = 3 [json_name = "dayEdits"];`
     */
    public var dayEdits: app.pochical.v1.DayEdits
      @kotlin.jvm.JvmName("getDayEdits")
        get() = _builder.dayEdits
      @kotlin.jvm.JvmName("setDayEdits")
        set(value) {
        _builder.dayEdits = value
      }
    /**
     * ```
     * The owner's own day edits, from their outbox; User DO socket only.
     * ```
     *
     * `.pochical.v1.DayEdits day_edits = 3 [json_name = "dayEdits"];`
     */
    public fun clearDayEdits() {
      _builder.clearDayEdits()
    }
    /**
     * ```
     * The owner's own day edits, from their outbox; User DO socket only.
     * ```
     *
     * `.pochical.v1.DayEdits day_edits = 3 [json_name = "dayEdits"];`
     * @return Whether the dayEdits field is set.
     */
    public fun hasDayEdits(): kotlin.Boolean {
      return _builder.hasDayEdits()
    }

    /**
     * ```
     * The owner's pattern edits, from the same outbox; User DO socket only.
     * ```
     *
     * `.pochical.v1.PatternEdits pattern_edits = 4 [json_name = "patternEdits"];`
     */
    public var patternEdits: app.pochical.v1.PatternEdits
      @kotlin.jvm.JvmName("getPatternEdits")
        get() = _builder.patternEdits
      @kotlin.jvm.JvmName("setPatternEdits")
        set(value) {
        _builder.patternEdits = value
      }
    /**
     * ```
     * The owner's pattern edits, from the same outbox; User DO socket only.
     * ```
     *
     * `.pochical.v1.PatternEdits pattern_edits = 4 [json_name = "patternEdits"];`
     */
    public fun clearPatternEdits() {
      _builder.clearPatternEdits()
    }
    /**
     * ```
     * The owner's pattern edits, from the same outbox; User DO socket only.
     * ```
     *
     * `.pochical.v1.PatternEdits pattern_edits = 4 [json_name = "patternEdits"];`
     * @return Whether the patternEdits field is set.
     */
    public fun hasPatternEdits(): kotlin.Boolean {
      return _builder.hasPatternEdits()
    }
    public val kindCase: app.pochical.v1.ClientFrame.KindCase
    @kotlin.jvm.JvmName("getKindCase")
      get() = _builder.kindCase

    public fun clearKind() {
      _builder.clearKind()
    }
  }
}
public inline fun app.pochical.v1.ClientFrame.copy(block: `app.pochical.v1`.ClientFrameKt.Dsl.() -> kotlin.Unit): app.pochical.v1.ClientFrame =
  `app.pochical.v1`.ClientFrameKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val app.pochical.v1.ClientFrameOrBuilder.helloOrNull: app.pochical.v1.Hello?
  get() = if (hasHello()) getHello() else null

public val app.pochical.v1.ClientFrameOrBuilder.pingOrNull: app.pochical.v1.Ping?
  get() = if (hasPing()) getPing() else null

public val app.pochical.v1.ClientFrameOrBuilder.dayEditsOrNull: app.pochical.v1.DayEdits?
  get() = if (hasDayEdits()) getDayEdits() else null

public val app.pochical.v1.ClientFrameOrBuilder.patternEditsOrNull: app.pochical.v1.PatternEdits?
  get() = if (hasPatternEdits()) getPatternEdits() else null

