// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializedayValue")
public inline fun dayValue(block: app.pochical.v1.DayValueKt.Dsl.() -> kotlin.Unit): app.pochical.v1.DayValue =
  app.pochical.v1.DayValueKt.Dsl._create(app.pochical.v1.DayValue.newBuilder()).apply { block() }._build()
/**
 * ```
 * One field of one day, as a device set it or as the server holds it.
 * ```
 *
 * Protobuf type `pochical.v1.DayValue`
 */
public object DayValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.DayValue.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.DayValue.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.DayValue = _builder.build()

    /**
     * ```
     * The day, "YYYY-MM-DD".
     * ```
     *
     * `string date = 1 [json_name = "date"];`
     */
    public var date: kotlin.String
      @kotlin.jvm.JvmName("getDate")
        get() = _builder.date
      @kotlin.jvm.JvmName("setDate")
        set(value) {
        _builder.date = value
      }
    /**
     * ```
     * The day, "YYYY-MM-DD".
     * ```
     *
     * `string date = 1 [json_name = "date"];`
     */
    public fun clearDate() {
      _builder.clearDate()
    }

    /**
     * `.pochical.v1.DayField field = 2 [json_name = "field"];`
     */
    public var field: app.pochical.v1.DayField
      @kotlin.jvm.JvmName("getField")
        get() = _builder.field
      @kotlin.jvm.JvmName("setField")
        set(value) {
        _builder.field = value
      }
    public var fieldValue: kotlin.Int
      @kotlin.jvm.JvmName("getFieldValue")
        get() = _builder.fieldValue
      @kotlin.jvm.JvmName("setFieldValue")
        set(value) {
        _builder.fieldValue = value
      }
    /**
     * `.pochical.v1.DayField field = 2 [json_name = "field"];`
     */
    public fun clearField() {
      _builder.clearField()
    }

    /**
     * ```
     * Unset clears the field. A day with no pattern follows its repeating
     * order, if any; a pattern of "" (dayRules.noShift, design/src/days.ts)
     * is a day with no shift
     * (spec/sync-protocol.md, Repeating orders).
     * ```
     *
     * `optional string value = 3 [json_name = "value"];`
     */
    public var value: kotlin.String
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * ```
     * Unset clears the field. A day with no pattern follows its repeating
     * order, if any; a pattern of "" (dayRules.noShift, design/src/days.ts)
     * is a day with no shift
     * (spec/sync-protocol.md, Repeating orders).
     * ```
     *
     * `optional string value = 3 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * ```
     * Unset clears the field. A day with no pattern follows its repeating
     * order, if any; a pattern of "" (dayRules.noShift, design/src/days.ts)
     * is a day with no shift
     * (spec/sync-protocol.md, Repeating orders).
     * ```
     *
     * `optional string value = 3 [json_name = "value"];`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }

    /**
     * `.pochical.v1.Hlc hlc = 4 [json_name = "hlc"];`
     */
    public var hlc: app.pochical.v1.Hlc
      @kotlin.jvm.JvmName("getHlc")
        get() = _builder.hlc
      @kotlin.jvm.JvmName("setHlc")
        set(value) {
        _builder.hlc = value
      }
    /**
     * `.pochical.v1.Hlc hlc = 4 [json_name = "hlc"];`
     */
    public fun clearHlc() {
      _builder.clearHlc()
    }
    /**
     * `.pochical.v1.Hlc hlc = 4 [json_name = "hlc"];`
     * @return Whether the hlc field is set.
     */
    public fun hasHlc(): kotlin.Boolean {
      return _builder.hasHlc()
    }

    public val DayValueKt.Dsl.hlcOrNull: app.pochical.v1.Hlc?
      get() = _builder.hlcOrNull
  }
}
public inline fun app.pochical.v1.DayValue.copy(block: `app.pochical.v1`.DayValueKt.Dsl.() -> kotlin.Unit): app.pochical.v1.DayValue =
  `app.pochical.v1`.DayValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val app.pochical.v1.DayValueOrBuilder.hlcOrNull: app.pochical.v1.Hlc?
  get() = if (hasHlc()) getHlc() else null

