// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/user.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializedeleteAccountResponse")
public inline fun deleteAccountResponse(block: app.pochical.v1.DeleteAccountResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.DeleteAccountResponse =
  app.pochical.v1.DeleteAccountResponseKt.Dsl._create(app.pochical.v1.DeleteAccountResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.DeleteAccountResponse`
 */
public object DeleteAccountResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.DeleteAccountResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.DeleteAccountResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.DeleteAccountResponse = _builder.build()
  }
}
public inline fun app.pochical.v1.DeleteAccountResponse.copy(block: `app.pochical.v1`.DeleteAccountResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.DeleteAccountResponse =
  `app.pochical.v1`.DeleteAccountResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

