// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/invite.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializegetInvitePreviewResponse")
public inline fun getInvitePreviewResponse(block: app.pochical.v1.GetInvitePreviewResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.GetInvitePreviewResponse =
  app.pochical.v1.GetInvitePreviewResponseKt.Dsl._create(app.pochical.v1.GetInvitePreviewResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.GetInvitePreviewResponse`
 */
public object GetInvitePreviewResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.GetInvitePreviewResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.GetInvitePreviewResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.GetInvitePreviewResponse = _builder.build()

    /**
     * `string group_name = 1 [json_name = "groupName"];`
     */
    public var groupName: kotlin.String
      @kotlin.jvm.JvmName("getGroupName")
        get() = _builder.groupName
      @kotlin.jvm.JvmName("setGroupName")
        set(value) {
        _builder.groupName = value
      }
    /**
     * `string group_name = 1 [json_name = "groupName"];`
     */
    public fun clearGroupName() {
      _builder.clearGroupName()
    }

    /**
     * `.pochical.v1.GroupMark group_mark = 4 [json_name = "groupMark"];`
     */
    public var groupMark: app.pochical.v1.GroupMark
      @kotlin.jvm.JvmName("getGroupMark")
        get() = _builder.groupMark
      @kotlin.jvm.JvmName("setGroupMark")
        set(value) {
        _builder.groupMark = value
      }
    /**
     * `.pochical.v1.GroupMark group_mark = 4 [json_name = "groupMark"];`
     */
    public fun clearGroupMark() {
      _builder.clearGroupMark()
    }
    /**
     * `.pochical.v1.GroupMark group_mark = 4 [json_name = "groupMark"];`
     * @return Whether the groupMark field is set.
     */
    public fun hasGroupMark(): kotlin.Boolean {
      return _builder.hasGroupMark()
    }

    public val GetInvitePreviewResponseKt.Dsl.groupMarkOrNull: app.pochical.v1.GroupMark?
      get() = _builder.groupMarkOrNull

    /**
     * ```
     * How many are in the group, for 「{n}人」 on the page and cards.
     * ```
     *
     * `uint32 member_count = 3 [json_name = "memberCount"];`
     */
    public var memberCount: kotlin.Int
      @kotlin.jvm.JvmName("getMemberCount")
        get() = _builder.memberCount
      @kotlin.jvm.JvmName("setMemberCount")
        set(value) {
        _builder.memberCount = value
      }
    /**
     * ```
     * How many are in the group, for 「{n}人」 on the page and cards.
     * ```
     *
     * `uint32 member_count = 3 [json_name = "memberCount"];`
     */
    public fun clearMemberCount() {
      _builder.clearMemberCount()
    }
  }
}
public inline fun app.pochical.v1.GetInvitePreviewResponse.copy(block: `app.pochical.v1`.GetInvitePreviewResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.GetInvitePreviewResponse =
  `app.pochical.v1`.GetInvitePreviewResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val app.pochical.v1.GetInvitePreviewResponseOrBuilder.groupMarkOrNull: app.pochical.v1.GroupMark?
  get() = if (hasGroupMark()) getGroupMark() else null

