// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/group.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializegetInviteRequest")
public inline fun getInviteRequest(block: app.pochical.v1.GetInviteRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.GetInviteRequest =
  app.pochical.v1.GetInviteRequestKt.Dsl._create(app.pochical.v1.GetInviteRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.GetInviteRequest`
 */
public object GetInviteRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.GetInviteRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.GetInviteRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.GetInviteRequest = _builder.build()

    /**
     * `string invite_code = 1 [json_name = "inviteCode"];`
     */
    public var inviteCode: kotlin.String
      @kotlin.jvm.JvmName("getInviteCode")
        get() = _builder.inviteCode
      @kotlin.jvm.JvmName("setInviteCode")
        set(value) {
        _builder.inviteCode = value
      }
    /**
     * `string invite_code = 1 [json_name = "inviteCode"];`
     */
    public fun clearInviteCode() {
      _builder.clearInviteCode()
    }
  }
}
public inline fun app.pochical.v1.GetInviteRequest.copy(block: `app.pochical.v1`.GetInviteRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.GetInviteRequest =
  `app.pochical.v1`.GetInviteRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

