// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: pochical/v1/group.proto
//
package app.pochical.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  Making groups and getting into them. Every call needs the session token
 *  from better-auth as `Authorization: Bearer <token>` (UNAUTHENTICATED
 *  without one). Names follow spec/text-limits.md, counted in characters as
 *  a reader sees them; a longer or empty one fails with INVALID_ARGUMENT.
 */
public interface GroupServiceClientInterface {
  /**
   *  Makes a group with the caller as its first member, and its first
   *  invitation link. Repeating it with the same request_id changes nothing
   *  and answers the same.
   */
  public suspend fun createGroup(request: CreateGroupRequest, headers: Headers = emptyMap()): ResponseMessage<CreateGroupResponse>

  /**
   *  The group's live invitation code. Members only (PERMISSION_DENIED
   *  otherwise).
   */
  public suspend fun getInviteLink(request: GetInviteLinkRequest, headers: Headers = emptyMap()): ResponseMessage<GetInviteLinkResponse>

  /**
   *  Replaces the group's invitation code: the old link and QR code stop
   *  working at once; members stay. Members only.
   */
  public suspend fun remakeInviteLink(request: RemakeInviteLinkRequest, headers: Headers = emptyMap()): ResponseMessage<RemakeInviteLinkResponse>

  /**
   *  Who is in the group a live code opens, for the join screen to show
   *  before joining. Signed in only: the public preview
   *  (InviteService.GetInvitePreview) gives no names. NOT_FOUND when no
   *  group uses the code.
   */
  public suspend fun getInvite(request: GetInviteRequest, headers: Headers = emptyMap()): ResponseMessage<GetInviteResponse>

  /**
   *  Joins the group a live code opens. NOT_FOUND when no group uses it;
   *  RESOURCE_EXHAUSTED when it already has its most members
   *  (GROUP_MAX_MEMBERS in design/src/limits.ts).
   *  Joining a group you are already in changes nothing and says so.
   */
  public suspend fun joinGroup(request: JoinGroupRequest, headers: Headers = emptyMap()): ResponseMessage<JoinGroupResponse>

  /**
   *  Gives the group a new name and mark, which every member sees. Members
   *  only.
   */
  public suspend fun renameGroup(request: RenameGroupRequest, headers: Headers = emptyMap()): ResponseMessage<RenameGroupResponse>

  /**
   *  How the caller appears in the group from now on. Members only.
   */
  public suspend fun setDisplayName(request: SetDisplayNameRequest, headers: Headers = emptyMap()): ResponseMessage<SetDisplayNameResponse>

  /**
   *  The caller's photo in the group from now on: their usual one, one of
   *  the group's photos they uploaded, or none. Members only.
   */
  public suspend fun setGroupPhoto(request: SetGroupPhotoRequest, headers: Headers = emptyMap()): ResponseMessage<SetGroupPhotoResponse>

  /**
   *  Takes the caller out of the group: what it holds of their shifts goes,
   *  and its socket and calls refuse them until they join again by a live
   *  link. Leaving a group you are not in changes nothing.
   */
  public suspend fun leaveGroup(request: LeaveGroupRequest, headers: Headers = emptyMap()): ResponseMessage<LeaveGroupResponse>
}
