// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/group.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializeinviteMember")
public inline fun inviteMember(block: app.pochical.v1.InviteMemberKt.Dsl.() -> kotlin.Unit): app.pochical.v1.InviteMember =
  app.pochical.v1.InviteMemberKt.Dsl._create(app.pochical.v1.InviteMember.newBuilder()).apply { block() }._build()
/**
 * ```
 * Someone in a group, as the join screen shows them.
 * ```
 *
 * Protobuf type `pochical.v1.InviteMember`
 */
public object InviteMemberKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.InviteMember.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.InviteMember.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.InviteMember = _builder.build()

    /**
     * `string display_name = 1 [json_name = "displayName"];`
     */
    public var displayName: kotlin.String
      @kotlin.jvm.JvmName("getDisplayName")
        get() = _builder.displayName
      @kotlin.jvm.JvmName("setDisplayName")
        set(value) {
        _builder.displayName = value
      }
    /**
     * `string display_name = 1 [json_name = "displayName"];`
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }
  }
}
public inline fun app.pochical.v1.InviteMember.copy(block: `app.pochical.v1`.InviteMemberKt.Dsl.() -> kotlin.Unit): app.pochical.v1.InviteMember =
  `app.pochical.v1`.InviteMemberKt.Dsl._create(this.toBuilder()).apply { block() }._build()

