// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/group.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializeleaveGroupResponse")
public inline fun leaveGroupResponse(block: app.pochical.v1.LeaveGroupResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.LeaveGroupResponse =
  app.pochical.v1.LeaveGroupResponseKt.Dsl._create(app.pochical.v1.LeaveGroupResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.LeaveGroupResponse`
 */
public object LeaveGroupResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.LeaveGroupResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.LeaveGroupResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.LeaveGroupResponse = _builder.build()
  }
}
public inline fun app.pochical.v1.LeaveGroupResponse.copy(block: `app.pochical.v1`.LeaveGroupResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.LeaveGroupResponse =
  `app.pochical.v1`.LeaveGroupResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

