// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializemember")
public inline fun member(block: app.pochical.v1.MemberKt.Dsl.() -> kotlin.Unit): app.pochical.v1.Member =
  app.pochical.v1.MemberKt.Dsl._create(app.pochical.v1.Member.newBuilder()).apply { block() }._build()
/**
 * ```
 * Someone in the group, as they appear in it.
 * ```
 *
 * Protobuf type `pochical.v1.Member`
 */
public object MemberKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.Member.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.Member.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.Member = _builder.build()

    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * ```
     * personName characters at most (design/src/limits.ts).
     * ```
     *
     * `string display_name = 2 [json_name = "displayName"];`
     */
    public var displayName: kotlin.String
      @kotlin.jvm.JvmName("getDisplayName")
        get() = _builder.displayName
      @kotlin.jvm.JvmName("setDisplayName")
        set(value) {
        _builder.displayName = value
      }
    /**
     * ```
     * personName characters at most (design/src/limits.ts).
     * ```
     *
     * `string display_name = 2 [json_name = "displayName"];`
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }

    /**
     * ```
     * When they joined, in ms since the epoch: the group's order of members.
     * ```
     *
     * `int64 joined_at_ms = 3 [json_name = "joinedAtMs"];`
     */
    public var joinedAtMs: kotlin.Long
      @kotlin.jvm.JvmName("getJoinedAtMs")
        get() = _builder.joinedAtMs
      @kotlin.jvm.JvmName("setJoinedAtMs")
        set(value) {
        _builder.joinedAtMs = value
      }
    /**
     * ```
     * When they joined, in ms since the epoch: the group's order of members.
     * ```
     *
     * `int64 joined_at_ms = 3 [json_name = "joinedAtMs"];`
     */
    public fun clearJoinedAtMs() {
      _builder.clearJoinedAtMs()
    }
  }
}
public inline fun app.pochical.v1.Member.copy(block: `app.pochical.v1`.MemberKt.Dsl.() -> kotlin.Unit): app.pochical.v1.Member =
  `app.pochical.v1`.MemberKt.Dsl._create(this.toBuilder()).apply { block() }._build()

