// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializepreferenceValue")
public inline fun preferenceValue(block: app.pochical.v1.PreferenceValueKt.Dsl.() -> kotlin.Unit): app.pochical.v1.PreferenceValue =
  app.pochical.v1.PreferenceValueKt.Dsl._create(app.pochical.v1.PreferenceValue.newBuilder()).apply { block() }._build()
/**
 * ```
 * One of the owner's preferences, how they like their screens: one
 * last-writer-wins value a key, kept with the account so each of their
 * devices shows the same (spec/sync-protocol.md, Preferences). The server
 * keeps what it is given without reading it; the apps read the value.
 * ```
 *
 * Protobuf type `pochical.v1.PreferenceValue`
 */
public object PreferenceValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.PreferenceValue.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.PreferenceValue.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.PreferenceValue = _builder.build()

    /**
     * ```
     * Which preference, as the apps name it: an id (syncLimits.idLength).
     * ```
     *
     * `string key = 1 [json_name = "key"];`
     */
    public var key: kotlin.String
      @kotlin.jvm.JvmName("getKey")
        get() = _builder.key
      @kotlin.jvm.JvmName("setKey")
        set(value) {
        _builder.key = value
      }
    /**
     * ```
     * Which preference, as the apps name it: an id (syncLimits.idLength).
     * ```
     *
     * `string key = 1 [json_name = "key"];`
     */
    public fun clearKey() {
      _builder.clearKey()
    }

    /**
     * ```
     * As the apps write it, JSON, syncLimits.preferenceLength characters at
     * most. Unset: none kept, so each device keeps its own.
     * ```
     *
     * `optional string value = 2 [json_name = "value"];`
     */
    public var value: kotlin.String
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * ```
     * As the apps write it, JSON, syncLimits.preferenceLength characters at
     * most. Unset: none kept, so each device keeps its own.
     * ```
     *
     * `optional string value = 2 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * ```
     * As the apps write it, JSON, syncLimits.preferenceLength characters at
     * most. Unset: none kept, so each device keeps its own.
     * ```
     *
     * `optional string value = 2 [json_name = "value"];`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }

    /**
     * `.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];`
     */
    public var hlc: app.pochical.v1.Hlc
      @kotlin.jvm.JvmName("getHlc")
        get() = _builder.hlc
      @kotlin.jvm.JvmName("setHlc")
        set(value) {
        _builder.hlc = value
      }
    /**
     * `.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];`
     */
    public fun clearHlc() {
      _builder.clearHlc()
    }
    /**
     * `.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];`
     * @return Whether the hlc field is set.
     */
    public fun hasHlc(): kotlin.Boolean {
      return _builder.hasHlc()
    }

    public val PreferenceValueKt.Dsl.hlcOrNull: app.pochical.v1.Hlc?
      get() = _builder.hlcOrNull
  }
}
public inline fun app.pochical.v1.PreferenceValue.copy(block: `app.pochical.v1`.PreferenceValueKt.Dsl.() -> kotlin.Unit): app.pochical.v1.PreferenceValue =
  `app.pochical.v1`.PreferenceValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val app.pochical.v1.PreferenceValueOrBuilder.hlcOrNull: app.pochical.v1.Hlc?
  get() = if (hasHlc()) getHlc() else null

