// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializepreferenceEdit")
public inline fun preferenceEdit(block: app.pochical.v1.PreferenceEditKt.Dsl.() -> kotlin.Unit): app.pochical.v1.PreferenceEdit =
  app.pochical.v1.PreferenceEditKt.Dsl._create(app.pochical.v1.PreferenceEdit.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.PreferenceEdit`
 */
public object PreferenceEditKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.PreferenceEdit.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.PreferenceEdit.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.PreferenceEdit = _builder.build()

    /**
     * ```
     * Unique per edit, as a DayEdit's.
     * ```
     *
     * `string op_id = 1 [json_name = "opId"];`
     */
    public var opId: kotlin.String
      @kotlin.jvm.JvmName("getOpId")
        get() = _builder.opId
      @kotlin.jvm.JvmName("setOpId")
        set(value) {
        _builder.opId = value
      }
    /**
     * ```
     * Unique per edit, as a DayEdit's.
     * ```
     *
     * `string op_id = 1 [json_name = "opId"];`
     */
    public fun clearOpId() {
      _builder.clearOpId()
    }

    /**
     * `.pochical.v1.PreferenceValue value = 2 [json_name = "value"];`
     */
    public var value: app.pochical.v1.PreferenceValue
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * `.pochical.v1.PreferenceValue value = 2 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * `.pochical.v1.PreferenceValue value = 2 [json_name = "value"];`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }

    public val PreferenceEditKt.Dsl.valueOrNull: app.pochical.v1.PreferenceValue?
      get() = _builder.valueOrNull
  }
}
public inline fun app.pochical.v1.PreferenceEdit.copy(block: `app.pochical.v1`.PreferenceEditKt.Dsl.() -> kotlin.Unit): app.pochical.v1.PreferenceEdit =
  `app.pochical.v1`.PreferenceEditKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val app.pochical.v1.PreferenceEditOrBuilder.valueOrNull: app.pochical.v1.PreferenceValue?
  get() = if (hasValue()) getValue() else null

