// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/user.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializeregisterPushTokenRequest")
public inline fun registerPushTokenRequest(block: app.pochical.v1.RegisterPushTokenRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.RegisterPushTokenRequest =
  app.pochical.v1.RegisterPushTokenRequestKt.Dsl._create(app.pochical.v1.RegisterPushTokenRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.RegisterPushTokenRequest`
 */
public object RegisterPushTokenRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.RegisterPushTokenRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.RegisterPushTokenRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.RegisterPushTokenRequest = _builder.build()

    /**
     * ```
     * The device's APNs token, as hex.
     * ```
     *
     * `string token = 1 [json_name = "token"];`
     */
    public var token: kotlin.String
      @kotlin.jvm.JvmName("getToken")
        get() = _builder.token
      @kotlin.jvm.JvmName("setToken")
        set(value) {
        _builder.token = value
      }
    /**
     * ```
     * The device's APNs token, as hex.
     * ```
     *
     * `string token = 1 [json_name = "token"];`
     */
    public fun clearToken() {
      _builder.clearToken()
    }

    /**
     * ```
     * From a development build: sent through APNs' sandbox.
     * ```
     *
     * `bool sandbox = 2 [json_name = "sandbox"];`
     */
    public var sandbox: kotlin.Boolean
      @kotlin.jvm.JvmName("getSandbox")
        get() = _builder.sandbox
      @kotlin.jvm.JvmName("setSandbox")
        set(value) {
        _builder.sandbox = value
      }
    /**
     * ```
     * From a development build: sent through APNs' sandbox.
     * ```
     *
     * `bool sandbox = 2 [json_name = "sandbox"];`
     */
    public fun clearSandbox() {
      _builder.clearSandbox()
    }
  }
}
public inline fun app.pochical.v1.RegisterPushTokenRequest.copy(block: `app.pochical.v1`.RegisterPushTokenRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.RegisterPushTokenRequest =
  `app.pochical.v1`.RegisterPushTokenRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

