// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializerepeatOrdersEdits")
public inline fun repeatOrdersEdits(block: app.pochical.v1.RepeatOrdersEditsKt.Dsl.() -> kotlin.Unit): app.pochical.v1.RepeatOrdersEdits =
  app.pochical.v1.RepeatOrdersEditsKt.Dsl._create(app.pochical.v1.RepeatOrdersEdits.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.RepeatOrdersEdits`
 */
public object RepeatOrdersEditsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.RepeatOrdersEdits.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.RepeatOrdersEdits.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.RepeatOrdersEdits = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EditsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .pochical.v1.RepeatOrdersEdit edits = 1 [json_name = "edits"];`
     */
     public val edits: com.google.protobuf.kotlin.DslList<app.pochical.v1.RepeatOrdersEdit, EditsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.editsList
      )
    /**
     * `repeated .pochical.v1.RepeatOrdersEdit edits = 1 [json_name = "edits"];`
     * @param value The edits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addEdits")
    public fun com.google.protobuf.kotlin.DslList<app.pochical.v1.RepeatOrdersEdit, EditsProxy>.add(value: app.pochical.v1.RepeatOrdersEdit) {
      _builder.addEdits(value)
    }
    /**
     * `repeated .pochical.v1.RepeatOrdersEdit edits = 1 [json_name = "edits"];`
     * @param value The edits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignEdits")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<app.pochical.v1.RepeatOrdersEdit, EditsProxy>.plusAssign(value: app.pochical.v1.RepeatOrdersEdit) {
      add(value)
    }
    /**
     * `repeated .pochical.v1.RepeatOrdersEdit edits = 1 [json_name = "edits"];`
     * @param values The edits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllEdits")
    public fun com.google.protobuf.kotlin.DslList<app.pochical.v1.RepeatOrdersEdit, EditsProxy>.addAll(values: kotlin.collections.Iterable<app.pochical.v1.RepeatOrdersEdit>) {
      _builder.addAllEdits(values)
    }
    /**
     * `repeated .pochical.v1.RepeatOrdersEdit edits = 1 [json_name = "edits"];`
     * @param values The edits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllEdits")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<app.pochical.v1.RepeatOrdersEdit, EditsProxy>.plusAssign(values: kotlin.collections.Iterable<app.pochical.v1.RepeatOrdersEdit>) {
      addAll(values)
    }
    /**
     * `repeated .pochical.v1.RepeatOrdersEdit edits = 1 [json_name = "edits"];`
     * @param index The index to set the value at.
     * @param value The edits to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setEdits")
    public operator fun com.google.protobuf.kotlin.DslList<app.pochical.v1.RepeatOrdersEdit, EditsProxy>.set(index: kotlin.Int, value: app.pochical.v1.RepeatOrdersEdit) {
      _builder.setEdits(index, value)
    }
    /**
     * `repeated .pochical.v1.RepeatOrdersEdit edits = 1 [json_name = "edits"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearEdits")
    public fun com.google.protobuf.kotlin.DslList<app.pochical.v1.RepeatOrdersEdit, EditsProxy>.clear() {
      _builder.clearEdits()
    }
  }
}
public inline fun app.pochical.v1.RepeatOrdersEdits.copy(block: `app.pochical.v1`.RepeatOrdersEditsKt.Dsl.() -> kotlin.Unit): app.pochical.v1.RepeatOrdersEdits =
  `app.pochical.v1`.RepeatOrdersEditsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

