// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/support.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializesendSupportMessageRequest")
public inline fun sendSupportMessageRequest(block: app.pochical.v1.SendSupportMessageRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SendSupportMessageRequest =
  app.pochical.v1.SendSupportMessageRequestKt.Dsl._create(app.pochical.v1.SendSupportMessageRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.SendSupportMessageRequest`
 */
public object SendSupportMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.SendSupportMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.SendSupportMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.SendSupportMessageRequest = _builder.build()

    /**
     * ```
     * The app's own id for the line, a UUID.
     * ```
     *
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * The app's own id for the line, a UUID.
     * ```
     *
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string text = 2 [json_name = "text"];`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `string text = 2 [json_name = "text"];`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * The app's version and the device, as the chat's head says reach
     * Pochical's people with what is written: ポチカル 1.0・iPhone (iOS 26.0).
     * ```
     *
     * `string device = 3 [json_name = "device"];`
     */
    public var device: kotlin.String
      @kotlin.jvm.JvmName("getDevice")
        get() = _builder.device
      @kotlin.jvm.JvmName("setDevice")
        set(value) {
        _builder.device = value
      }
    /**
     * ```
     * The app's version and the device, as the chat's head says reach
     * Pochical's people with what is written: ポチカル 1.0・iPhone (iOS 26.0).
     * ```
     *
     * `string device = 3 [json_name = "device"];`
     */
    public fun clearDevice() {
      _builder.clearDevice()
    }

    /**
     * ```
     * The line it is a reply to, by id, when it is one; one not in the chat
     * is left out.
     * ```
     *
     * `string reply_to = 4 [json_name = "replyTo"];`
     */
    public var replyTo: kotlin.String
      @kotlin.jvm.JvmName("getReplyTo")
        get() = _builder.replyTo
      @kotlin.jvm.JvmName("setReplyTo")
        set(value) {
        _builder.replyTo = value
      }
    /**
     * ```
     * The line it is a reply to, by id, when it is one; one not in the chat
     * is left out.
     * ```
     *
     * `string reply_to = 4 [json_name = "replyTo"];`
     */
    public fun clearReplyTo() {
      _builder.clearReplyTo()
    }

    /**
     * ```
     * A photo already uploaded, sent with no words. FAILED_PRECONDITION
     * while it is not uploaded.
     * ```
     *
     * `.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];`
     */
    public var photo: app.pochical.v1.ChatPhoto
      @kotlin.jvm.JvmName("getPhoto")
        get() = _builder.photo
      @kotlin.jvm.JvmName("setPhoto")
        set(value) {
        _builder.photo = value
      }
    /**
     * ```
     * A photo already uploaded, sent with no words. FAILED_PRECONDITION
     * while it is not uploaded.
     * ```
     *
     * `.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];`
     */
    public fun clearPhoto() {
      _builder.clearPhoto()
    }
    /**
     * ```
     * A photo already uploaded, sent with no words. FAILED_PRECONDITION
     * while it is not uploaded.
     * ```
     *
     * `.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];`
     * @return Whether the photo field is set.
     */
    public fun hasPhoto(): kotlin.Boolean {
      return _builder.hasPhoto()
    }

    public val SendSupportMessageRequestKt.Dsl.photoOrNull: app.pochical.v1.ChatPhoto?
      get() = _builder.photoOrNull
  }
}
public inline fun app.pochical.v1.SendSupportMessageRequest.copy(block: `app.pochical.v1`.SendSupportMessageRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SendSupportMessageRequest =
  `app.pochical.v1`.SendSupportMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val app.pochical.v1.SendSupportMessageRequestOrBuilder.photoOrNull: app.pochical.v1.ChatPhoto?
  get() = if (hasPhoto()) getPhoto() else null

