// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/support.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializesendSupportMessageRequest")
public inline fun sendSupportMessageRequest(block: app.pochical.v1.SendSupportMessageRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SendSupportMessageRequest =
  app.pochical.v1.SendSupportMessageRequestKt.Dsl._create(app.pochical.v1.SendSupportMessageRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.SendSupportMessageRequest`
 */
public object SendSupportMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.SendSupportMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.SendSupportMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.SendSupportMessageRequest = _builder.build()

    /**
     * ```
     * The app's own id for the line, a UUID.
     * ```
     *
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * The app's own id for the line, a UUID.
     * ```
     *
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string text = 2 [json_name = "text"];`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `string text = 2 [json_name = "text"];`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * The app's version and the device, as the chat's head says reach
     * Pochical's people with what is written: ポチカル 1.0・iPhone (iOS 26.0).
     * ```
     *
     * `string device = 3 [json_name = "device"];`
     */
    public var device: kotlin.String
      @kotlin.jvm.JvmName("getDevice")
        get() = _builder.device
      @kotlin.jvm.JvmName("setDevice")
        set(value) {
        _builder.device = value
      }
    /**
     * ```
     * The app's version and the device, as the chat's head says reach
     * Pochical's people with what is written: ポチカル 1.0・iPhone (iOS 26.0).
     * ```
     *
     * `string device = 3 [json_name = "device"];`
     */
    public fun clearDevice() {
      _builder.clearDevice()
    }
  }
}
public inline fun app.pochical.v1.SendSupportMessageRequest.copy(block: `app.pochical.v1`.SendSupportMessageRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SendSupportMessageRequest =
  `app.pochical.v1`.SendSupportMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

