// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/support.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializesendSupportMessageResponse")
public inline fun sendSupportMessageResponse(block: app.pochical.v1.SendSupportMessageResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SendSupportMessageResponse =
  app.pochical.v1.SendSupportMessageResponseKt.Dsl._create(app.pochical.v1.SendSupportMessageResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.SendSupportMessageResponse`
 */
public object SendSupportMessageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.SendSupportMessageResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.SendSupportMessageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.SendSupportMessageResponse = _builder.build()

    /**
     * `.pochical.v1.SupportMessage message = 1 [json_name = "message"];`
     */
    public var message: app.pochical.v1.SupportMessage
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `.pochical.v1.SupportMessage message = 1 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
    /**
     * `.pochical.v1.SupportMessage message = 1 [json_name = "message"];`
     * @return Whether the message field is set.
     */
    public fun hasMessage(): kotlin.Boolean {
      return _builder.hasMessage()
    }

    public val SendSupportMessageResponseKt.Dsl.messageOrNull: app.pochical.v1.SupportMessage?
      get() = _builder.messageOrNull
  }
}
public inline fun app.pochical.v1.SendSupportMessageResponse.copy(block: `app.pochical.v1`.SendSupportMessageResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SendSupportMessageResponse =
  `app.pochical.v1`.SendSupportMessageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val app.pochical.v1.SendSupportMessageResponseOrBuilder.messageOrNull: app.pochical.v1.SupportMessage?
  get() = if (hasMessage()) getMessage() else null

