// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/user.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializesetBlockedRequest")
public inline fun setBlockedRequest(block: app.pochical.v1.SetBlockedRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SetBlockedRequest =
  app.pochical.v1.SetBlockedRequestKt.Dsl._create(app.pochical.v1.SetBlockedRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.SetBlockedRequest`
 */
public object SetBlockedRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.SetBlockedRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.SetBlockedRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.SetBlockedRequest = _builder.build()

    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 1 [json_name = "userId"];`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `bool blocked = 2 [json_name = "blocked"];`
     */
    public var blocked: kotlin.Boolean
      @kotlin.jvm.JvmName("getBlocked")
        get() = _builder.blocked
      @kotlin.jvm.JvmName("setBlocked")
        set(value) {
        _builder.blocked = value
      }
    /**
     * `bool blocked = 2 [json_name = "blocked"];`
     */
    public fun clearBlocked() {
      _builder.clearBlocked()
    }
  }
}
public inline fun app.pochical.v1.SetBlockedRequest.copy(block: `app.pochical.v1`.SetBlockedRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SetBlockedRequest =
  `app.pochical.v1`.SetBlockedRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

