// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/user.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializesetProfileRequest")
public inline fun setProfileRequest(block: app.pochical.v1.SetProfileRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SetProfileRequest =
  app.pochical.v1.SetProfileRequestKt.Dsl._create(app.pochical.v1.SetProfileRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.SetProfileRequest`
 */
public object SetProfileRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.SetProfileRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.SetProfileRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.SetProfileRequest = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * One of the user's own photos, uploaded to /v1/me/photos/{id} first.
     * ```
     *
     * `string photo_id = 2 [json_name = "photoId"];`
     */
    public var photoId: kotlin.String
      @kotlin.jvm.JvmName("getPhotoId")
        get() = _builder.photoId
      @kotlin.jvm.JvmName("setPhotoId")
        set(value) {
        _builder.photoId = value
      }
    /**
     * ```
     * One of the user's own photos, uploaded to /v1/me/photos/{id} first.
     * ```
     *
     * `string photo_id = 2 [json_name = "photoId"];`
     */
    public fun clearPhotoId() {
      _builder.clearPhotoId()
    }
  }
}
public inline fun app.pochical.v1.SetProfileRequest.copy(block: `app.pochical.v1`.SetProfileRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.SetProfileRequest =
  `app.pochical.v1`.SetProfileRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

