// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/user.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializetakeAccountResponse")
public inline fun takeAccountResponse(block: app.pochical.v1.TakeAccountResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.TakeAccountResponse =
  app.pochical.v1.TakeAccountResponseKt.Dsl._create(app.pochical.v1.TakeAccountResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.TakeAccountResponse`
 */
public object TakeAccountResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.TakeAccountResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.TakeAccountResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.TakeAccountResponse = _builder.build()
  }
}
public inline fun app.pochical.v1.TakeAccountResponse.copy(block: `app.pochical.v1`.TakeAccountResponseKt.Dsl.() -> kotlin.Unit): app.pochical.v1.TakeAccountResponse =
  `app.pochical.v1`.TakeAccountResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

