// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/user.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package app.pochical.v1;

@kotlin.jvm.JvmName("-initializetakeAccountRequest")
public inline fun takeAccountRequest(block: app.pochical.v1.TakeAccountRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.TakeAccountRequest =
  app.pochical.v1.TakeAccountRequestKt.Dsl._create(app.pochical.v1.TakeAccountRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.TakeAccountRequest`
 */
public object TakeAccountRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: app.pochical.v1.TakeAccountRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: app.pochical.v1.TakeAccountRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): app.pochical.v1.TakeAccountRequest = _builder.build()

    /**
     * `string apple_id_token = 1 [json_name = "appleIdToken"];`
     */
    public var appleIdToken: kotlin.String
      @kotlin.jvm.JvmName("getAppleIdToken")
        get() = _builder.appleIdToken
      @kotlin.jvm.JvmName("setAppleIdToken")
        set(value) {
        _builder.appleIdToken = value
      }
    /**
     * `string apple_id_token = 1 [json_name = "appleIdToken"];`
     */
    public fun clearAppleIdToken() {
      _builder.clearAppleIdToken()
    }

    /**
     * `string nonce = 2 [json_name = "nonce"];`
     */
    public var nonce: kotlin.String
      @kotlin.jvm.JvmName("getNonce")
        get() = _builder.nonce
      @kotlin.jvm.JvmName("setNonce")
        set(value) {
        _builder.nonce = value
      }
    /**
     * `string nonce = 2 [json_name = "nonce"];`
     */
    public fun clearNonce() {
      _builder.clearNonce()
    }
  }
}
public inline fun app.pochical.v1.TakeAccountRequest.copy(block: `app.pochical.v1`.TakeAccountRequestKt.Dsl.() -> kotlin.Unit): app.pochical.v1.TakeAccountRequest =
  `app.pochical.v1`.TakeAccountRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

