// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: pochical/v1/user.proto
//
package app.pochical.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  The signed-in user. Every call here needs the session token from
 *  better-auth (/api/auth) as `Authorization: Bearer <token>`; without a
 *  valid one it fails with UNAUTHENTICATED.
 */
public interface UserServiceClientInterface {
  /**
   *  Who the token belongs to, for the apps to check a stored session.
   */
  public suspend fun getMe(request: GetMeRequest, headers: Headers = emptyMap()): ResponseMessage<GetMeResponse>

  /**
   *  Blocks someone in every group the two share, or unblocks them
   *  (spec/chat.md, Reporting and blocking); their devices hear of it as a
   *  Block change. Blocking oneself is INVALID_ARGUMENT.
   */
  public suspend fun setBlocked(request: SetBlockedRequest, headers: Headers = emptyMap()): ResponseMessage<SetBlockedResponse>
}
