// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: pochical/v1/user.proto
//
package app.pochical.v1

import com.connectrpc.Headers
import com.connectrpc.Idempotency
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

/**
 *  The signed-in user. Every call here needs the session token from
 *  better-auth (/api/auth) as `Authorization: Bearer <token>`; without a
 *  valid one it fails with UNAUTHENTICATED.
 */
public class UserServiceClient(
  private val client: ProtocolClientInterface,
) : UserServiceClientInterface {
  /**
   *  Deletes the user's account and everything of it (spec/sync-protocol.md,
   *  Deleting an account): their own values, their place in each group with
   *  every line they wrote taken back, their chat with Pochical's people,
   *  and their sign-ins. A user linked to Sign in with Apple sends a fresh
   *  authorization code, with which the server revokes the app's Apple
   *  tokens as Apple asks; FAILED_PRECONDITION without one Apple takes.
   */
  override suspend fun deleteAccount(request: DeleteAccountRequest, headers: Headers): ResponseMessage<DeleteAccountResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "pochical.v1.UserService/DeleteAccount",
      app.pochical.v1.DeleteAccountRequest::class,
      app.pochical.v1.DeleteAccountResponse::class,
      StreamType.UNARY,
      idempotency = Idempotency.IDEMPOTENT,
    ),
  )


  /**
   *  Who the token belongs to, for the apps to check a stored session.
   */
  override suspend fun getMe(request: GetMeRequest, headers: Headers): ResponseMessage<GetMeResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "pochical.v1.UserService/GetMe",
      app.pochical.v1.GetMeRequest::class,
      app.pochical.v1.GetMeResponse::class,
      StreamType.UNARY,
      idempotency = Idempotency.NO_SIDE_EFFECTS,
    ),
  )


  /**
   *  Blocks someone in every group the two share, or unblocks them
   *  (spec/chat.md, Reporting and blocking); their devices hear of it as a
   *  Block change. Blocking oneself is INVALID_ARGUMENT.
   */
  override suspend fun setBlocked(request: SetBlockedRequest, headers: Headers): ResponseMessage<SetBlockedResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "pochical.v1.UserService/SetBlocked",
      app.pochical.v1.SetBlockedRequest::class,
      app.pochical.v1.SetBlockedResponse::class,
      StreamType.UNARY,
      idempotency = Idempotency.IDEMPOTENT,
    ),
  )


  /**
   *  Keeps a device's push token for the user's notifications (spec/chat.md,
   *  Notifications); sent each launch, as iOS may change it.
   */
  override suspend fun registerPushToken(request: RegisterPushTokenRequest, headers: Headers): ResponseMessage<RegisterPushTokenResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "pochical.v1.UserService/RegisterPushToken",
      app.pochical.v1.RegisterPushTokenRequest::class,
      app.pochical.v1.RegisterPushTokenResponse::class,
      StreamType.UNARY,
      idempotency = Idempotency.IDEMPOTENT,
    ),
  )


  /**
   *  Turns a chat's notifications off or on again (spec/chat.md,
   *  Notifications); the user's devices hear of it as a ChatMute change.
   *  NOT_FOUND for a group the user is not in or a chat not theirs.
   */
  override suspend fun setChatMuted(request: SetChatMutedRequest, headers: Headers): ResponseMessage<SetChatMutedResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "pochical.v1.UserService/SetChatMuted",
      app.pochical.v1.SetChatMutedRequest::class,
      app.pochical.v1.SetChatMutedResponse::class,
      StreamType.UNARY,
      idempotency = Idempotency.IDEMPOTENT,
    ),
  )


  /**
   *  Sets メンションはいつも通知 for the account; the devices hear of it as a
   *  ChatNotifications change.
   */
  override suspend fun setChatNotifications(request: SetChatNotificationsRequest, headers: Headers): ResponseMessage<SetChatNotificationsResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "pochical.v1.UserService/SetChatNotifications",
      app.pochical.v1.SetChatNotificationsRequest::class,
      app.pochical.v1.SetChatNotificationsResponse::class,
      StreamType.UNARY,
      idempotency = Idempotency.IDEMPOTENT,
    ),
  )

}
