// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package tech.chiji.pochical.v1;

@kotlin.jvm.JvmName("-initializechange")
public inline fun change(block: tech.chiji.pochical.v1.ChangeKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.Change =
  tech.chiji.pochical.v1.ChangeKt.Dsl._create(tech.chiji.pochical.v1.Change.newBuilder()).apply { block() }._build()
/**
 * ```
 * A value as the DO now holds it, at the cursor it got when it last
 * changed.
 * ```
 *
 * Protobuf type `pochical.v1.Change`
 */
public object ChangeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: tech.chiji.pochical.v1.Change.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: tech.chiji.pochical.v1.Change.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): tech.chiji.pochical.v1.Change = _builder.build()

    /**
     * `uint64 cursor = 1 [json_name = "cursor"];`
     */
    public var cursor: kotlin.Long
      @kotlin.jvm.JvmName("getCursor")
        get() = _builder.cursor
      @kotlin.jvm.JvmName("setCursor")
        set(value) {
        _builder.cursor = value
      }
    /**
     * `uint64 cursor = 1 [json_name = "cursor"];`
     */
    public fun clearCursor() {
      _builder.clearCursor()
    }

    /**
     * `.pochical.v1.DayValue day = 2 [json_name = "day"];`
     */
    public var day: tech.chiji.pochical.v1.DayValue
      @kotlin.jvm.JvmName("getDay")
        get() = _builder.day
      @kotlin.jvm.JvmName("setDay")
        set(value) {
        _builder.day = value
      }
    /**
     * `.pochical.v1.DayValue day = 2 [json_name = "day"];`
     */
    public fun clearDay() {
      _builder.clearDay()
    }
    /**
     * `.pochical.v1.DayValue day = 2 [json_name = "day"];`
     * @return Whether the day field is set.
     */
    public fun hasDay(): kotlin.Boolean {
      return _builder.hasDay()
    }
    public val kindCase: tech.chiji.pochical.v1.Change.KindCase
    @kotlin.jvm.JvmName("getKindCase")
      get() = _builder.kindCase

    public fun clearKind() {
      _builder.clearKind()
    }
  }
}
public inline fun tech.chiji.pochical.v1.Change.copy(block: `tech.chiji.pochical.v1`.ChangeKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.Change =
  `tech.chiji.pochical.v1`.ChangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val tech.chiji.pochical.v1.ChangeOrBuilder.dayOrNull: tech.chiji.pochical.v1.DayValue?
  get() = if (hasDay()) getDay() else null

