// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package tech.chiji.pochical.v1;

@kotlin.jvm.JvmName("-initializeclientFrame")
public inline fun clientFrame(block: tech.chiji.pochical.v1.ClientFrameKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.ClientFrame =
  tech.chiji.pochical.v1.ClientFrameKt.Dsl._create(tech.chiji.pochical.v1.ClientFrame.newBuilder()).apply { block() }._build()
/**
 * ```
 * Every binary WebSocket message from a client is one ClientFrame.
 * ```
 *
 * Protobuf type `pochical.v1.ClientFrame`
 */
public object ClientFrameKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: tech.chiji.pochical.v1.ClientFrame.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: tech.chiji.pochical.v1.ClientFrame.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): tech.chiji.pochical.v1.ClientFrame = _builder.build()

    /**
     * `.pochical.v1.Hello hello = 1 [json_name = "hello"];`
     */
    public var hello: tech.chiji.pochical.v1.Hello
      @kotlin.jvm.JvmName("getHello")
        get() = _builder.hello
      @kotlin.jvm.JvmName("setHello")
        set(value) {
        _builder.hello = value
      }
    /**
     * `.pochical.v1.Hello hello = 1 [json_name = "hello"];`
     */
    public fun clearHello() {
      _builder.clearHello()
    }
    /**
     * `.pochical.v1.Hello hello = 1 [json_name = "hello"];`
     * @return Whether the hello field is set.
     */
    public fun hasHello(): kotlin.Boolean {
      return _builder.hasHello()
    }

    /**
     * `.pochical.v1.Ping ping = 2 [json_name = "ping"];`
     */
    public var ping: tech.chiji.pochical.v1.Ping
      @kotlin.jvm.JvmName("getPing")
        get() = _builder.ping
      @kotlin.jvm.JvmName("setPing")
        set(value) {
        _builder.ping = value
      }
    /**
     * `.pochical.v1.Ping ping = 2 [json_name = "ping"];`
     */
    public fun clearPing() {
      _builder.clearPing()
    }
    /**
     * `.pochical.v1.Ping ping = 2 [json_name = "ping"];`
     * @return Whether the ping field is set.
     */
    public fun hasPing(): kotlin.Boolean {
      return _builder.hasPing()
    }
    public val kindCase: tech.chiji.pochical.v1.ClientFrame.KindCase
    @kotlin.jvm.JvmName("getKindCase")
      get() = _builder.kindCase

    public fun clearKind() {
      _builder.clearKind()
    }
  }
}
public inline fun tech.chiji.pochical.v1.ClientFrame.copy(block: `tech.chiji.pochical.v1`.ClientFrameKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.ClientFrame =
  `tech.chiji.pochical.v1`.ClientFrameKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val tech.chiji.pochical.v1.ClientFrameOrBuilder.helloOrNull: tech.chiji.pochical.v1.Hello?
  get() = if (hasHello()) getHello() else null

public val tech.chiji.pochical.v1.ClientFrameOrBuilder.pingOrNull: tech.chiji.pochical.v1.Ping?
  get() = if (hasPing()) getPing() else null

