// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/group.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package tech.chiji.pochical.v1;

@kotlin.jvm.JvmName("-initializecreateGroupResponse")
public inline fun createGroupResponse(block: tech.chiji.pochical.v1.CreateGroupResponseKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.CreateGroupResponse =
  tech.chiji.pochical.v1.CreateGroupResponseKt.Dsl._create(tech.chiji.pochical.v1.CreateGroupResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.CreateGroupResponse`
 */
public object CreateGroupResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: tech.chiji.pochical.v1.CreateGroupResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: tech.chiji.pochical.v1.CreateGroupResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): tech.chiji.pochical.v1.CreateGroupResponse = _builder.build()

    /**
     * `string group_id = 1 [json_name = "groupId"];`
     */
    public var groupId: kotlin.String
      @kotlin.jvm.JvmName("getGroupId")
        get() = _builder.groupId
      @kotlin.jvm.JvmName("setGroupId")
        set(value) {
        _builder.groupId = value
      }
    /**
     * `string group_id = 1 [json_name = "groupId"];`
     */
    public fun clearGroupId() {
      _builder.clearGroupId()
    }

    /**
     * `string invite_code = 2 [json_name = "inviteCode"];`
     */
    public var inviteCode: kotlin.String
      @kotlin.jvm.JvmName("getInviteCode")
        get() = _builder.inviteCode
      @kotlin.jvm.JvmName("setInviteCode")
        set(value) {
        _builder.inviteCode = value
      }
    /**
     * `string invite_code = 2 [json_name = "inviteCode"];`
     */
    public fun clearInviteCode() {
      _builder.clearInviteCode()
    }
  }
}
public inline fun tech.chiji.pochical.v1.CreateGroupResponse.copy(block: `tech.chiji.pochical.v1`.CreateGroupResponseKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.CreateGroupResponse =
  `tech.chiji.pochical.v1`.CreateGroupResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

