// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/invite.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package tech.chiji.pochical.v1;

@kotlin.jvm.JvmName("-initializegetInvitePreviewRequest")
public inline fun getInvitePreviewRequest(block: tech.chiji.pochical.v1.GetInvitePreviewRequestKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.GetInvitePreviewRequest =
  tech.chiji.pochical.v1.GetInvitePreviewRequestKt.Dsl._create(tech.chiji.pochical.v1.GetInvitePreviewRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.GetInvitePreviewRequest`
 */
public object GetInvitePreviewRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: tech.chiji.pochical.v1.GetInvitePreviewRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: tech.chiji.pochical.v1.GetInvitePreviewRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): tech.chiji.pochical.v1.GetInvitePreviewRequest = _builder.build()

    /**
     * ```
     * inviteRules.codeLength characters from inviteRules.codeAlphabet
     * (design/src/invite.ts).
     * ```
     *
     * `string invite_code = 1 [json_name = "inviteCode"];`
     */
    public var inviteCode: kotlin.String
      @kotlin.jvm.JvmName("getInviteCode")
        get() = _builder.inviteCode
      @kotlin.jvm.JvmName("setInviteCode")
        set(value) {
        _builder.inviteCode = value
      }
    /**
     * ```
     * inviteRules.codeLength characters from inviteRules.codeAlphabet
     * (design/src/invite.ts).
     * ```
     *
     * `string invite_code = 1 [json_name = "inviteCode"];`
     */
    public fun clearInviteCode() {
      _builder.clearInviteCode()
    }
  }
}
public inline fun tech.chiji.pochical.v1.GetInvitePreviewRequest.copy(block: `tech.chiji.pochical.v1`.GetInvitePreviewRequestKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.GetInvitePreviewRequest =
  `tech.chiji.pochical.v1`.GetInvitePreviewRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

