// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package tech.chiji.pochical.v1;

@kotlin.jvm.JvmName("-initializehello")
public inline fun hello(block: tech.chiji.pochical.v1.HelloKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.Hello =
  tech.chiji.pochical.v1.HelloKt.Dsl._create(tech.chiji.pochical.v1.Hello.newBuilder()).apply { block() }._build()
/**
 * ```
 * First frame a client sends after the socket opens.
 * ```
 *
 * Protobuf type `pochical.v1.Hello`
 */
public object HelloKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: tech.chiji.pochical.v1.Hello.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: tech.chiji.pochical.v1.Hello.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): tech.chiji.pochical.v1.Hello = _builder.build()

    /**
     * `uint32 protocol_version = 1 [json_name = "protocolVersion"];`
     */
    public var protocolVersion: kotlin.Int
      @kotlin.jvm.JvmName("getProtocolVersion")
        get() = _builder.protocolVersion
      @kotlin.jvm.JvmName("setProtocolVersion")
        set(value) {
        _builder.protocolVersion = value
      }
    /**
     * `uint32 protocol_version = 1 [json_name = "protocolVersion"];`
     */
    public fun clearProtocolVersion() {
      _builder.clearProtocolVersion()
    }

    /**
     * ```
     * Last server cursor the client has applied; 0 for a fresh install.
     * ```
     *
     * `uint64 cursor = 2 [json_name = "cursor"];`
     */
    public var cursor: kotlin.Long
      @kotlin.jvm.JvmName("getCursor")
        get() = _builder.cursor
      @kotlin.jvm.JvmName("setCursor")
        set(value) {
        _builder.cursor = value
      }
    /**
     * ```
     * Last server cursor the client has applied; 0 for a fresh install.
     * ```
     *
     * `uint64 cursor = 2 [json_name = "cursor"];`
     */
    public fun clearCursor() {
      _builder.clearCursor()
    }
  }
}
public inline fun tech.chiji.pochical.v1.Hello.copy(block: `tech.chiji.pochical.v1`.HelloKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.Hello =
  `tech.chiji.pochical.v1`.HelloKt.Dsl._create(this.toBuilder()).apply { block() }._build()

