// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package tech.chiji.pochical.v1;

@kotlin.jvm.JvmName("-initializepatternEdits")
public inline fun patternEdits(block: tech.chiji.pochical.v1.PatternEditsKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.PatternEdits =
  tech.chiji.pochical.v1.PatternEditsKt.Dsl._create(tech.chiji.pochical.v1.PatternEdits.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `pochical.v1.PatternEdits`
 */
public object PatternEditsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: tech.chiji.pochical.v1.PatternEdits.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: tech.chiji.pochical.v1.PatternEdits.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): tech.chiji.pochical.v1.PatternEdits = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EditsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .pochical.v1.PatternEdit edits = 1 [json_name = "edits"];`
     */
     public val edits: com.google.protobuf.kotlin.DslList<tech.chiji.pochical.v1.PatternEdit, EditsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.editsList
      )
    /**
     * `repeated .pochical.v1.PatternEdit edits = 1 [json_name = "edits"];`
     * @param value The edits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addEdits")
    public fun com.google.protobuf.kotlin.DslList<tech.chiji.pochical.v1.PatternEdit, EditsProxy>.add(value: tech.chiji.pochical.v1.PatternEdit) {
      _builder.addEdits(value)
    }
    /**
     * `repeated .pochical.v1.PatternEdit edits = 1 [json_name = "edits"];`
     * @param value The edits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignEdits")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<tech.chiji.pochical.v1.PatternEdit, EditsProxy>.plusAssign(value: tech.chiji.pochical.v1.PatternEdit) {
      add(value)
    }
    /**
     * `repeated .pochical.v1.PatternEdit edits = 1 [json_name = "edits"];`
     * @param values The edits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllEdits")
    public fun com.google.protobuf.kotlin.DslList<tech.chiji.pochical.v1.PatternEdit, EditsProxy>.addAll(values: kotlin.collections.Iterable<tech.chiji.pochical.v1.PatternEdit>) {
      _builder.addAllEdits(values)
    }
    /**
     * `repeated .pochical.v1.PatternEdit edits = 1 [json_name = "edits"];`
     * @param values The edits to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllEdits")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<tech.chiji.pochical.v1.PatternEdit, EditsProxy>.plusAssign(values: kotlin.collections.Iterable<tech.chiji.pochical.v1.PatternEdit>) {
      addAll(values)
    }
    /**
     * `repeated .pochical.v1.PatternEdit edits = 1 [json_name = "edits"];`
     * @param index The index to set the value at.
     * @param value The edits to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setEdits")
    public operator fun com.google.protobuf.kotlin.DslList<tech.chiji.pochical.v1.PatternEdit, EditsProxy>.set(index: kotlin.Int, value: tech.chiji.pochical.v1.PatternEdit) {
      _builder.setEdits(index, value)
    }
    /**
     * `repeated .pochical.v1.PatternEdit edits = 1 [json_name = "edits"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearEdits")
    public fun com.google.protobuf.kotlin.DslList<tech.chiji.pochical.v1.PatternEdit, EditsProxy>.clear() {
      _builder.clearEdits()
    }
  }
}
public inline fun tech.chiji.pochical.v1.PatternEdits.copy(block: `tech.chiji.pochical.v1`.PatternEditsKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.PatternEdits =
  `tech.chiji.pochical.v1`.PatternEditsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

