// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package tech.chiji.pochical.v1;

@kotlin.jvm.JvmName("-initializepatternValue")
public inline fun patternValue(block: tech.chiji.pochical.v1.PatternValueKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.PatternValue =
  tech.chiji.pochical.v1.PatternValueKt.Dsl._create(tech.chiji.pochical.v1.PatternValue.newBuilder()).apply { block() }._build()
/**
 * ```
 * One of the owner's patterns as a device set it, whole: each is one
 * last-writer-wins value.
 * ```
 *
 * Protobuf type `pochical.v1.PatternValue`
 */
public object PatternValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: tech.chiji.pochical.v1.PatternValue.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: tech.chiji.pochical.v1.PatternValue.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): tech.chiji.pochical.v1.PatternValue = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * Unset: the pattern was deleted.
     * ```
     *
     * `optional .pochical.v1.Pattern pattern = 2 [json_name = "pattern"];`
     */
    public var pattern: tech.chiji.pochical.v1.Pattern
      @kotlin.jvm.JvmName("getPattern")
        get() = _builder.pattern
      @kotlin.jvm.JvmName("setPattern")
        set(value) {
        _builder.pattern = value
      }
    /**
     * ```
     * Unset: the pattern was deleted.
     * ```
     *
     * `optional .pochical.v1.Pattern pattern = 2 [json_name = "pattern"];`
     */
    public fun clearPattern() {
      _builder.clearPattern()
    }
    /**
     * ```
     * Unset: the pattern was deleted.
     * ```
     *
     * `optional .pochical.v1.Pattern pattern = 2 [json_name = "pattern"];`
     * @return Whether the pattern field is set.
     */
    public fun hasPattern(): kotlin.Boolean {
      return _builder.hasPattern()
    }

    public val PatternValueKt.Dsl.patternOrNull: tech.chiji.pochical.v1.Pattern?
      get() = _builder.patternOrNull

    /**
     * `.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];`
     */
    public var hlc: tech.chiji.pochical.v1.Hlc
      @kotlin.jvm.JvmName("getHlc")
        get() = _builder.hlc
      @kotlin.jvm.JvmName("setHlc")
        set(value) {
        _builder.hlc = value
      }
    /**
     * `.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];`
     */
    public fun clearHlc() {
      _builder.clearHlc()
    }
    /**
     * `.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];`
     * @return Whether the hlc field is set.
     */
    public fun hasHlc(): kotlin.Boolean {
      return _builder.hasHlc()
    }

    public val PatternValueKt.Dsl.hlcOrNull: tech.chiji.pochical.v1.Hlc?
      get() = _builder.hlcOrNull
  }
}
public inline fun tech.chiji.pochical.v1.PatternValue.copy(block: `tech.chiji.pochical.v1`.PatternValueKt.Dsl.() -> kotlin.Unit): tech.chiji.pochical.v1.PatternValue =
  `tech.chiji.pochical.v1`.PatternValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val tech.chiji.pochical.v1.PatternValueOrBuilder.patternOrNull: tech.chiji.pochical.v1.Pattern?
  get() = if (hasPattern()) getPattern() else null

public val tech.chiji.pochical.v1.PatternValueOrBuilder.hlcOrNull: tech.chiji.pochical.v1.Hlc?
  get() = if (hasHlc()) getHlc() else null

