// Writes the Phosphor icons that shift marks use, in the two weights they
// are drawn in (duotone when filled, regular when not), as plain path data.
// @phosphor-icons/react ships all six weights in every icon, which would
// put the four unused ones in every page that shows a calendar.
// Run again after adding an icon to markIcons (shift-mark.tsx): bun run icon:marks
import { writeFile } from "node:fs/promises";

import { markIconWeights, readPhosphorPaths } from "./phosphor-paths";

// Phosphor's names for the icons markIcons draws.
export const phosphorNames = [
  "Airplane",
  "Alarm",
  "Ambulance",
  "Baby",
  "BabyCarriage",
  "Backpack",
  "Balloon",
  "Bandaids",
  "Bank",
  "Barbell",
  "Baseball",
  "Basket",
  "Basketball",
  "Bathtub",
  "Bed",
  "BeerStein",
  "Bell",
  "Bicycle",
  "Bird",
  "Boat",
  "BookOpen",
  "Books",
  "Bread",
  "Briefcase",
  "Broom",
  "Buildings",
  "Bus",
  "Cake",
  "Calculator",
  "CalendarCheck",
  "CalendarHeart",
  "Camera",
  "Car",
  "CashRegister",
  "Cat",
  "ChalkboardTeacher",
  "ChartLine",
  "ChefHat",
  "Clock",
  "Cloud",
  "CloudMoon",
  "CloudRain",
  "CloudSun",
  "Code",
  "Coffee",
  "Coins",
  "Confetti",
  "CookingPot",
  "Couch",
  "Desktop",
  "Dog",
  "Envelope",
  "Eyeglasses",
  "Factory",
  "FilmSlate",
  "FireExtinguisher",
  "FireTruck",
  "FirstAidKit",
  "Fish",
  "Flower",
  "Folder",
  "ForkKnife",
  "GameController",
  "GasPump",
  "Gift",
  "GraduationCap",
  "Guitar",
  "Hammer",
  "HandHeart",
  "Handshake",
  "HardHat",
  "Headset",
  "Heart",
  "Heartbeat",
  "Hospital",
  "Hourglass",
  "House",
  "IceCream",
  "IdentificationBadge",
  "Island",
  "Laptop",
  "Leaf",
  "Lightbulb",
  "Lightning",
  "MapPin",
  "Megaphone",
  "MicrophoneStage",
  "Microscope",
  "Moon",
  "MoonStars",
  "Motorcycle",
  "Mountains",
  "MusicNote",
  "Needle",
  "Notebook",
  "Package",
  "PaintBrush",
  "Palette",
  "PawPrint",
  "Pencil",
  "PencilSimple",
  "PersonSimpleRun",
  "PersonSimpleSwim",
  "Phone",
  "Pill",
  "PoliceCar",
  "Popcorn",
  "PottedPlant",
  "PresentationChart",
  "Printer",
  "Rabbit",
  "Rainbow",
  "Scales",
  "Scissors",
  "Shield",
  "ShieldCheck",
  "ShoppingBag",
  "ShoppingCart",
  "Siren",
  "Smiley",
  "Sneaker",
  "Snowflake",
  "SoccerBall",
  "Star",
  "Stethoscope",
  "Storefront",
  "Subway",
  "SuitcaseRolling",
  "Sun",
  "SunHorizon",
  "Sunglasses",
  "Syringe",
  "TShirt",
  "Taxi",
  "TennisBall",
  "Tent",
  "Ticket",
  "Timer",
  "Tooth",
  "Tractor",
  "Train",
  "Translate",
  "Tree",
  "TreePalm",
  "Trophy",
  "Truck",
  "Users",
  "Van",
  "VideoCamera",
  "Warehouse",
  "WashingMachine",
  "Wheelchair",
  "Wine",
  "Wrench",
] as const;

const OUTPUT = new URL("../src/lib/mark-icon-paths.ts", import.meta.url)
  .pathname;

if (import.meta.main) {
  const entries = await Promise.all(
    phosphorNames.map(
      async (name) =>
        `  ${name}: ${JSON.stringify(await readPhosphorPaths(name))},`
    )
  );
  await writeFile(
    OUTPUT,
    [
      "// Written by scripts/mark-icons.ts (bun run icon:marks); do not edit.",
      `// Phosphor's paths for the shift marks' icons, ${markIconWeights.join(" and ")}, on a 256 grid.`,
      "type MarkIconPath = { d: string; opacity?: number };",
      `export type MarkIconName = ${phosphorNames.map((name) => `"${name}"`).join(" | ")};`,
      "",
      `export const markIconPaths: Record<MarkIconName, Record<"${markIconWeights.join('" | "')}", MarkIconPath[]>> = {`,
      ...entries,
      "};",
      "",
    ].join("\n")
  );
}
