// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

/**
 * Protobuf type {@code pochical.v1.Acked}
 */
@com.google.protobuf.Generated
public  final class Acked extends
    com.google.protobuf.GeneratedMessageLite<
        Acked, Acked.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.Acked)
    AckedOrBuilder {
  private Acked() {
    opIds_ = emptyProtobufList();
  }
  public static final int OP_IDS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> opIds_;
  /**
   * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
   * @return A list containing the opIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getOpIdsList() {
    return opIds_;
  }
  /**
   * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
   * @return The count of opIds.
   */
  @java.lang.Override
  public int getOpIdsCount() {
    return opIds_.size();
  }
  /**
   * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
   * @param index The index of the element to return.
   * @return The opIds at the given index.
   */
  @java.lang.Override
  public java.lang.String getOpIds(int index) {
    return opIds_.get(index);
  }
  /**
   * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the opIds at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOpIdsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        opIds_.get(index));
  }
  private void ensureOpIdsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        opIds_;  if (!tmp.isModifiable()) {
      opIds_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
   * @param index The index to set the value at.
   * @param value The opIds to set.
   */
  private void setOpIds(
      int index, java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureOpIdsIsMutable();
    opIds_.set(index, value);
  }
  /**
   * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
   * @param value The opIds to add.
   */
  private void addOpIds(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureOpIdsIsMutable();
    opIds_.add(value);
  }
  /**
   * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
   * @param values The opIds to add.
   */
  private void addAllOpIds(
      java.lang.Iterable<java.lang.String> values) {
    ensureOpIdsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, opIds_);
  }
  /**
   * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
   */
  private void clearOpIds() {
    opIds_ = emptyProtobufList();
  }
  /**
   * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
   * @param value The bytes of the opIds to add.
   */
  private void addOpIdsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureOpIdsIsMutable();
    opIds_.add(value.toStringUtf8());
  }

  public static app.pochical.v1.Acked parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.Acked parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.Acked parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.Acked parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.Acked parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.Acked parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.Acked parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.Acked parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static app.pochical.v1.Acked parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static app.pochical.v1.Acked parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static app.pochical.v1.Acked parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.Acked parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(app.pochical.v1.Acked prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code pochical.v1.Acked}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        app.pochical.v1.Acked, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.Acked)
      app.pochical.v1.AckedOrBuilder {
    // Construct using app.pochical.v1.Acked.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
     * @return A list containing the opIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getOpIdsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOpIdsList());
    }
    /**
     * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
     * @return The count of opIds.
     */
    @java.lang.Override
    public int getOpIdsCount() {
      return instance.getOpIdsCount();
    }
    /**
     * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
     * @param index The index of the element to return.
     * @return The opIds at the given index.
     */
    @java.lang.Override
    public java.lang.String getOpIds(int index) {
      return instance.getOpIds(index);
    }
    /**
     * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the opIds at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOpIdsBytes(int index) {
      return instance.getOpIdsBytes(index);
    }
    /**
     * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
     * @param index The index to set the value at.
     * @param value The opIds to set.
     * @return This builder for chaining.
     */
    public Builder setOpIds(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setOpIds(index, value);
      return this;
    }
    /**
     * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
     * @param value The opIds to add.
     * @return This builder for chaining.
     */
    public Builder addOpIds(
        java.lang.String value) {
      copyOnWrite();
      instance.addOpIds(value);
      return this;
    }
    /**
     * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
     * @param values The opIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllOpIds(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllOpIds(values);
      return this;
    }
    /**
     * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOpIds() {
      copyOnWrite();
      instance.clearOpIds();
      return this;
    }
    /**
     * <code>repeated string op_ids = 1 [json_name = "opIds"];</code>
     * @param value The bytes of the opIds to add.
     * @return This builder for chaining.
     */
    public Builder addOpIdsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addOpIdsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.Acked)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new app.pochical.v1.Acked();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "opIds_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<app.pochical.v1.Acked> parser = PARSER;
        if (parser == null) {
          synchronized (app.pochical.v1.Acked.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<app.pochical.v1.Acked>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.Acked)
  private static final app.pochical.v1.Acked DEFAULT_INSTANCE;
  static {
    Acked defaultInstance = new Acked();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Acked.class, defaultInstance);
  }

  public static app.pochical.v1.Acked getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Acked> PARSER;

  public static com.google.protobuf.Parser<Acked> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

