// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface ChangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.Change)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint64 cursor = 1 [json_name = "cursor"];</code>
   * @return The cursor.
   */
  long getCursor();

  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   * @return Whether the day field is set.
   */
  boolean hasDay();
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   * @return The day.
   */
  app.pochical.v1.DayValue getDay();

  /**
   * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
   * @return Whether the pattern field is set.
   */
  boolean hasPattern();
  /**
   * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
   * @return The pattern.
   */
  app.pochical.v1.PatternValue getPattern();

  /**
   * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
   * @return Whether the patternOrder field is set.
   */
  boolean hasPatternOrder();
  /**
   * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
   * @return The patternOrder.
   */
  app.pochical.v1.PatternOrder getPatternOrder();

  /**
   * <pre>
   * On a Group DO socket: a member's shared days and patterns, as their
   * User DO pushes them (spec/sync-protocol.md, Group projection).
   * </pre>
   *
   * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
   * @return Whether the memberDay field is set.
   */
  boolean hasMemberDay();
  /**
   * <pre>
   * On a Group DO socket: a member's shared days and patterns, as their
   * User DO pushes them (spec/sync-protocol.md, Group projection).
   * </pre>
   *
   * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
   * @return The memberDay.
   */
  app.pochical.v1.MemberDay getMemberDay();

  /**
   * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
   * @return Whether the memberPattern field is set.
   */
  boolean hasMemberPattern();
  /**
   * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
   * @return The memberPattern.
   */
  app.pochical.v1.MemberPattern getMemberPattern();

  /**
   * <code>.pochical.v1.RepeatOrders repeat_orders = 7 [json_name = "repeatOrders"];</code>
   * @return Whether the repeatOrders field is set.
   */
  boolean hasRepeatOrders();
  /**
   * <code>.pochical.v1.RepeatOrders repeat_orders = 7 [json_name = "repeatOrders"];</code>
   * @return The repeatOrders.
   */
  app.pochical.v1.RepeatOrders getRepeatOrders();

  /**
   * <code>.pochical.v1.CoworkerValue coworker = 8 [json_name = "coworker"];</code>
   * @return Whether the coworker field is set.
   */
  boolean hasCoworker();
  /**
   * <code>.pochical.v1.CoworkerValue coworker = 8 [json_name = "coworker"];</code>
   * @return The coworker.
   */
  app.pochical.v1.CoworkerValue getCoworker();

  /**
   * <code>.pochical.v1.CoworkerOrder coworker_order = 9 [json_name = "coworkerOrder"];</code>
   * @return Whether the coworkerOrder field is set.
   */
  boolean hasCoworkerOrder();
  /**
   * <code>.pochical.v1.CoworkerOrder coworker_order = 9 [json_name = "coworkerOrder"];</code>
   * @return The coworkerOrder.
   */
  app.pochical.v1.CoworkerOrder getCoworkerOrder();

  /**
   * <pre>
   * On a Group DO socket: a member's repeating orders, so the group works
   * their days out as their own devices do.
   * </pre>
   *
   * <code>.pochical.v1.MemberRepeatOrders member_repeat_orders = 10 [json_name = "memberRepeatOrders"];</code>
   * @return Whether the memberRepeatOrders field is set.
   */
  boolean hasMemberRepeatOrders();
  /**
   * <pre>
   * On a Group DO socket: a member's repeating orders, so the group works
   * their days out as their own devices do.
   * </pre>
   *
   * <code>.pochical.v1.MemberRepeatOrders member_repeat_orders = 10 [json_name = "memberRepeatOrders"];</code>
   * @return The memberRepeatOrders.
   */
  app.pochical.v1.MemberRepeatOrders getMemberRepeatOrders();

  public app.pochical.v1.Change.KindCase getKindCase();
}
