// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

/**
 * Protobuf type {@code pochical.v1.ChatPageRequest}
 */
@com.google.protobuf.Generated
public  final class ChatPageRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ChatPageRequest, ChatPageRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.ChatPageRequest)
    ChatPageRequestOrBuilder {
  private ChatPageRequest() {
    threadId_ = "";
  }
  public static final int THREAD_ID_FIELD_NUMBER = 1;
  private java.lang.String threadId_;
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @return The threadId.
   */
  @java.lang.Override
  public java.lang.String getThreadId() {
    return threadId_;
  }
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @return The bytes for threadId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreadIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(threadId_);
  }
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @param value The threadId to set.
   */
  private void setThreadId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    threadId_ = value;
  }
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   */
  private void clearThreadId() {

    threadId_ = getDefaultInstance().getThreadId();
  }
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @param value The bytes for threadId to set.
   */
  private void setThreadIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    threadId_ = value.toStringUtf8();

  }

  public static final int BEFORE_SEQ_FIELD_NUMBER = 2;
  private long beforeSeq_;
  /**
   * <pre>
   * The lines before this one; 0 for the latest.
   * </pre>
   *
   * <code>uint64 before_seq = 2 [json_name = "beforeSeq"];</code>
   * @return The beforeSeq.
   */
  @java.lang.Override
  public long getBeforeSeq() {
    return beforeSeq_;
  }
  /**
   * <pre>
   * The lines before this one; 0 for the latest.
   * </pre>
   *
   * <code>uint64 before_seq = 2 [json_name = "beforeSeq"];</code>
   * @param value The beforeSeq to set.
   */
  private void setBeforeSeq(long value) {
    
    beforeSeq_ = value;
  }
  /**
   * <pre>
   * The lines before this one; 0 for the latest.
   * </pre>
   *
   * <code>uint64 before_seq = 2 [json_name = "beforeSeq"];</code>
   */
  private void clearBeforeSeq() {

    beforeSeq_ = 0L;
  }

  public static app.pochical.v1.ChatPageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.ChatPageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.ChatPageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.ChatPageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.ChatPageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.ChatPageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.ChatPageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.ChatPageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static app.pochical.v1.ChatPageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static app.pochical.v1.ChatPageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static app.pochical.v1.ChatPageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.ChatPageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(app.pochical.v1.ChatPageRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code pochical.v1.ChatPageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        app.pochical.v1.ChatPageRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.ChatPageRequest)
      app.pochical.v1.ChatPageRequestOrBuilder {
    // Construct using app.pochical.v1.ChatPageRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @return The threadId.
     */
    @java.lang.Override
    public java.lang.String getThreadId() {
      return instance.getThreadId();
    }
    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @return The bytes for threadId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getThreadIdBytes() {
      return instance.getThreadIdBytes();
    }
    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @param value The threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadId(
        java.lang.String value) {
      copyOnWrite();
      instance.setThreadId(value);
      return this;
    }
    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadId() {
      copyOnWrite();
      instance.clearThreadId();
      return this;
    }
    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @param value The bytes for threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setThreadIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * The lines before this one; 0 for the latest.
     * </pre>
     *
     * <code>uint64 before_seq = 2 [json_name = "beforeSeq"];</code>
     * @return The beforeSeq.
     */
    @java.lang.Override
    public long getBeforeSeq() {
      return instance.getBeforeSeq();
    }
    /**
     * <pre>
     * The lines before this one; 0 for the latest.
     * </pre>
     *
     * <code>uint64 before_seq = 2 [json_name = "beforeSeq"];</code>
     * @param value The beforeSeq to set.
     * @return This builder for chaining.
     */
    public Builder setBeforeSeq(long value) {
      copyOnWrite();
      instance.setBeforeSeq(value);
      return this;
    }
    /**
     * <pre>
     * The lines before this one; 0 for the latest.
     * </pre>
     *
     * <code>uint64 before_seq = 2 [json_name = "beforeSeq"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBeforeSeq() {
      copyOnWrite();
      instance.clearBeforeSeq();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.ChatPageRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new app.pochical.v1.ChatPageRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "threadId_",
            "beforeSeq_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0003" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<app.pochical.v1.ChatPageRequest> parser = PARSER;
        if (parser == null) {
          synchronized (app.pochical.v1.ChatPageRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<app.pochical.v1.ChatPageRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.ChatPageRequest)
  private static final app.pochical.v1.ChatPageRequest DEFAULT_INSTANCE;
  static {
    ChatPageRequest defaultInstance = new ChatPageRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ChatPageRequest.class, defaultInstance);
  }

  public static app.pochical.v1.ChatPageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ChatPageRequest> PARSER;

  public static com.google.protobuf.Parser<ChatPageRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

