// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface ChatLineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.ChatLine)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @return The threadId.
   */
  java.lang.String getThreadId();
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @return The bytes for threadId.
   */
  com.google.protobuf.ByteString
      getThreadIdBytes();

  /**
   * <pre>
   * Its place in the chat, from 1, given by the group as it takes it.
   * </pre>
   *
   * <code>uint64 seq = 2 [json_name = "seq"];</code>
   * @return The seq.
   */
  long getSeq();

  /**
   * <pre>
   * Who wrote it; it stays theirs after they leave.
   * </pre>
   *
   * <code>string author_id = 3 [json_name = "authorId"];</code>
   * @return The authorId.
   */
  java.lang.String getAuthorId();
  /**
   * <pre>
   * Who wrote it; it stays theirs after they leave.
   * </pre>
   *
   * <code>string author_id = 3 [json_name = "authorId"];</code>
   * @return The bytes for authorId.
   */
  com.google.protobuf.ByteString
      getAuthorIdBytes();

  /**
   * <pre>
   * chatMessage characters at most (design/src/limits.ts); empty for a
   * line of shared days, and once unsent.
   * </pre>
   *
   * <code>string text = 4 [json_name = "text"];</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * chatMessage characters at most (design/src/limits.ts); empty for a
   * line of shared days, and once unsent.
   * </pre>
   *
   * <code>string text = 4 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * When the group took it, in ms since the epoch.
   * </pre>
   *
   * <code>int64 sent_at_ms = 5 [json_name = "sentAtMs"];</code>
   * @return The sentAtMs.
   */
  long getSentAtMs();

  /**
   * <pre>
   * Its words were changed after it was sent (編集済み).
   * </pre>
   *
   * <code>bool edited = 6 [json_name = "edited"];</code>
   * @return The edited.
   */
  boolean getEdited();

  /**
   * <pre>
   * Taken back by its writer (送信取消): its words are gone for everyone.
   * </pre>
   *
   * <code>bool unsent = 7 [json_name = "unsent"];</code>
   * @return The unsent.
   */
  boolean getUnsent();

  /**
   * <pre>
   * The op_id of the edit that sent it, so the sending device puts the
   * group's line in place of the one it showed while it waited.
   * </pre>
   *
   * <code>string op_id = 8 [json_name = "opId"];</code>
   * @return The opId.
   */
  java.lang.String getOpId();
  /**
   * <pre>
   * The op_id of the edit that sent it, so the sending device puts the
   * group's line in place of the one it showed while it waited.
   * </pre>
   *
   * <code>string op_id = 8 [json_name = "opId"];</code>
   * @return The bytes for opId.
   */
  com.google.protobuf.ByteString
      getOpIdBytes();

  /**
   * <pre>
   * Its reactions, each emoji with who chose it in the order they did,
   * the emoji in the order first chosen; none once unsent.
   * </pre>
   *
   * <code>repeated .pochical.v1.ChatReaction reactions = 9 [json_name = "reactions"];</code>
   */
  java.util.List<app.pochical.v1.ChatReaction> 
      getReactionsList();
  /**
   * <pre>
   * Its reactions, each emoji with who chose it in the order they did,
   * the emoji in the order first chosen; none once unsent.
   * </pre>
   *
   * <code>repeated .pochical.v1.ChatReaction reactions = 9 [json_name = "reactions"];</code>
   */
  app.pochical.v1.ChatReaction getReactions(int index);
  /**
   * <pre>
   * Its reactions, each emoji with who chose it in the order they did,
   * the emoji in the order first chosen; none once unsent.
   * </pre>
   *
   * <code>repeated .pochical.v1.ChatReaction reactions = 9 [json_name = "reactions"];</code>
   */
  int getReactionsCount();

  /**
   * <pre>
   * Pinned for everyone in the chat: the group's cursor when it was last
   * pinned, so the latest pin is the greatest; 0 when not pinned.
   * </pre>
   *
   * <code>uint64 pinned_order = 10 [json_name = "pinnedOrder"];</code>
   * @return The pinnedOrder.
   */
  long getPinnedOrder();

  /**
   * <pre>
   * The days it shares with everyone's shifts, as YYYY-MM-DD in order; a
   * line of days has no words. None once unsent.
   * </pre>
   *
   * <code>repeated string days = 11 [json_name = "days"];</code>
   * @return A list containing the days.
   */
  java.util.List<java.lang.String>
      getDaysList();
  /**
   * <pre>
   * The days it shares with everyone's shifts, as YYYY-MM-DD in order; a
   * line of days has no words. None once unsent.
   * </pre>
   *
   * <code>repeated string days = 11 [json_name = "days"];</code>
   * @return The count of days.
   */
  int getDaysCount();
  /**
   * <pre>
   * The days it shares with everyone's shifts, as YYYY-MM-DD in order; a
   * line of days has no words. None once unsent.
   * </pre>
   *
   * <code>repeated string days = 11 [json_name = "days"];</code>
   * @param index The index of the element to return.
   * @return The days at the given index.
   */
  java.lang.String getDays(int index);
  /**
   * <pre>
   * The days it shares with everyone's shifts, as YYYY-MM-DD in order; a
   * line of days has no words. None once unsent.
   * </pre>
   *
   * <code>repeated string days = 11 [json_name = "days"];</code>
   * @param index The index of the element to return.
   * @return The days at the given index.
   */
  com.google.protobuf.ByteString
      getDaysBytes(int index);

  /**
   * <pre>
   * Its days are put to the vote (spec/chat.md, Polls), in a group chat.
   * </pre>
   *
   * <code>bool poll = 12 [json_name = "poll"];</code>
   * @return The poll.
   */
  boolean getPoll();

  /**
   * <pre>
   * A poll's votes: each day someone can come, with who can, in the
   * order they said so. None once unsent.
   * </pre>
   *
   * <code>repeated .pochical.v1.ChatVotes votes = 13 [json_name = "votes"];</code>
   */
  java.util.List<app.pochical.v1.ChatVotes> 
      getVotesList();
  /**
   * <pre>
   * A poll's votes: each day someone can come, with who can, in the
   * order they said so. None once unsent.
   * </pre>
   *
   * <code>repeated .pochical.v1.ChatVotes votes = 13 [json_name = "votes"];</code>
   */
  app.pochical.v1.ChatVotes getVotes(int index);
  /**
   * <pre>
   * A poll's votes: each day someone can come, with who can, in the
   * order they said so. None once unsent.
   * </pre>
   *
   * <code>repeated .pochical.v1.ChatVotes votes = 13 [json_name = "votes"];</code>
   */
  int getVotesCount();

  /**
   * <pre>
   * The day a poll was settled on, as YYYY-MM-DD; empty while open.
   * </pre>
   *
   * <code>string decided = 14 [json_name = "decided"];</code>
   * @return The decided.
   */
  java.lang.String getDecided();
  /**
   * <pre>
   * The day a poll was settled on, as YYYY-MM-DD; empty while open.
   * </pre>
   *
   * <code>string decided = 14 [json_name = "decided"];</code>
   * @return The bytes for decided.
   */
  com.google.protobuf.ByteString
      getDecidedBytes();

  /**
   * <pre>
   * A photo sent as the line, with no words; none once unsent.
   * </pre>
   *
   * <code>.pochical.v1.ChatPhoto photo = 15 [json_name = "photo"];</code>
   * @return Whether the photo field is set.
   */
  boolean hasPhoto();
  /**
   * <pre>
   * A photo sent as the line, with no words; none once unsent.
   * </pre>
   *
   * <code>.pochical.v1.ChatPhoto photo = 15 [json_name = "photo"];</code>
   * @return The photo.
   */
  app.pochical.v1.ChatPhoto getPhoto();

  /**
   * <pre>
   * Its first link's page, under its words; none once unsent.
   * </pre>
   *
   * <code>.pochical.v1.LinkPreview preview = 16 [json_name = "preview"];</code>
   * @return Whether the preview field is set.
   */
  boolean hasPreview();
  /**
   * <pre>
   * Its first link's page, under its words; none once unsent.
   * </pre>
   *
   * <code>.pochical.v1.LinkPreview preview = 16 [json_name = "preview"];</code>
   * @return The preview.
   */
  app.pochical.v1.LinkPreview getPreview();

  /**
   * <pre>
   * Sent in a one-to-one chat by someone the reader had blocked: never
   * delivered to them, so it comes without its content and shows nothing.
   * </pre>
   *
   * <code>bool hidden = 17 [json_name = "hidden"];</code>
   * @return The hidden.
   */
  boolean getHidden();

  /**
   * <pre>
   * The line it answers (返信), by its seq in the same chat; 0 for none,
   * and none once unsent.
   * </pre>
   *
   * <code>uint64 reply_to = 18 [json_name = "replyTo"];</code>
   * @return The replyTo.
   */
  long getReplyTo();
}
