// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface ChatNotificationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.ChatNotifications)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * メンションはいつも通知: a line mentioning the user notifies, and
   * counts, in a chat turned off.
   * </pre>
   *
   * <code>bool mentions_when_muted = 1 [json_name = "mentionsWhenMuted"];</code>
   * @return The mentionsWhenMuted.
   */
  boolean getMentionsWhenMuted();
}
