// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

/**
 * <pre>
 * A new line at the end of the chat: words, or days shared with
 * everyone's shifts (spec/chat.md, Long messages and shared days).
 * </pre>
 *
 * Protobuf type {@code pochical.v1.ChatSend}
 */
@com.google.protobuf.Generated
public  final class ChatSend extends
    com.google.protobuf.GeneratedMessageLite<
        ChatSend, ChatSend.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.ChatSend)
    ChatSendOrBuilder {
  private ChatSend() {
    threadId_ = "";
    text_ = "";
    days_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int THREAD_ID_FIELD_NUMBER = 1;
  private java.lang.String threadId_;
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @return The threadId.
   */
  @java.lang.Override
  public java.lang.String getThreadId() {
    return threadId_;
  }
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @return The bytes for threadId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreadIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(threadId_);
  }
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @param value The threadId to set.
   */
  private void setThreadId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    threadId_ = value;
  }
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   */
  private void clearThreadId() {

    threadId_ = getDefaultInstance().getThreadId();
  }
  /**
   * <code>string thread_id = 1 [json_name = "threadId"];</code>
   * @param value The bytes for threadId to set.
   */
  private void setThreadIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    threadId_ = value.toStringUtf8();

  }

  public static final int TEXT_FIELD_NUMBER = 2;
  private java.lang.String text_;
  /**
   * <pre>
   * 1 to chatMessage characters, not blank; empty for days.
   * </pre>
   *
   * <code>string text = 2 [json_name = "text"];</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    return text_;
  }
  /**
   * <pre>
   * 1 to chatMessage characters, not blank; empty for days.
   * </pre>
   *
   * <code>string text = 2 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(text_);
  }
  /**
   * <pre>
   * 1 to chatMessage characters, not blank; empty for days.
   * </pre>
   *
   * <code>string text = 2 [json_name = "text"];</code>
   * @param value The text to set.
   */
  private void setText(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    text_ = value;
  }
  /**
   * <pre>
   * 1 to chatMessage characters, not blank; empty for days.
   * </pre>
   *
   * <code>string text = 2 [json_name = "text"];</code>
   */
  private void clearText() {

    text_ = getDefaultInstance().getText();
  }
  /**
   * <pre>
   * 1 to chatMessage characters, not blank; empty for days.
   * </pre>
   *
   * <code>string text = 2 [json_name = "text"];</code>
   * @param value The bytes for text to set.
   */
  private void setTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    text_ = value.toStringUtf8();

  }

  public static final int DAYS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> days_;
  /**
   * <pre>
   * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
   * each once and in order; none for words.
   * </pre>
   *
   * <code>repeated string days = 3 [json_name = "days"];</code>
   * @return A list containing the days.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getDaysList() {
    return days_;
  }
  /**
   * <pre>
   * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
   * each once and in order; none for words.
   * </pre>
   *
   * <code>repeated string days = 3 [json_name = "days"];</code>
   * @return The count of days.
   */
  @java.lang.Override
  public int getDaysCount() {
    return days_.size();
  }
  /**
   * <pre>
   * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
   * each once and in order; none for words.
   * </pre>
   *
   * <code>repeated string days = 3 [json_name = "days"];</code>
   * @param index The index of the element to return.
   * @return The days at the given index.
   */
  @java.lang.Override
  public java.lang.String getDays(int index) {
    return days_.get(index);
  }
  /**
   * <pre>
   * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
   * each once and in order; none for words.
   * </pre>
   *
   * <code>repeated string days = 3 [json_name = "days"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the days at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDaysBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        days_.get(index));
  }
  private void ensureDaysIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        days_;  if (!tmp.isModifiable()) {
      days_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
   * each once and in order; none for words.
   * </pre>
   *
   * <code>repeated string days = 3 [json_name = "days"];</code>
   * @param index The index to set the value at.
   * @param value The days to set.
   */
  private void setDays(
      int index, java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureDaysIsMutable();
    days_.set(index, value);
  }
  /**
   * <pre>
   * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
   * each once and in order; none for words.
   * </pre>
   *
   * <code>repeated string days = 3 [json_name = "days"];</code>
   * @param value The days to add.
   */
  private void addDays(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureDaysIsMutable();
    days_.add(value);
  }
  /**
   * <pre>
   * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
   * each once and in order; none for words.
   * </pre>
   *
   * <code>repeated string days = 3 [json_name = "days"];</code>
   * @param values The days to add.
   */
  private void addAllDays(
      java.lang.Iterable<java.lang.String> values) {
    ensureDaysIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, days_);
  }
  /**
   * <pre>
   * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
   * each once and in order; none for words.
   * </pre>
   *
   * <code>repeated string days = 3 [json_name = "days"];</code>
   */
  private void clearDays() {
    days_ = emptyProtobufList();
  }
  /**
   * <pre>
   * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
   * each once and in order; none for words.
   * </pre>
   *
   * <code>repeated string days = 3 [json_name = "days"];</code>
   * @param value The bytes of the days to add.
   */
  private void addDaysBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureDaysIsMutable();
    days_.add(value.toStringUtf8());
  }

  public static final int POLL_FIELD_NUMBER = 4;
  private boolean poll_;
  /**
   * <pre>
   * The days put to the vote instead: 2 days at least, in the group chat.
   * </pre>
   *
   * <code>bool poll = 4 [json_name = "poll"];</code>
   * @return The poll.
   */
  @java.lang.Override
  public boolean getPoll() {
    return poll_;
  }
  /**
   * <pre>
   * The days put to the vote instead: 2 days at least, in the group chat.
   * </pre>
   *
   * <code>bool poll = 4 [json_name = "poll"];</code>
   * @param value The poll to set.
   */
  private void setPoll(boolean value) {
    
    poll_ = value;
  }
  /**
   * <pre>
   * The days put to the vote instead: 2 days at least, in the group chat.
   * </pre>
   *
   * <code>bool poll = 4 [json_name = "poll"];</code>
   */
  private void clearPoll() {

    poll_ = false;
  }

  public static final int PHOTO_FIELD_NUMBER = 5;
  private app.pochical.v1.ChatPhoto photo_;
  /**
   * <pre>
   * A photo instead, the sender's own, uploaded first; no words or days.
   * </pre>
   *
   * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
   */
  @java.lang.Override
  public boolean hasPhoto() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * A photo instead, the sender's own, uploaded first; no words or days.
   * </pre>
   *
   * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
   */
  @java.lang.Override
  public app.pochical.v1.ChatPhoto getPhoto() {
    return photo_ == null ? app.pochical.v1.ChatPhoto.getDefaultInstance() : photo_;
  }
  /**
   * <pre>
   * A photo instead, the sender's own, uploaded first; no words or days.
   * </pre>
   *
   * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
   */
  private void setPhoto(app.pochical.v1.ChatPhoto value) {
    java.util.Objects.requireNonNull(value);
    photo_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * A photo instead, the sender's own, uploaded first; no words or days.
   * </pre>
   *
   * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergePhoto(app.pochical.v1.ChatPhoto value) {
    java.util.Objects.requireNonNull(value);
    if (photo_ != null &&
        photo_ != app.pochical.v1.ChatPhoto.getDefaultInstance()) {
      photo_ =
        app.pochical.v1.ChatPhoto.newBuilder(photo_).mergeFrom(value).buildPartial();
    } else {
      photo_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * A photo instead, the sender's own, uploaded first; no words or days.
   * </pre>
   *
   * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
   */
  private void clearPhoto() {
    photo_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static app.pochical.v1.ChatSend parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.ChatSend parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.ChatSend parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.ChatSend parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.ChatSend parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.ChatSend parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.ChatSend parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.ChatSend parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static app.pochical.v1.ChatSend parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static app.pochical.v1.ChatSend parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static app.pochical.v1.ChatSend parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.ChatSend parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(app.pochical.v1.ChatSend prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A new line at the end of the chat: words, or days shared with
   * everyone's shifts (spec/chat.md, Long messages and shared days).
   * </pre>
   *
   * Protobuf type {@code pochical.v1.ChatSend}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        app.pochical.v1.ChatSend, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.ChatSend)
      app.pochical.v1.ChatSendOrBuilder {
    // Construct using app.pochical.v1.ChatSend.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @return The threadId.
     */
    @java.lang.Override
    public java.lang.String getThreadId() {
      return instance.getThreadId();
    }
    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @return The bytes for threadId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getThreadIdBytes() {
      return instance.getThreadIdBytes();
    }
    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @param value The threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadId(
        java.lang.String value) {
      copyOnWrite();
      instance.setThreadId(value);
      return this;
    }
    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadId() {
      copyOnWrite();
      instance.clearThreadId();
      return this;
    }
    /**
     * <code>string thread_id = 1 [json_name = "threadId"];</code>
     * @param value The bytes for threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setThreadIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * 1 to chatMessage characters, not blank; empty for days.
     * </pre>
     *
     * <code>string text = 2 [json_name = "text"];</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      return instance.getText();
    }
    /**
     * <pre>
     * 1 to chatMessage characters, not blank; empty for days.
     * </pre>
     *
     * <code>string text = 2 [json_name = "text"];</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      return instance.getTextBytes();
    }
    /**
     * <pre>
     * 1 to chatMessage characters, not blank; empty for days.
     * </pre>
     *
     * <code>string text = 2 [json_name = "text"];</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <pre>
     * 1 to chatMessage characters, not blank; empty for days.
     * </pre>
     *
     * <code>string text = 2 [json_name = "text"];</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }
    /**
     * <pre>
     * 1 to chatMessage characters, not blank; empty for days.
     * </pre>
     *
     * <code>string text = 2 [json_name = "text"];</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextBytes(value);
      return this;
    }

    /**
     * <pre>
     * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
     * each once and in order; none for words.
     * </pre>
     *
     * <code>repeated string days = 3 [json_name = "days"];</code>
     * @return A list containing the days.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getDaysList() {
      return java.util.Collections.unmodifiableList(
          instance.getDaysList());
    }
    /**
     * <pre>
     * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
     * each once and in order; none for words.
     * </pre>
     *
     * <code>repeated string days = 3 [json_name = "days"];</code>
     * @return The count of days.
     */
    @java.lang.Override
    public int getDaysCount() {
      return instance.getDaysCount();
    }
    /**
     * <pre>
     * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
     * each once and in order; none for words.
     * </pre>
     *
     * <code>repeated string days = 3 [json_name = "days"];</code>
     * @param index The index of the element to return.
     * @return The days at the given index.
     */
    @java.lang.Override
    public java.lang.String getDays(int index) {
      return instance.getDays(index);
    }
    /**
     * <pre>
     * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
     * each once and in order; none for words.
     * </pre>
     *
     * <code>repeated string days = 3 [json_name = "days"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the days at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDaysBytes(int index) {
      return instance.getDaysBytes(index);
    }
    /**
     * <pre>
     * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
     * each once and in order; none for words.
     * </pre>
     *
     * <code>repeated string days = 3 [json_name = "days"];</code>
     * @param index The index to set the value at.
     * @param value The days to set.
     * @return This builder for chaining.
     */
    public Builder setDays(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setDays(index, value);
      return this;
    }
    /**
     * <pre>
     * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
     * each once and in order; none for words.
     * </pre>
     *
     * <code>repeated string days = 3 [json_name = "days"];</code>
     * @param value The days to add.
     * @return This builder for chaining.
     */
    public Builder addDays(
        java.lang.String value) {
      copyOnWrite();
      instance.addDays(value);
      return this;
    }
    /**
     * <pre>
     * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
     * each once and in order; none for words.
     * </pre>
     *
     * <code>repeated string days = 3 [json_name = "days"];</code>
     * @param values The days to add.
     * @return This builder for chaining.
     */
    public Builder addAllDays(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllDays(values);
      return this;
    }
    /**
     * <pre>
     * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
     * each once and in order; none for words.
     * </pre>
     *
     * <code>repeated string days = 3 [json_name = "days"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDays() {
      copyOnWrite();
      instance.clearDays();
      return this;
    }
    /**
     * <pre>
     * 1 to SHARED_DAYS_MAX days (design/src/limits.ts), as YYYY-MM-DD,
     * each once and in order; none for words.
     * </pre>
     *
     * <code>repeated string days = 3 [json_name = "days"];</code>
     * @param value The bytes of the days to add.
     * @return This builder for chaining.
     */
    public Builder addDaysBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addDaysBytes(value);
      return this;
    }

    /**
     * <pre>
     * The days put to the vote instead: 2 days at least, in the group chat.
     * </pre>
     *
     * <code>bool poll = 4 [json_name = "poll"];</code>
     * @return The poll.
     */
    @java.lang.Override
    public boolean getPoll() {
      return instance.getPoll();
    }
    /**
     * <pre>
     * The days put to the vote instead: 2 days at least, in the group chat.
     * </pre>
     *
     * <code>bool poll = 4 [json_name = "poll"];</code>
     * @param value The poll to set.
     * @return This builder for chaining.
     */
    public Builder setPoll(boolean value) {
      copyOnWrite();
      instance.setPoll(value);
      return this;
    }
    /**
     * <pre>
     * The days put to the vote instead: 2 days at least, in the group chat.
     * </pre>
     *
     * <code>bool poll = 4 [json_name = "poll"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPoll() {
      copyOnWrite();
      instance.clearPoll();
      return this;
    }

    /**
     * <pre>
     * A photo instead, the sender's own, uploaded first; no words or days.
     * </pre>
     *
     * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
     */
    @java.lang.Override
    public boolean hasPhoto() {
      return instance.hasPhoto();
    }
    /**
     * <pre>
     * A photo instead, the sender's own, uploaded first; no words or days.
     * </pre>
     *
     * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
     */
    @java.lang.Override
    public app.pochical.v1.ChatPhoto getPhoto() {
      return instance.getPhoto();
    }
    /**
     * <pre>
     * A photo instead, the sender's own, uploaded first; no words or days.
     * </pre>
     *
     * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
     */
    public Builder setPhoto(app.pochical.v1.ChatPhoto value) {
      copyOnWrite();
      instance.setPhoto(value);
      return this;
      }
    /**
     * <pre>
     * A photo instead, the sender's own, uploaded first; no words or days.
     * </pre>
     *
     * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
     */
    public Builder setPhoto(
        app.pochical.v1.ChatPhoto.Builder builderForValue) {
      copyOnWrite();
      instance.setPhoto(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * A photo instead, the sender's own, uploaded first; no words or days.
     * </pre>
     *
     * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
     */
    public Builder mergePhoto(app.pochical.v1.ChatPhoto value) {
      copyOnWrite();
      instance.mergePhoto(value);
      return this;
    }
    /**
     * <pre>
     * A photo instead, the sender's own, uploaded first; no words or days.
     * </pre>
     *
     * <code>.pochical.v1.ChatPhoto photo = 5 [json_name = "photo"];</code>
     */
    public Builder clearPhoto() {  copyOnWrite();
      instance.clearPhoto();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.ChatSend)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new app.pochical.v1.ChatSend();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "threadId_",
            "text_",
            "days_",
            "poll_",
            "photo_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u021a\u0004\u0007\u0005\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<app.pochical.v1.ChatSend> parser = PARSER;
        if (parser == null) {
          synchronized (app.pochical.v1.ChatSend.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<app.pochical.v1.ChatSend>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.ChatSend)
  private static final app.pochical.v1.ChatSend DEFAULT_INSTANCE;
  static {
    ChatSend defaultInstance = new ChatSend();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ChatSend.class, defaultInstance);
  }

  public static app.pochical.v1.ChatSend getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ChatSend> PARSER;

  public static com.google.protobuf.Parser<ChatSend> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

