// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface ChatEditOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.ChatEdit)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Unique per edit, as a DayEdit's: a send taken twice is one line.
   * </pre>
   *
   * <code>string op_id = 1 [json_name = "opId"];</code>
   * @return The opId.
   */
  java.lang.String getOpId();
  /**
   * <pre>
   * Unique per edit, as a DayEdit's: a send taken twice is one line.
   * </pre>
   *
   * <code>string op_id = 1 [json_name = "opId"];</code>
   * @return The bytes for opId.
   */
  com.google.protobuf.ByteString
      getOpIdBytes();

  /**
   * <code>.pochical.v1.ChatSend send = 2 [json_name = "send"];</code>
   * @return Whether the send field is set.
   */
  boolean hasSend();
  /**
   * <code>.pochical.v1.ChatSend send = 2 [json_name = "send"];</code>
   * @return The send.
   */
  app.pochical.v1.ChatSend getSend();

  /**
   * <code>.pochical.v1.ChatChange change = 3 [json_name = "change"];</code>
   * @return Whether the change field is set.
   */
  boolean hasChange();
  /**
   * <code>.pochical.v1.ChatChange change = 3 [json_name = "change"];</code>
   * @return The change.
   */
  app.pochical.v1.ChatChange getChange();

  /**
   * <code>.pochical.v1.ChatUnsend unsend = 4 [json_name = "unsend"];</code>
   * @return Whether the unsend field is set.
   */
  boolean hasUnsend();
  /**
   * <code>.pochical.v1.ChatUnsend unsend = 4 [json_name = "unsend"];</code>
   * @return The unsend.
   */
  app.pochical.v1.ChatUnsend getUnsend();

  /**
   * <code>.pochical.v1.ChatRead read = 5 [json_name = "read"];</code>
   * @return Whether the read field is set.
   */
  boolean hasRead();
  /**
   * <code>.pochical.v1.ChatRead read = 5 [json_name = "read"];</code>
   * @return The read.
   */
  app.pochical.v1.ChatRead getRead();

  public app.pochical.v1.ChatEdit.KindCase getKindCase();
}
