// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface CoworkerEditsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.CoworkerEdits)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .pochical.v1.CoworkerEdit edits = 1 [json_name = "edits"];</code>
   */
  java.util.List<app.pochical.v1.CoworkerEdit> 
      getEditsList();
  /**
   * <code>repeated .pochical.v1.CoworkerEdit edits = 1 [json_name = "edits"];</code>
   */
  app.pochical.v1.CoworkerEdit getEdits(int index);
  /**
   * <code>repeated .pochical.v1.CoworkerEdit edits = 1 [json_name = "edits"];</code>
   */
  int getEditsCount();
}
