// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/group.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface CreateGroupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.CreateGroupResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @return The groupId.
   */
  java.lang.String getGroupId();
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @return The bytes for groupId.
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>string invite_code = 2 [json_name = "inviteCode"];</code>
   * @return The inviteCode.
   */
  java.lang.String getInviteCode();
  /**
   * <code>string invite_code = 2 [json_name = "inviteCode"];</code>
   * @return The bytes for inviteCode.
   */
  com.google.protobuf.ByteString
      getInviteCodeBytes();
}
