// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/group.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface CreateGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.CreateGroupRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * groupName: 1 to 30 characters.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * groupName: 1 to 30 characters.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The group's mark: one emoji. Other marks come later.
   * </pre>
   *
   * <code>string emoji = 2 [json_name = "emoji"];</code>
   * @return The emoji.
   */
  java.lang.String getEmoji();
  /**
   * <pre>
   * The group's mark: one emoji. Other marks come later.
   * </pre>
   *
   * <code>string emoji = 2 [json_name = "emoji"];</code>
   * @return The bytes for emoji.
   */
  com.google.protobuf.ByteString
      getEmojiBytes();

  /**
   * <pre>
   * How the caller appears in this group; personName: 1 to 20 characters.
   * </pre>
   *
   * <code>string display_name = 3 [json_name = "displayName"];</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   * How the caller appears in this group; personName: 1 to 20 characters.
   * </pre>
   *
   * <code>string display_name = 3 [json_name = "displayName"];</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();
}
