// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/group.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface GetInviteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.GetInviteRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string invite_code = 1 [json_name = "inviteCode"];</code>
   * @return The inviteCode.
   */
  java.lang.String getInviteCode();
  /**
   * <code>string invite_code = 1 [json_name = "inviteCode"];</code>
   * @return The bytes for inviteCode.
   */
  com.google.protobuf.ByteString
      getInviteCodeBytes();
}
