// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/chat.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface GetLinkPreviewResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.GetLinkPreviewResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.pochical.v1.LinkPreview preview = 1 [json_name = "preview"];</code>
   * @return Whether the preview field is set.
   */
  boolean hasPreview();
  /**
   * <code>.pochical.v1.LinkPreview preview = 1 [json_name = "preview"];</code>
   * @return The preview.
   */
  app.pochical.v1.LinkPreview getPreview();
}
