// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/marks.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface GroupMarkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.GroupMark)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * One emoji (spec/text-limits.md, isEmoji).
   * </pre>
   *
   * <code>string emoji = 1 [json_name = "emoji"];</code>
   * @return The emoji.
   */
  java.lang.String getEmoji();
  /**
   * <pre>
   * One emoji (spec/text-limits.md, isEmoji).
   * </pre>
   *
   * <code>string emoji = 1 [json_name = "emoji"];</code>
   * @return The bytes for emoji.
   */
  com.google.protobuf.ByteString
      getEmojiBytes();

  /**
   * <pre>
   * A mark icon's name.
   * </pre>
   *
   * <code>string icon = 2 [json_name = "icon"];</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <pre>
   * A mark icon's name.
   * </pre>
   *
   * <code>string icon = 2 [json_name = "icon"];</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <pre>
   * groupMark characters at most (design/src/limits.ts).
   * </pre>
   *
   * <code>string letter = 3 [json_name = "letter"];</code>
   * @return The letter.
   */
  java.lang.String getLetter();
  /**
   * <pre>
   * groupMark characters at most (design/src/limits.ts).
   * </pre>
   *
   * <code>string letter = 3 [json_name = "letter"];</code>
   * @return The bytes for letter.
   */
  com.google.protobuf.ByteString
      getLetterBytes();

  /**
   * <pre>
   * The icon's or letters' color slot, an index into the mark palette
   * (design/src/colors.ts, markColors).
   * </pre>
   *
   * <code>uint32 color = 4 [json_name = "color"];</code>
   * @return The color.
   */
  int getColor();
}
