// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/group.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

/**
 * Protobuf type {@code pochical.v1.LeaveGroupRequest}
 */
@com.google.protobuf.Generated
public  final class LeaveGroupRequest extends
    com.google.protobuf.GeneratedMessageLite<
        LeaveGroupRequest, LeaveGroupRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.LeaveGroupRequest)
    LeaveGroupRequestOrBuilder {
  private LeaveGroupRequest() {
    groupId_ = "";
  }
  public static final int GROUP_ID_FIELD_NUMBER = 1;
  private java.lang.String groupId_;
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @return The groupId.
   */
  @java.lang.Override
  public java.lang.String getGroupId() {
    return groupId_;
  }
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @return The bytes for groupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(groupId_);
  }
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @param value The groupId to set.
   */
  private void setGroupId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    groupId_ = value;
  }
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   */
  private void clearGroupId() {

    groupId_ = getDefaultInstance().getGroupId();
  }
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @param value The bytes for groupId to set.
   */
  private void setGroupIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    groupId_ = value.toStringUtf8();

  }

  public static app.pochical.v1.LeaveGroupRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.LeaveGroupRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.LeaveGroupRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.LeaveGroupRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.LeaveGroupRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.LeaveGroupRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.LeaveGroupRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.LeaveGroupRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static app.pochical.v1.LeaveGroupRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static app.pochical.v1.LeaveGroupRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static app.pochical.v1.LeaveGroupRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.LeaveGroupRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(app.pochical.v1.LeaveGroupRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code pochical.v1.LeaveGroupRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        app.pochical.v1.LeaveGroupRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.LeaveGroupRequest)
      app.pochical.v1.LeaveGroupRequestOrBuilder {
    // Construct using app.pochical.v1.LeaveGroupRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @return The groupId.
     */
    @java.lang.Override
    public java.lang.String getGroupId() {
      return instance.getGroupId();
    }
    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @return The bytes for groupId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      return instance.getGroupIdBytes();
    }
    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(
        java.lang.String value) {
      copyOnWrite();
      instance.setGroupId(value);
      return this;
    }
    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      copyOnWrite();
      instance.clearGroupId();
      return this;
    }
    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @param value The bytes for groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGroupIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.LeaveGroupRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new app.pochical.v1.LeaveGroupRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "groupId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<app.pochical.v1.LeaveGroupRequest> parser = PARSER;
        if (parser == null) {
          synchronized (app.pochical.v1.LeaveGroupRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<app.pochical.v1.LeaveGroupRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.LeaveGroupRequest)
  private static final app.pochical.v1.LeaveGroupRequest DEFAULT_INSTANCE;
  static {
    LeaveGroupRequest defaultInstance = new LeaveGroupRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LeaveGroupRequest.class, defaultInstance);
  }

  public static app.pochical.v1.LeaveGroupRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LeaveGroupRequest> PARSER;

  public static com.google.protobuf.Parser<LeaveGroupRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

