// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

/**
 * <pre>
 * One of a member's patterns, so the group can draw their marks.
 * </pre>
 *
 * Protobuf type {@code pochical.v1.MemberPattern}
 */
@com.google.protobuf.Generated
public  final class MemberPattern extends
    com.google.protobuf.GeneratedMessageLite<
        MemberPattern, MemberPattern.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.MemberPattern)
    MemberPatternOrBuilder {
  private MemberPattern() {
    userId_ = "";
  }
  private int bitField0_;
  public static final int USER_ID_FIELD_NUMBER = 1;
  private java.lang.String userId_;
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @param value The userId to set.
   */
  private void setUserId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    userId_ = value;
  }
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   */
  private void clearUserId() {

    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();

  }

  public static final int PATTERN_FIELD_NUMBER = 2;
  private app.pochical.v1.PatternValue pattern_;
  /**
   * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
   */
  @java.lang.Override
  public boolean hasPattern() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
   */
  @java.lang.Override
  public app.pochical.v1.PatternValue getPattern() {
    return pattern_ == null ? app.pochical.v1.PatternValue.getDefaultInstance() : pattern_;
  }
  /**
   * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
   */
  private void setPattern(app.pochical.v1.PatternValue value) {
    java.util.Objects.requireNonNull(value);
    pattern_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergePattern(app.pochical.v1.PatternValue value) {
    java.util.Objects.requireNonNull(value);
    if (pattern_ != null &&
        pattern_ != app.pochical.v1.PatternValue.getDefaultInstance()) {
      pattern_ =
        app.pochical.v1.PatternValue.newBuilder(pattern_).mergeFrom(value).buildPartial();
    } else {
      pattern_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
   */
  private void clearPattern() {
    pattern_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static app.pochical.v1.MemberPattern parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.MemberPattern parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.MemberPattern parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.MemberPattern parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.MemberPattern parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.MemberPattern parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.MemberPattern parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.MemberPattern parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static app.pochical.v1.MemberPattern parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static app.pochical.v1.MemberPattern parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static app.pochical.v1.MemberPattern parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.MemberPattern parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(app.pochical.v1.MemberPattern prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * One of a member's patterns, so the group can draw their marks.
   * </pre>
   *
   * Protobuf type {@code pochical.v1.MemberPattern}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        app.pochical.v1.MemberPattern, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.MemberPattern)
      app.pochical.v1.MemberPatternOrBuilder {
    // Construct using app.pochical.v1.MemberPattern.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
     */
    @java.lang.Override
    public boolean hasPattern() {
      return instance.hasPattern();
    }
    /**
     * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
     */
    @java.lang.Override
    public app.pochical.v1.PatternValue getPattern() {
      return instance.getPattern();
    }
    /**
     * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
     */
    public Builder setPattern(app.pochical.v1.PatternValue value) {
      copyOnWrite();
      instance.setPattern(value);
      return this;
      }
    /**
     * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
     */
    public Builder setPattern(
        app.pochical.v1.PatternValue.Builder builderForValue) {
      copyOnWrite();
      instance.setPattern(builderForValue.build());
      return this;
    }
    /**
     * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
     */
    public Builder mergePattern(app.pochical.v1.PatternValue value) {
      copyOnWrite();
      instance.mergePattern(value);
      return this;
    }
    /**
     * <code>.pochical.v1.PatternValue pattern = 2 [json_name = "pattern"];</code>
     */
    public Builder clearPattern() {  copyOnWrite();
      instance.clearPattern();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.MemberPattern)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new app.pochical.v1.MemberPattern();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "userId_",
            "pattern_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<app.pochical.v1.MemberPattern> parser = PARSER;
        if (parser == null) {
          synchronized (app.pochical.v1.MemberPattern.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<app.pochical.v1.MemberPattern>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.MemberPattern)
  private static final app.pochical.v1.MemberPattern DEFAULT_INSTANCE;
  static {
    MemberPattern defaultInstance = new MemberPattern();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MemberPattern.class, defaultInstance);
  }

  public static app.pochical.v1.MemberPattern getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MemberPattern> PARSER;

  public static com.google.protobuf.Parser<MemberPattern> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

