// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

/**
 * <pre>
 * One of the owner's preferences, how they like their screens: one
 * last-writer-wins value a key, kept with the account so each of their
 * devices shows the same (spec/sync-protocol.md, Preferences). The server
 * keeps what it is given without reading it; the apps read the value.
 * </pre>
 *
 * Protobuf type {@code pochical.v1.PreferenceValue}
 */
@com.google.protobuf.Generated
public  final class PreferenceValue extends
    com.google.protobuf.GeneratedMessageLite<
        PreferenceValue, PreferenceValue.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.PreferenceValue)
    PreferenceValueOrBuilder {
  private PreferenceValue() {
    key_ = "";
    value_ = "";
  }
  private int bitField0_;
  public static final int KEY_FIELD_NUMBER = 1;
  private java.lang.String key_;
  /**
   * <pre>
   * Which preference, as the apps name it: an id (syncLimits.idLength).
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    return key_;
  }
  /**
   * <pre>
   * Which preference, as the apps name it: an id (syncLimits.idLength).
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(key_);
  }
  /**
   * <pre>
   * Which preference, as the apps name it: an id (syncLimits.idLength).
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @param value The key to set.
   */
  private void setKey(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    key_ = value;
  }
  /**
   * <pre>
   * Which preference, as the apps name it: an id (syncLimits.idLength).
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   */
  private void clearKey() {

    key_ = getDefaultInstance().getKey();
  }
  /**
   * <pre>
   * Which preference, as the apps name it: an id (syncLimits.idLength).
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @param value The bytes for key to set.
   */
  private void setKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    key_ = value.toStringUtf8();

  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private java.lang.String value_;
  /**
   * <pre>
   * As the apps write it, JSON, syncLimits.preferenceLength characters at
   * most. Unset: back to the apps' own default.
   * </pre>
   *
   * <code>optional string value = 2 [json_name = "value"];</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * As the apps write it, JSON, syncLimits.preferenceLength characters at
   * most. Unset: back to the apps' own default.
   * </pre>
   *
   * <code>optional string value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    return value_;
  }
  /**
   * <pre>
   * As the apps write it, JSON, syncLimits.preferenceLength characters at
   * most. Unset: back to the apps' own default.
   * </pre>
   *
   * <code>optional string value = 2 [json_name = "value"];</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(value_);
  }
  /**
   * <pre>
   * As the apps write it, JSON, syncLimits.preferenceLength characters at
   * most. Unset: back to the apps' own default.
   * </pre>
   *
   * <code>optional string value = 2 [json_name = "value"];</code>
   * @param value The value to set.
   */
  private void setValue(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    bitField0_ |= 0x00000001;
    value_ = value;
  }
  /**
   * <pre>
   * As the apps write it, JSON, syncLimits.preferenceLength characters at
   * most. Unset: back to the apps' own default.
   * </pre>
   *
   * <code>optional string value = 2 [json_name = "value"];</code>
   */
  private void clearValue() {
    bitField0_ = (bitField0_ & ~0x00000001);
    value_ = getDefaultInstance().getValue();
  }
  /**
   * <pre>
   * As the apps write it, JSON, syncLimits.preferenceLength characters at
   * most. Unset: back to the apps' own default.
   * </pre>
   *
   * <code>optional string value = 2 [json_name = "value"];</code>
   * @param value The bytes for value to set.
   */
  private void setValueBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    value_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int HLC_FIELD_NUMBER = 3;
  private app.pochical.v1.Hlc hlc_;
  /**
   * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
   */
  @java.lang.Override
  public boolean hasHlc() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
   */
  @java.lang.Override
  public app.pochical.v1.Hlc getHlc() {
    return hlc_ == null ? app.pochical.v1.Hlc.getDefaultInstance() : hlc_;
  }
  /**
   * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
   */
  private void setHlc(app.pochical.v1.Hlc value) {
    java.util.Objects.requireNonNull(value);
    hlc_ = value;
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeHlc(app.pochical.v1.Hlc value) {
    java.util.Objects.requireNonNull(value);
    if (hlc_ != null &&
        hlc_ != app.pochical.v1.Hlc.getDefaultInstance()) {
      hlc_ =
        app.pochical.v1.Hlc.newBuilder(hlc_).mergeFrom(value).buildPartial();
    } else {
      hlc_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
   */
  private void clearHlc() {
    hlc_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static app.pochical.v1.PreferenceValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.PreferenceValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.PreferenceValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.PreferenceValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.PreferenceValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.PreferenceValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.PreferenceValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.PreferenceValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static app.pochical.v1.PreferenceValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static app.pochical.v1.PreferenceValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static app.pochical.v1.PreferenceValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.PreferenceValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(app.pochical.v1.PreferenceValue prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * One of the owner's preferences, how they like their screens: one
   * last-writer-wins value a key, kept with the account so each of their
   * devices shows the same (spec/sync-protocol.md, Preferences). The server
   * keeps what it is given without reading it; the apps read the value.
   * </pre>
   *
   * Protobuf type {@code pochical.v1.PreferenceValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        app.pochical.v1.PreferenceValue, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.PreferenceValue)
      app.pochical.v1.PreferenceValueOrBuilder {
    // Construct using app.pochical.v1.PreferenceValue.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Which preference, as the apps name it: an id (syncLimits.idLength).
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return instance.getKey();
    }
    /**
     * <pre>
     * Which preference, as the apps name it: an id (syncLimits.idLength).
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return instance.getKeyBytes();
    }
    /**
     * <pre>
     * Which preference, as the apps name it: an id (syncLimits.idLength).
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setKey(value);
      return this;
    }
    /**
     * <pre>
     * Which preference, as the apps name it: an id (syncLimits.idLength).
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      copyOnWrite();
      instance.clearKey();
      return this;
    }
    /**
     * <pre>
     * Which preference, as the apps name it: an id (syncLimits.idLength).
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKeyBytes(value);
      return this;
    }

    /**
     * <pre>
     * As the apps write it, JSON, syncLimits.preferenceLength characters at
     * most. Unset: back to the apps' own default.
     * </pre>
     *
     * <code>optional string value = 2 [json_name = "value"];</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return instance.hasValue();
    }
    /**
     * <pre>
     * As the apps write it, JSON, syncLimits.preferenceLength characters at
     * most. Unset: back to the apps' own default.
     * </pre>
     *
     * <code>optional string value = 2 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return instance.getValue();
    }
    /**
     * <pre>
     * As the apps write it, JSON, syncLimits.preferenceLength characters at
     * most. Unset: back to the apps' own default.
     * </pre>
     *
     * <code>optional string value = 2 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return instance.getValueBytes();
    }
    /**
     * <pre>
     * As the apps write it, JSON, syncLimits.preferenceLength characters at
     * most. Unset: back to the apps' own default.
     * </pre>
     *
     * <code>optional string value = 2 [json_name = "value"];</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setValue(value);
      return this;
    }
    /**
     * <pre>
     * As the apps write it, JSON, syncLimits.preferenceLength characters at
     * most. Unset: back to the apps' own default.
     * </pre>
     *
     * <code>optional string value = 2 [json_name = "value"];</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }
    /**
     * <pre>
     * As the apps write it, JSON, syncLimits.preferenceLength characters at
     * most. Unset: back to the apps' own default.
     * </pre>
     *
     * <code>optional string value = 2 [json_name = "value"];</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setValueBytes(value);
      return this;
    }

    /**
     * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
     */
    @java.lang.Override
    public boolean hasHlc() {
      return instance.hasHlc();
    }
    /**
     * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
     */
    @java.lang.Override
    public app.pochical.v1.Hlc getHlc() {
      return instance.getHlc();
    }
    /**
     * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
     */
    public Builder setHlc(app.pochical.v1.Hlc value) {
      copyOnWrite();
      instance.setHlc(value);
      return this;
      }
    /**
     * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
     */
    public Builder setHlc(
        app.pochical.v1.Hlc.Builder builderForValue) {
      copyOnWrite();
      instance.setHlc(builderForValue.build());
      return this;
    }
    /**
     * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
     */
    public Builder mergeHlc(app.pochical.v1.Hlc value) {
      copyOnWrite();
      instance.mergeHlc(value);
      return this;
    }
    /**
     * <code>.pochical.v1.Hlc hlc = 3 [json_name = "hlc"];</code>
     */
    public Builder clearHlc() {  copyOnWrite();
      instance.clearHlc();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.PreferenceValue)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new app.pochical.v1.PreferenceValue();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "key_",
            "value_",
            "hlc_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u1208" +
              "\u0000\u0003\u1009\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<app.pochical.v1.PreferenceValue> parser = PARSER;
        if (parser == null) {
          synchronized (app.pochical.v1.PreferenceValue.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<app.pochical.v1.PreferenceValue>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.PreferenceValue)
  private static final app.pochical.v1.PreferenceValue DEFAULT_INSTANCE;
  static {
    PreferenceValue defaultInstance = new PreferenceValue();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PreferenceValue.class, defaultInstance);
  }

  public static app.pochical.v1.PreferenceValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PreferenceValue> PARSER;

  public static com.google.protobuf.Parser<PreferenceValue> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

