// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface ProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.Profile)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * personName characters at most (design/src/limits.ts); empty for none.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * personName characters at most (design/src/limits.ts); empty for none.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The usual photo, one of the user's own photos (/v1/me/photos/{id});
   * empty for none.
   * </pre>
   *
   * <code>string photo_id = 2 [json_name = "photoId"];</code>
   * @return The photoId.
   */
  java.lang.String getPhotoId();
  /**
   * <pre>
   * The usual photo, one of the user's own photos (/v1/me/photos/{id});
   * empty for none.
   * </pre>
   *
   * <code>string photo_id = 2 [json_name = "photoId"];</code>
   * @return The bytes for photoId.
   */
  com.google.protobuf.ByteString
      getPhotoIdBytes();
}
