// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/support.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

/**
 * Protobuf type {@code pochical.v1.ReactSupportResponse}
 */
@com.google.protobuf.Generated
public  final class ReactSupportResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ReactSupportResponse, ReactSupportResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.ReactSupportResponse)
    ReactSupportResponseOrBuilder {
  private ReactSupportResponse() {
  }
  private int bitField0_;
  public static final int MESSAGE_FIELD_NUMBER = 1;
  private app.pochical.v1.SupportMessage message_;
  /**
   * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
   */
  @java.lang.Override
  public app.pochical.v1.SupportMessage getMessage() {
    return message_ == null ? app.pochical.v1.SupportMessage.getDefaultInstance() : message_;
  }
  /**
   * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
   */
  private void setMessage(app.pochical.v1.SupportMessage value) {
    java.util.Objects.requireNonNull(value);
    message_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeMessage(app.pochical.v1.SupportMessage value) {
    java.util.Objects.requireNonNull(value);
    if (message_ != null &&
        message_ != app.pochical.v1.SupportMessage.getDefaultInstance()) {
      message_ =
        app.pochical.v1.SupportMessage.newBuilder(message_).mergeFrom(value).buildPartial();
    } else {
      message_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
   */
  private void clearMessage() {
    message_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static app.pochical.v1.ReactSupportResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.ReactSupportResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.ReactSupportResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.ReactSupportResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.ReactSupportResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.ReactSupportResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.ReactSupportResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.ReactSupportResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static app.pochical.v1.ReactSupportResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static app.pochical.v1.ReactSupportResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static app.pochical.v1.ReactSupportResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.ReactSupportResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(app.pochical.v1.ReactSupportResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code pochical.v1.ReactSupportResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        app.pochical.v1.ReactSupportResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.ReactSupportResponse)
      app.pochical.v1.ReactSupportResponseOrBuilder {
    // Construct using app.pochical.v1.ReactSupportResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
     */
    @java.lang.Override
    public boolean hasMessage() {
      return instance.hasMessage();
    }
    /**
     * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
     */
    @java.lang.Override
    public app.pochical.v1.SupportMessage getMessage() {
      return instance.getMessage();
    }
    /**
     * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
     */
    public Builder setMessage(app.pochical.v1.SupportMessage value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
      }
    /**
     * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
     */
    public Builder setMessage(
        app.pochical.v1.SupportMessage.Builder builderForValue) {
      copyOnWrite();
      instance.setMessage(builderForValue.build());
      return this;
    }
    /**
     * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
     */
    public Builder mergeMessage(app.pochical.v1.SupportMessage value) {
      copyOnWrite();
      instance.mergeMessage(value);
      return this;
    }
    /**
     * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
     */
    public Builder clearMessage() {  copyOnWrite();
      instance.clearMessage();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.ReactSupportResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new app.pochical.v1.ReactSupportResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "message_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<app.pochical.v1.ReactSupportResponse> parser = PARSER;
        if (parser == null) {
          synchronized (app.pochical.v1.ReactSupportResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<app.pochical.v1.ReactSupportResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.ReactSupportResponse)
  private static final app.pochical.v1.ReactSupportResponse DEFAULT_INSTANCE;
  static {
    ReactSupportResponse defaultInstance = new ReactSupportResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ReactSupportResponse.class, defaultInstance);
  }

  public static app.pochical.v1.ReactSupportResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ReactSupportResponse> PARSER;

  public static com.google.protobuf.Parser<ReactSupportResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

