// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/support.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface ReactSupportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.ReactSupportRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The line, by id.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The line, by id.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string emoji = 2 [json_name = "emoji"];</code>
   * @return The emoji.
   */
  java.lang.String getEmoji();
  /**
   * <code>string emoji = 2 [json_name = "emoji"];</code>
   * @return The bytes for emoji.
   */
  com.google.protobuf.ByteString
      getEmojiBytes();

  /**
   * <pre>
   * Put on, or taken off.
   * </pre>
   *
   * <code>bool on = 3 [json_name = "on"];</code>
   * @return The on.
   */
  boolean getOn();
}
