// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface ReadMarkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.ReadMark)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string thread_id = 2 [json_name = "threadId"];</code>
   * @return The threadId.
   */
  java.lang.String getThreadId();
  /**
   * <code>string thread_id = 2 [json_name = "threadId"];</code>
   * @return The bytes for threadId.
   */
  com.google.protobuf.ByteString
      getThreadIdBytes();

  /**
   * <code>uint64 last_read_seq = 3 [json_name = "lastReadSeq"];</code>
   * @return The lastReadSeq.
   */
  long getLastReadSeq();
}
