// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface RepeatOrdersEditOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.RepeatOrdersEdit)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Unique per edit, as a DayEdit's.
   * </pre>
   *
   * <code>string op_id = 1 [json_name = "opId"];</code>
   * @return The opId.
   */
  java.lang.String getOpId();
  /**
   * <pre>
   * Unique per edit, as a DayEdit's.
   * </pre>
   *
   * <code>string op_id = 1 [json_name = "opId"];</code>
   * @return The bytes for opId.
   */
  com.google.protobuf.ByteString
      getOpIdBytes();

  /**
   * <code>.pochical.v1.RepeatOrders orders = 2 [json_name = "orders"];</code>
   * @return Whether the orders field is set.
   */
  boolean hasOrders();
  /**
   * <code>.pochical.v1.RepeatOrders orders = 2 [json_name = "orders"];</code>
   * @return The orders.
   */
  app.pochical.v1.RepeatOrders getOrders();

  /**
   * <pre>
   * The new or corrected order's start: when the server takes the orders,
   * the days from it give their own pattern and times back to the order,
   * those older than the edit's clock. Unset clears nothing.
   * </pre>
   *
   * <code>optional string clear_from = 3 [json_name = "clearFrom"];</code>
   * @return Whether the clearFrom field is set.
   */
  boolean hasClearFrom();
  /**
   * <pre>
   * The new or corrected order's start: when the server takes the orders,
   * the days from it give their own pattern and times back to the order,
   * those older than the edit's clock. Unset clears nothing.
   * </pre>
   *
   * <code>optional string clear_from = 3 [json_name = "clearFrom"];</code>
   * @return The clearFrom.
   */
  java.lang.String getClearFrom();
  /**
   * <pre>
   * The new or corrected order's start: when the server takes the orders,
   * the days from it give their own pattern and times back to the order,
   * those older than the edit's clock. Unset clears nothing.
   * </pre>
   *
   * <code>optional string clear_from = 3 [json_name = "clearFrom"];</code>
   * @return The bytes for clearFrom.
   */
  com.google.protobuf.ByteString
      getClearFromBytes();
}
