// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface RepeatOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.RepeatOrder)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The first day it applies, "YYYY-MM-DD".
   * </pre>
   *
   * <code>string start = 1 [json_name = "start"];</code>
   * @return The start.
   */
  java.lang.String getStart();
  /**
   * <pre>
   * The first day it applies, "YYYY-MM-DD".
   * </pre>
   *
   * <code>string start = 1 [json_name = "start"];</code>
   * @return The bytes for start.
   */
  com.google.protobuf.ByteString
      getStartBytes();

  /**
   * <pre>
   * A day that falls on the sequence's first shift, "YYYY-MM-DD"; unset,
   * the start.
   * </pre>
   *
   * <code>optional string anchor = 2 [json_name = "anchor"];</code>
   * @return Whether the anchor field is set.
   */
  boolean hasAnchor();
  /**
   * <pre>
   * A day that falls on the sequence's first shift, "YYYY-MM-DD"; unset,
   * the start.
   * </pre>
   *
   * <code>optional string anchor = 2 [json_name = "anchor"];</code>
   * @return The anchor.
   */
  java.lang.String getAnchor();
  /**
   * <pre>
   * A day that falls on the sequence's first shift, "YYYY-MM-DD"; unset,
   * the start.
   * </pre>
   *
   * <code>optional string anchor = 2 [json_name = "anchor"];</code>
   * @return The bytes for anchor.
   */
  com.google.protobuf.ByteString
      getAnchorBytes();

  /**
   * <pre>
   * Pattern ids, one a day. Empty: repeating ends from the start, and days
   * are entered by hand.
   * </pre>
   *
   * <code>repeated string sequence = 3 [json_name = "sequence"];</code>
   * @return A list containing the sequence.
   */
  java.util.List<java.lang.String>
      getSequenceList();
  /**
   * <pre>
   * Pattern ids, one a day. Empty: repeating ends from the start, and days
   * are entered by hand.
   * </pre>
   *
   * <code>repeated string sequence = 3 [json_name = "sequence"];</code>
   * @return The count of sequence.
   */
  int getSequenceCount();
  /**
   * <pre>
   * Pattern ids, one a day. Empty: repeating ends from the start, and days
   * are entered by hand.
   * </pre>
   *
   * <code>repeated string sequence = 3 [json_name = "sequence"];</code>
   * @param index The index of the element to return.
   * @return The sequence at the given index.
   */
  java.lang.String getSequence(int index);
  /**
   * <pre>
   * Pattern ids, one a day. Empty: repeating ends from the start, and days
   * are entered by hand.
   * </pre>
   *
   * <code>repeated string sequence = 3 [json_name = "sequence"];</code>
   * @param index The index of the element to return.
   * @return The sequence at the given index.
   */
  com.google.protobuf.ByteString
      getSequenceBytes(int index);

  /**
   * <pre>
   * 祝日は休みにする: the national holidays of holiday_country take
   * holiday_shift in place of the sequence's shift.
   * </pre>
   *
   * <code>bool holidays_off = 4 [json_name = "holidaysOff"];</code>
   * @return The holidaysOff.
   */
  boolean getHolidaysOff();

  /**
   * <pre>
   * The day-off pattern holidays take, the person's first one when
   * holidays_off was turned on; set whenever holidays_off is.
   * </pre>
   *
   * <code>optional string holiday_shift = 5 [json_name = "holidayShift"];</code>
   * @return Whether the holidayShift field is set.
   */
  boolean hasHolidayShift();
  /**
   * <pre>
   * The day-off pattern holidays take, the person's first one when
   * holidays_off was turned on; set whenever holidays_off is.
   * </pre>
   *
   * <code>optional string holiday_shift = 5 [json_name = "holidayShift"];</code>
   * @return The holidayShift.
   */
  java.lang.String getHolidayShift();
  /**
   * <pre>
   * The day-off pattern holidays take, the person's first one when
   * holidays_off was turned on; set whenever holidays_off is.
   * </pre>
   *
   * <code>optional string holiday_shift = 5 [json_name = "holidayShift"];</code>
   * @return The bytes for holidayShift.
   */
  com.google.protobuf.ByteString
      getHolidayShiftBytes();

  /**
   * <pre>
   * Whose holidays, as a country code ("JP"): the device's region when the
   * order was made.
   * </pre>
   *
   * <code>string holiday_country = 6 [json_name = "holidayCountry"];</code>
   * @return The holidayCountry.
   */
  java.lang.String getHolidayCountry();
  /**
   * <pre>
   * Whose holidays, as a country code ("JP"): the device's region when the
   * order was made.
   * </pre>
   *
   * <code>string holiday_country = 6 [json_name = "holidayCountry"];</code>
   * @return The bytes for holidayCountry.
   */
  com.google.protobuf.ByteString
      getHolidayCountryBytes();
}
