// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface RepeatOrdersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.RepeatOrders)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .pochical.v1.RepeatOrder orders = 1 [json_name = "orders"];</code>
   */
  java.util.List<app.pochical.v1.RepeatOrder> 
      getOrdersList();
  /**
   * <code>repeated .pochical.v1.RepeatOrder orders = 1 [json_name = "orders"];</code>
   */
  app.pochical.v1.RepeatOrder getOrders(int index);
  /**
   * <code>repeated .pochical.v1.RepeatOrder orders = 1 [json_name = "orders"];</code>
   */
  int getOrdersCount();

  /**
   * <code>.pochical.v1.Hlc hlc = 2 [json_name = "hlc"];</code>
   * @return Whether the hlc field is set.
   */
  boolean hasHlc();
  /**
   * <code>.pochical.v1.Hlc hlc = 2 [json_name = "hlc"];</code>
   * @return The hlc.
   */
  app.pochical.v1.Hlc getHlc();
}
