// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/user.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface SetChatMutedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.SetChatMutedRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @return The groupId.
   */
  java.lang.String getGroupId();
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @return The bytes for groupId.
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <pre>
   * "group" for the group's chat, or a one-to-one chat the user is in.
   * </pre>
   *
   * <code>string thread_id = 2 [json_name = "threadId"];</code>
   * @return The threadId.
   */
  java.lang.String getThreadId();
  /**
   * <pre>
   * "group" for the group's chat, or a one-to-one chat the user is in.
   * </pre>
   *
   * <code>string thread_id = 2 [json_name = "threadId"];</code>
   * @return The bytes for threadId.
   */
  com.google.protobuf.ByteString
      getThreadIdBytes();

  /**
   * <code>bool muted = 3 [json_name = "muted"];</code>
   * @return The muted.
   */
  boolean getMuted();
}
