// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/support.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface SupportMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.SupportMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Written by Pochical's people, not the user.
   * </pre>
   *
   * <code>bool from_support = 2 [json_name = "fromSupport"];</code>
   * @return The fromSupport.
   */
  boolean getFromSupport();

  /**
   * <code>string text = 3 [json_name = "text"];</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 3 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>int64 sent_at_ms = 4 [json_name = "sentAtMs"];</code>
   * @return The sentAtMs.
   */
  long getSentAtMs();
}
