// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/support.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

/**
 * <pre>
 * An emoji on a line, put there by the user, by Pochical's people, or by
 * both.
 * </pre>
 *
 * Protobuf type {@code pochical.v1.SupportReaction}
 */
@com.google.protobuf.Generated
public  final class SupportReaction extends
    com.google.protobuf.GeneratedMessageLite<
        SupportReaction, SupportReaction.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.SupportReaction)
    SupportReactionOrBuilder {
  private SupportReaction() {
    emoji_ = "";
  }
  public static final int EMOJI_FIELD_NUMBER = 1;
  private java.lang.String emoji_;
  /**
   * <code>string emoji = 1 [json_name = "emoji"];</code>
   * @return The emoji.
   */
  @java.lang.Override
  public java.lang.String getEmoji() {
    return emoji_;
  }
  /**
   * <code>string emoji = 1 [json_name = "emoji"];</code>
   * @return The bytes for emoji.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmojiBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(emoji_);
  }
  /**
   * <code>string emoji = 1 [json_name = "emoji"];</code>
   * @param value The emoji to set.
   */
  private void setEmoji(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    emoji_ = value;
  }
  /**
   * <code>string emoji = 1 [json_name = "emoji"];</code>
   */
  private void clearEmoji() {

    emoji_ = getDefaultInstance().getEmoji();
  }
  /**
   * <code>string emoji = 1 [json_name = "emoji"];</code>
   * @param value The bytes for emoji to set.
   */
  private void setEmojiBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    emoji_ = value.toStringUtf8();

  }

  public static final int MINE_FIELD_NUMBER = 2;
  private boolean mine_;
  /**
   * <code>bool mine = 2 [json_name = "mine"];</code>
   * @return The mine.
   */
  @java.lang.Override
  public boolean getMine() {
    return mine_;
  }
  /**
   * <code>bool mine = 2 [json_name = "mine"];</code>
   * @param value The mine to set.
   */
  private void setMine(boolean value) {
    
    mine_ = value;
  }
  /**
   * <code>bool mine = 2 [json_name = "mine"];</code>
   */
  private void clearMine() {

    mine_ = false;
  }

  public static final int SUPPORT_FIELD_NUMBER = 3;
  private boolean support_;
  /**
   * <code>bool support = 3 [json_name = "support"];</code>
   * @return The support.
   */
  @java.lang.Override
  public boolean getSupport() {
    return support_;
  }
  /**
   * <code>bool support = 3 [json_name = "support"];</code>
   * @param value The support to set.
   */
  private void setSupport(boolean value) {
    
    support_ = value;
  }
  /**
   * <code>bool support = 3 [json_name = "support"];</code>
   */
  private void clearSupport() {

    support_ = false;
  }

  public static app.pochical.v1.SupportReaction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.SupportReaction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.SupportReaction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.SupportReaction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.SupportReaction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.SupportReaction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.SupportReaction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.SupportReaction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static app.pochical.v1.SupportReaction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static app.pochical.v1.SupportReaction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static app.pochical.v1.SupportReaction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.SupportReaction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(app.pochical.v1.SupportReaction prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * An emoji on a line, put there by the user, by Pochical's people, or by
   * both.
   * </pre>
   *
   * Protobuf type {@code pochical.v1.SupportReaction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        app.pochical.v1.SupportReaction, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.SupportReaction)
      app.pochical.v1.SupportReactionOrBuilder {
    // Construct using app.pochical.v1.SupportReaction.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string emoji = 1 [json_name = "emoji"];</code>
     * @return The emoji.
     */
    @java.lang.Override
    public java.lang.String getEmoji() {
      return instance.getEmoji();
    }
    /**
     * <code>string emoji = 1 [json_name = "emoji"];</code>
     * @return The bytes for emoji.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmojiBytes() {
      return instance.getEmojiBytes();
    }
    /**
     * <code>string emoji = 1 [json_name = "emoji"];</code>
     * @param value The emoji to set.
     * @return This builder for chaining.
     */
    public Builder setEmoji(
        java.lang.String value) {
      copyOnWrite();
      instance.setEmoji(value);
      return this;
    }
    /**
     * <code>string emoji = 1 [json_name = "emoji"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEmoji() {
      copyOnWrite();
      instance.clearEmoji();
      return this;
    }
    /**
     * <code>string emoji = 1 [json_name = "emoji"];</code>
     * @param value The bytes for emoji to set.
     * @return This builder for chaining.
     */
    public Builder setEmojiBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEmojiBytes(value);
      return this;
    }

    /**
     * <code>bool mine = 2 [json_name = "mine"];</code>
     * @return The mine.
     */
    @java.lang.Override
    public boolean getMine() {
      return instance.getMine();
    }
    /**
     * <code>bool mine = 2 [json_name = "mine"];</code>
     * @param value The mine to set.
     * @return This builder for chaining.
     */
    public Builder setMine(boolean value) {
      copyOnWrite();
      instance.setMine(value);
      return this;
    }
    /**
     * <code>bool mine = 2 [json_name = "mine"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMine() {
      copyOnWrite();
      instance.clearMine();
      return this;
    }

    /**
     * <code>bool support = 3 [json_name = "support"];</code>
     * @return The support.
     */
    @java.lang.Override
    public boolean getSupport() {
      return instance.getSupport();
    }
    /**
     * <code>bool support = 3 [json_name = "support"];</code>
     * @param value The support to set.
     * @return This builder for chaining.
     */
    public Builder setSupport(boolean value) {
      copyOnWrite();
      instance.setSupport(value);
      return this;
    }
    /**
     * <code>bool support = 3 [json_name = "support"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSupport() {
      copyOnWrite();
      instance.clearSupport();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.SupportReaction)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new app.pochical.v1.SupportReaction();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "emoji_",
            "mine_",
            "support_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0007" +
              "\u0003\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<app.pochical.v1.SupportReaction> parser = PARSER;
        if (parser == null) {
          synchronized (app.pochical.v1.SupportReaction.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<app.pochical.v1.SupportReaction>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.SupportReaction)
  private static final app.pochical.v1.SupportReaction DEFAULT_INSTANCE;
  static {
    SupportReaction defaultInstance = new SupportReaction();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SupportReaction.class, defaultInstance);
  }

  public static app.pochical.v1.SupportReaction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SupportReaction> PARSER;

  public static com.google.protobuf.Parser<SupportReaction> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

