// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

/**
 * <pre>
 * How many lines of a group's chat the user has not read: others' lines
 * past their read mark. One value per chat, the group's latest.
 * </pre>
 *
 * Protobuf type {@code pochical.v1.UnreadCount}
 */
@com.google.protobuf.Generated
public  final class UnreadCount extends
    com.google.protobuf.GeneratedMessageLite<
        UnreadCount, UnreadCount.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.UnreadCount)
    UnreadCountOrBuilder {
  private UnreadCount() {
    groupId_ = "";
    threadId_ = "";
  }
  public static final int GROUP_ID_FIELD_NUMBER = 1;
  private java.lang.String groupId_;
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @return The groupId.
   */
  @java.lang.Override
  public java.lang.String getGroupId() {
    return groupId_;
  }
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @return The bytes for groupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(groupId_);
  }
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @param value The groupId to set.
   */
  private void setGroupId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    groupId_ = value;
  }
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   */
  private void clearGroupId() {

    groupId_ = getDefaultInstance().getGroupId();
  }
  /**
   * <code>string group_id = 1 [json_name = "groupId"];</code>
   * @param value The bytes for groupId to set.
   */
  private void setGroupIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    groupId_ = value.toStringUtf8();

  }

  public static final int THREAD_ID_FIELD_NUMBER = 2;
  private java.lang.String threadId_;
  /**
   * <code>string thread_id = 2 [json_name = "threadId"];</code>
   * @return The threadId.
   */
  @java.lang.Override
  public java.lang.String getThreadId() {
    return threadId_;
  }
  /**
   * <code>string thread_id = 2 [json_name = "threadId"];</code>
   * @return The bytes for threadId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreadIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(threadId_);
  }
  /**
   * <code>string thread_id = 2 [json_name = "threadId"];</code>
   * @param value The threadId to set.
   */
  private void setThreadId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    threadId_ = value;
  }
  /**
   * <code>string thread_id = 2 [json_name = "threadId"];</code>
   */
  private void clearThreadId() {

    threadId_ = getDefaultInstance().getThreadId();
  }
  /**
   * <code>string thread_id = 2 [json_name = "threadId"];</code>
   * @param value The bytes for threadId to set.
   */
  private void setThreadIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    threadId_ = value.toStringUtf8();

  }

  public static final int COUNT_FIELD_NUMBER = 3;
  private int count_;
  /**
   * <code>uint32 count = 3 [json_name = "count"];</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }
  /**
   * <code>uint32 count = 3 [json_name = "count"];</code>
   * @param value The count to set.
   */
  private void setCount(int value) {
    
    count_ = value;
  }
  /**
   * <code>uint32 count = 3 [json_name = "count"];</code>
   */
  private void clearCount() {

    count_ = 0;
  }

  public static app.pochical.v1.UnreadCount parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.UnreadCount parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.UnreadCount parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.UnreadCount parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.UnreadCount parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static app.pochical.v1.UnreadCount parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static app.pochical.v1.UnreadCount parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.UnreadCount parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static app.pochical.v1.UnreadCount parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static app.pochical.v1.UnreadCount parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static app.pochical.v1.UnreadCount parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static app.pochical.v1.UnreadCount parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(app.pochical.v1.UnreadCount prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * How many lines of a group's chat the user has not read: others' lines
   * past their read mark. One value per chat, the group's latest.
   * </pre>
   *
   * Protobuf type {@code pochical.v1.UnreadCount}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        app.pochical.v1.UnreadCount, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.UnreadCount)
      app.pochical.v1.UnreadCountOrBuilder {
    // Construct using app.pochical.v1.UnreadCount.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @return The groupId.
     */
    @java.lang.Override
    public java.lang.String getGroupId() {
      return instance.getGroupId();
    }
    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @return The bytes for groupId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      return instance.getGroupIdBytes();
    }
    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(
        java.lang.String value) {
      copyOnWrite();
      instance.setGroupId(value);
      return this;
    }
    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      copyOnWrite();
      instance.clearGroupId();
      return this;
    }
    /**
     * <code>string group_id = 1 [json_name = "groupId"];</code>
     * @param value The bytes for groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGroupIdBytes(value);
      return this;
    }

    /**
     * <code>string thread_id = 2 [json_name = "threadId"];</code>
     * @return The threadId.
     */
    @java.lang.Override
    public java.lang.String getThreadId() {
      return instance.getThreadId();
    }
    /**
     * <code>string thread_id = 2 [json_name = "threadId"];</code>
     * @return The bytes for threadId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getThreadIdBytes() {
      return instance.getThreadIdBytes();
    }
    /**
     * <code>string thread_id = 2 [json_name = "threadId"];</code>
     * @param value The threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadId(
        java.lang.String value) {
      copyOnWrite();
      instance.setThreadId(value);
      return this;
    }
    /**
     * <code>string thread_id = 2 [json_name = "threadId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadId() {
      copyOnWrite();
      instance.clearThreadId();
      return this;
    }
    /**
     * <code>string thread_id = 2 [json_name = "threadId"];</code>
     * @param value The bytes for threadId to set.
     * @return This builder for chaining.
     */
    public Builder setThreadIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setThreadIdBytes(value);
      return this;
    }

    /**
     * <code>uint32 count = 3 [json_name = "count"];</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return instance.getCount();
    }
    /**
     * <code>uint32 count = 3 [json_name = "count"];</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {
      copyOnWrite();
      instance.setCount(value);
      return this;
    }
    /**
     * <code>uint32 count = 3 [json_name = "count"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      copyOnWrite();
      instance.clearCount();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.UnreadCount)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new app.pochical.v1.UnreadCount();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "groupId_",
            "threadId_",
            "count_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u000b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<app.pochical.v1.UnreadCount> parser = PARSER;
        if (parser == null) {
          synchronized (app.pochical.v1.UnreadCount.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<app.pochical.v1.UnreadCount>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.UnreadCount)
  private static final app.pochical.v1.UnreadCount DEFAULT_INSTANCE;
  static {
    UnreadCount defaultInstance = new UnreadCount();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UnreadCount.class, defaultInstance);
  }

  public static app.pochical.v1.UnreadCount getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UnreadCount> PARSER;

  public static com.google.protobuf.Parser<UnreadCount> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

