// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/support.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface UnsendSupportMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.UnsendSupportMessageResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.pochical.v1.SupportMessage message = 1 [json_name = "message"];</code>
   * @return The message.
   */
  app.pochical.v1.SupportMessage getMessage();
}
