// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package app.pochical.v1;

@com.google.protobuf.Generated
public interface WelcomeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.Welcome)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Current head of the DO's change log.
   * </pre>
   *
   * <code>uint64 cursor = 1 [json_name = "cursor"];</code>
   * @return The cursor.
   */
  long getCursor();

  /**
   * <pre>
   * The server's time as it sent Welcome, ms since the Unix epoch: the
   * device corrects its clock by it (spec/sync-protocol.md, HLC).
   * </pre>
   *
   * <code>int64 server_ms = 2 [json_name = "serverMs"];</code>
   * @return The serverMs.
   */
  long getServerMs();
}
