// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package tech.chiji.pochical.v1;

/**
 * <pre>
 * A value as the DO now holds it, at the cursor it got when it last
 * changed.
 * </pre>
 *
 * Protobuf type {@code pochical.v1.Change}
 */
@com.google.protobuf.Generated
public  final class Change extends
    com.google.protobuf.GeneratedMessageLite<
        Change, Change.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.Change)
    ChangeOrBuilder {
  private Change() {
  }
  private int kindCase_ = 0;
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.AbstractMessageLite.InternalOneOfEnum {
    DAY(2),
    PATTERN(3),
    PATTERN_ORDER(4),
    MEMBER_DAY(5),
    MEMBER_PATTERN(6),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 2: return DAY;
        case 3: return PATTERN;
        case 4: return PATTERN_ORDER;
        case 5: return MEMBER_DAY;
        case 6: return MEMBER_PATTERN;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    @java.lang.Override public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  private void clearKind() {
    kindCase_ = 0;
    kind_ = null;
  }

  public static final int CURSOR_FIELD_NUMBER = 1;
  private long cursor_;
  /**
   * <code>uint64 cursor = 1 [json_name = "cursor"];</code>
   * @return The cursor.
   */
  @java.lang.Override
  public long getCursor() {
    return cursor_;
  }
  /**
   * <code>uint64 cursor = 1 [json_name = "cursor"];</code>
   * @param value The cursor to set.
   */
  private void setCursor(long value) {
    
    cursor_ = value;
  }
  /**
   * <code>uint64 cursor = 1 [json_name = "cursor"];</code>
   */
  private void clearCursor() {

    cursor_ = 0L;
  }

  public static final int DAY_FIELD_NUMBER = 2;
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  @java.lang.Override
  public boolean hasDay() {
    return kindCase_ == 2;
  }
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  @java.lang.Override
  public tech.chiji.pochical.v1.DayValue getDay() {
    if (kindCase_ == 2) {
       return (tech.chiji.pochical.v1.DayValue) kind_;
    }
    return tech.chiji.pochical.v1.DayValue.getDefaultInstance();
  }
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  private void setDay(tech.chiji.pochical.v1.DayValue value) {
    java.util.Objects.requireNonNull(value);
    kind_ = value;
    kindCase_ = 2;
  }
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  private void mergeDay(tech.chiji.pochical.v1.DayValue value) {
    java.util.Objects.requireNonNull(value);
    if (kindCase_ == 2 &&
        kind_ != tech.chiji.pochical.v1.DayValue.getDefaultInstance()) {
      kind_ = tech.chiji.pochical.v1.DayValue.newBuilder((tech.chiji.pochical.v1.DayValue) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 2;
  }
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  private void clearDay() {
    if (kindCase_ == 2) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int PATTERN_FIELD_NUMBER = 3;
  /**
   * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
   */
  @java.lang.Override
  public boolean hasPattern() {
    return kindCase_ == 3;
  }
  /**
   * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
   */
  @java.lang.Override
  public tech.chiji.pochical.v1.PatternValue getPattern() {
    if (kindCase_ == 3) {
       return (tech.chiji.pochical.v1.PatternValue) kind_;
    }
    return tech.chiji.pochical.v1.PatternValue.getDefaultInstance();
  }
  /**
   * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
   */
  private void setPattern(tech.chiji.pochical.v1.PatternValue value) {
    java.util.Objects.requireNonNull(value);
    kind_ = value;
    kindCase_ = 3;
  }
  /**
   * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
   */
  private void mergePattern(tech.chiji.pochical.v1.PatternValue value) {
    java.util.Objects.requireNonNull(value);
    if (kindCase_ == 3 &&
        kind_ != tech.chiji.pochical.v1.PatternValue.getDefaultInstance()) {
      kind_ = tech.chiji.pochical.v1.PatternValue.newBuilder((tech.chiji.pochical.v1.PatternValue) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 3;
  }
  /**
   * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
   */
  private void clearPattern() {
    if (kindCase_ == 3) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int PATTERN_ORDER_FIELD_NUMBER = 4;
  /**
   * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
   */
  @java.lang.Override
  public boolean hasPatternOrder() {
    return kindCase_ == 4;
  }
  /**
   * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
   */
  @java.lang.Override
  public tech.chiji.pochical.v1.PatternOrder getPatternOrder() {
    if (kindCase_ == 4) {
       return (tech.chiji.pochical.v1.PatternOrder) kind_;
    }
    return tech.chiji.pochical.v1.PatternOrder.getDefaultInstance();
  }
  /**
   * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
   */
  private void setPatternOrder(tech.chiji.pochical.v1.PatternOrder value) {
    java.util.Objects.requireNonNull(value);
    kind_ = value;
    kindCase_ = 4;
  }
  /**
   * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
   */
  private void mergePatternOrder(tech.chiji.pochical.v1.PatternOrder value) {
    java.util.Objects.requireNonNull(value);
    if (kindCase_ == 4 &&
        kind_ != tech.chiji.pochical.v1.PatternOrder.getDefaultInstance()) {
      kind_ = tech.chiji.pochical.v1.PatternOrder.newBuilder((tech.chiji.pochical.v1.PatternOrder) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 4;
  }
  /**
   * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
   */
  private void clearPatternOrder() {
    if (kindCase_ == 4) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int MEMBER_DAY_FIELD_NUMBER = 5;
  /**
   * <pre>
   * On a Group DO socket: a member's shared days and patterns, as their
   * User DO pushes them (spec/sync-protocol.md, Group projection).
   * </pre>
   *
   * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
   */
  @java.lang.Override
  public boolean hasMemberDay() {
    return kindCase_ == 5;
  }
  /**
   * <pre>
   * On a Group DO socket: a member's shared days and patterns, as their
   * User DO pushes them (spec/sync-protocol.md, Group projection).
   * </pre>
   *
   * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
   */
  @java.lang.Override
  public tech.chiji.pochical.v1.MemberDay getMemberDay() {
    if (kindCase_ == 5) {
       return (tech.chiji.pochical.v1.MemberDay) kind_;
    }
    return tech.chiji.pochical.v1.MemberDay.getDefaultInstance();
  }
  /**
   * <pre>
   * On a Group DO socket: a member's shared days and patterns, as their
   * User DO pushes them (spec/sync-protocol.md, Group projection).
   * </pre>
   *
   * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
   */
  private void setMemberDay(tech.chiji.pochical.v1.MemberDay value) {
    java.util.Objects.requireNonNull(value);
    kind_ = value;
    kindCase_ = 5;
  }
  /**
   * <pre>
   * On a Group DO socket: a member's shared days and patterns, as their
   * User DO pushes them (spec/sync-protocol.md, Group projection).
   * </pre>
   *
   * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
   */
  private void mergeMemberDay(tech.chiji.pochical.v1.MemberDay value) {
    java.util.Objects.requireNonNull(value);
    if (kindCase_ == 5 &&
        kind_ != tech.chiji.pochical.v1.MemberDay.getDefaultInstance()) {
      kind_ = tech.chiji.pochical.v1.MemberDay.newBuilder((tech.chiji.pochical.v1.MemberDay) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 5;
  }
  /**
   * <pre>
   * On a Group DO socket: a member's shared days and patterns, as their
   * User DO pushes them (spec/sync-protocol.md, Group projection).
   * </pre>
   *
   * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
   */
  private void clearMemberDay() {
    if (kindCase_ == 5) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static final int MEMBER_PATTERN_FIELD_NUMBER = 6;
  /**
   * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
   */
  @java.lang.Override
  public boolean hasMemberPattern() {
    return kindCase_ == 6;
  }
  /**
   * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
   */
  @java.lang.Override
  public tech.chiji.pochical.v1.MemberPattern getMemberPattern() {
    if (kindCase_ == 6) {
       return (tech.chiji.pochical.v1.MemberPattern) kind_;
    }
    return tech.chiji.pochical.v1.MemberPattern.getDefaultInstance();
  }
  /**
   * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
   */
  private void setMemberPattern(tech.chiji.pochical.v1.MemberPattern value) {
    java.util.Objects.requireNonNull(value);
    kind_ = value;
    kindCase_ = 6;
  }
  /**
   * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
   */
  private void mergeMemberPattern(tech.chiji.pochical.v1.MemberPattern value) {
    java.util.Objects.requireNonNull(value);
    if (kindCase_ == 6 &&
        kind_ != tech.chiji.pochical.v1.MemberPattern.getDefaultInstance()) {
      kind_ = tech.chiji.pochical.v1.MemberPattern.newBuilder((tech.chiji.pochical.v1.MemberPattern) kind_)
          .mergeFrom(value).buildPartial();
    } else {
      kind_ = value;
    }
    kindCase_ = 6;
  }
  /**
   * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
   */
  private void clearMemberPattern() {
    if (kindCase_ == 6) {
      kindCase_ = 0;
      kind_ = null;
    }
  }

  public static tech.chiji.pochical.v1.Change parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.chiji.pochical.v1.Change parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.Change parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.chiji.pochical.v1.Change parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.Change parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.chiji.pochical.v1.Change parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.Change parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.chiji.pochical.v1.Change parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static tech.chiji.pochical.v1.Change parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static tech.chiji.pochical.v1.Change parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.Change parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.chiji.pochical.v1.Change parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(tech.chiji.pochical.v1.Change prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A value as the DO now holds it, at the cursor it got when it last
   * changed.
   * </pre>
   *
   * Protobuf type {@code pochical.v1.Change}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        tech.chiji.pochical.v1.Change, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.Change)
      tech.chiji.pochical.v1.ChangeOrBuilder {
    // Construct using tech.chiji.pochical.v1.Change.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public KindCase
        getKindCase() {
      return instance.getKindCase();
    }

    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }


    /**
     * <code>uint64 cursor = 1 [json_name = "cursor"];</code>
     * @return The cursor.
     */
    @java.lang.Override
    public long getCursor() {
      return instance.getCursor();
    }
    /**
     * <code>uint64 cursor = 1 [json_name = "cursor"];</code>
     * @param value The cursor to set.
     * @return This builder for chaining.
     */
    public Builder setCursor(long value) {
      copyOnWrite();
      instance.setCursor(value);
      return this;
    }
    /**
     * <code>uint64 cursor = 1 [json_name = "cursor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCursor() {
      copyOnWrite();
      instance.clearCursor();
      return this;
    }

    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    @java.lang.Override
    public boolean hasDay() {
      return instance.hasDay();
    }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    @java.lang.Override
    public tech.chiji.pochical.v1.DayValue getDay() {
      return instance.getDay();
    }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    public Builder setDay(tech.chiji.pochical.v1.DayValue value) {
      copyOnWrite();
      instance.setDay(value);
      return this;
    }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    public Builder setDay(
        tech.chiji.pochical.v1.DayValue.Builder builderForValue) {
      copyOnWrite();
      instance.setDay(builderForValue.build());
      return this;
    }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    public Builder mergeDay(tech.chiji.pochical.v1.DayValue value) {
      copyOnWrite();
      instance.mergeDay(value);
      return this;
    }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    public Builder clearDay() {
      copyOnWrite();
      instance.clearDay();
      return this;
    }

    /**
     * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
     */
    @java.lang.Override
    public boolean hasPattern() {
      return instance.hasPattern();
    }
    /**
     * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
     */
    @java.lang.Override
    public tech.chiji.pochical.v1.PatternValue getPattern() {
      return instance.getPattern();
    }
    /**
     * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
     */
    public Builder setPattern(tech.chiji.pochical.v1.PatternValue value) {
      copyOnWrite();
      instance.setPattern(value);
      return this;
    }
    /**
     * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
     */
    public Builder setPattern(
        tech.chiji.pochical.v1.PatternValue.Builder builderForValue) {
      copyOnWrite();
      instance.setPattern(builderForValue.build());
      return this;
    }
    /**
     * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
     */
    public Builder mergePattern(tech.chiji.pochical.v1.PatternValue value) {
      copyOnWrite();
      instance.mergePattern(value);
      return this;
    }
    /**
     * <code>.pochical.v1.PatternValue pattern = 3 [json_name = "pattern"];</code>
     */
    public Builder clearPattern() {
      copyOnWrite();
      instance.clearPattern();
      return this;
    }

    /**
     * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
     */
    @java.lang.Override
    public boolean hasPatternOrder() {
      return instance.hasPatternOrder();
    }
    /**
     * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
     */
    @java.lang.Override
    public tech.chiji.pochical.v1.PatternOrder getPatternOrder() {
      return instance.getPatternOrder();
    }
    /**
     * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
     */
    public Builder setPatternOrder(tech.chiji.pochical.v1.PatternOrder value) {
      copyOnWrite();
      instance.setPatternOrder(value);
      return this;
    }
    /**
     * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
     */
    public Builder setPatternOrder(
        tech.chiji.pochical.v1.PatternOrder.Builder builderForValue) {
      copyOnWrite();
      instance.setPatternOrder(builderForValue.build());
      return this;
    }
    /**
     * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
     */
    public Builder mergePatternOrder(tech.chiji.pochical.v1.PatternOrder value) {
      copyOnWrite();
      instance.mergePatternOrder(value);
      return this;
    }
    /**
     * <code>.pochical.v1.PatternOrder pattern_order = 4 [json_name = "patternOrder"];</code>
     */
    public Builder clearPatternOrder() {
      copyOnWrite();
      instance.clearPatternOrder();
      return this;
    }

    /**
     * <pre>
     * On a Group DO socket: a member's shared days and patterns, as their
     * User DO pushes them (spec/sync-protocol.md, Group projection).
     * </pre>
     *
     * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
     */
    @java.lang.Override
    public boolean hasMemberDay() {
      return instance.hasMemberDay();
    }
    /**
     * <pre>
     * On a Group DO socket: a member's shared days and patterns, as their
     * User DO pushes them (spec/sync-protocol.md, Group projection).
     * </pre>
     *
     * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
     */
    @java.lang.Override
    public tech.chiji.pochical.v1.MemberDay getMemberDay() {
      return instance.getMemberDay();
    }
    /**
     * <pre>
     * On a Group DO socket: a member's shared days and patterns, as their
     * User DO pushes them (spec/sync-protocol.md, Group projection).
     * </pre>
     *
     * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
     */
    public Builder setMemberDay(tech.chiji.pochical.v1.MemberDay value) {
      copyOnWrite();
      instance.setMemberDay(value);
      return this;
    }
    /**
     * <pre>
     * On a Group DO socket: a member's shared days and patterns, as their
     * User DO pushes them (spec/sync-protocol.md, Group projection).
     * </pre>
     *
     * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
     */
    public Builder setMemberDay(
        tech.chiji.pochical.v1.MemberDay.Builder builderForValue) {
      copyOnWrite();
      instance.setMemberDay(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * On a Group DO socket: a member's shared days and patterns, as their
     * User DO pushes them (spec/sync-protocol.md, Group projection).
     * </pre>
     *
     * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
     */
    public Builder mergeMemberDay(tech.chiji.pochical.v1.MemberDay value) {
      copyOnWrite();
      instance.mergeMemberDay(value);
      return this;
    }
    /**
     * <pre>
     * On a Group DO socket: a member's shared days and patterns, as their
     * User DO pushes them (spec/sync-protocol.md, Group projection).
     * </pre>
     *
     * <code>.pochical.v1.MemberDay member_day = 5 [json_name = "memberDay"];</code>
     */
    public Builder clearMemberDay() {
      copyOnWrite();
      instance.clearMemberDay();
      return this;
    }

    /**
     * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
     */
    @java.lang.Override
    public boolean hasMemberPattern() {
      return instance.hasMemberPattern();
    }
    /**
     * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
     */
    @java.lang.Override
    public tech.chiji.pochical.v1.MemberPattern getMemberPattern() {
      return instance.getMemberPattern();
    }
    /**
     * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
     */
    public Builder setMemberPattern(tech.chiji.pochical.v1.MemberPattern value) {
      copyOnWrite();
      instance.setMemberPattern(value);
      return this;
    }
    /**
     * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
     */
    public Builder setMemberPattern(
        tech.chiji.pochical.v1.MemberPattern.Builder builderForValue) {
      copyOnWrite();
      instance.setMemberPattern(builderForValue.build());
      return this;
    }
    /**
     * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
     */
    public Builder mergeMemberPattern(tech.chiji.pochical.v1.MemberPattern value) {
      copyOnWrite();
      instance.mergeMemberPattern(value);
      return this;
    }
    /**
     * <code>.pochical.v1.MemberPattern member_pattern = 6 [json_name = "memberPattern"];</code>
     */
    public Builder clearMemberPattern() {
      copyOnWrite();
      instance.clearMemberPattern();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.Change)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new tech.chiji.pochical.v1.Change();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "kind_",
            "kindCase_",
            "cursor_",
            tech.chiji.pochical.v1.DayValue.class,
            tech.chiji.pochical.v1.PatternValue.class,
            tech.chiji.pochical.v1.PatternOrder.class,
            tech.chiji.pochical.v1.MemberDay.class,
            tech.chiji.pochical.v1.MemberPattern.class,
          };
          java.lang.String info =
              "\u0000\u0006\u0001\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0003\u0002<\u0000" +
              "\u0003<\u0000\u0004<\u0000\u0005<\u0000\u0006<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<tech.chiji.pochical.v1.Change> parser = PARSER;
        if (parser == null) {
          synchronized (tech.chiji.pochical.v1.Change.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<tech.chiji.pochical.v1.Change>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.Change)
  private static final tech.chiji.pochical.v1.Change DEFAULT_INSTANCE;
  static {
    Change defaultInstance = new Change();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Change.class, defaultInstance);
  }

  public static tech.chiji.pochical.v1.Change getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Change> PARSER;

  public static com.google.protobuf.Parser<Change> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

