// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package tech.chiji.pochical.v1;

/**
 * Protobuf type {@code pochical.v1.Changes}
 */
@com.google.protobuf.Generated
public  final class Changes extends
    com.google.protobuf.GeneratedMessageLite<
        Changes, Changes.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.Changes)
    ChangesOrBuilder {
  private Changes() {
    changes_ = emptyProtobufList();
  }
  public static final int CHANGES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<tech.chiji.pochical.v1.Change> changes_;
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  @java.lang.Override
  public java.util.List<tech.chiji.pochical.v1.Change> getChangesList() {
    return changes_;
  }
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  public java.util.List<? extends tech.chiji.pochical.v1.ChangeOrBuilder> 
      getChangesOrBuilderList() {
    return changes_;
  }
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  @java.lang.Override
  public int getChangesCount() {
    return changes_.size();
  }
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  @java.lang.Override
  public tech.chiji.pochical.v1.Change getChanges(int index) {
    return changes_.get(index);
  }
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  public tech.chiji.pochical.v1.ChangeOrBuilder getChangesOrBuilder(
      int index) {
    return changes_.get(index);
  }
  private void ensureChangesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<tech.chiji.pochical.v1.Change> tmp = changes_;
    if (!tmp.isModifiable()) {
      changes_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  private void setChanges(
      int index, tech.chiji.pochical.v1.Change value) {
    java.util.Objects.requireNonNull(value);
    ensureChangesIsMutable();
    changes_.set(index, value);
  }
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  private void addChanges(tech.chiji.pochical.v1.Change value) {
    java.util.Objects.requireNonNull(value);
    ensureChangesIsMutable();
    changes_.add(value);
  }
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  private void addChanges(
      int index, tech.chiji.pochical.v1.Change value) {
    java.util.Objects.requireNonNull(value);
    ensureChangesIsMutable();
    changes_.add(index, value);
  }
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  private void addAllChanges(
      java.lang.Iterable<? extends tech.chiji.pochical.v1.Change> values) {
    ensureChangesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, changes_);
  }
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  private void clearChanges() {
    changes_ = emptyProtobufList();
  }
  /**
   * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
   */
  private void removeChanges(int index) {
    ensureChangesIsMutable();
    changes_.remove(index);
  }

  public static tech.chiji.pochical.v1.Changes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.chiji.pochical.v1.Changes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.Changes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.chiji.pochical.v1.Changes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.Changes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.chiji.pochical.v1.Changes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.Changes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.chiji.pochical.v1.Changes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static tech.chiji.pochical.v1.Changes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static tech.chiji.pochical.v1.Changes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.Changes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.chiji.pochical.v1.Changes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(tech.chiji.pochical.v1.Changes prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code pochical.v1.Changes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        tech.chiji.pochical.v1.Changes, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.Changes)
      tech.chiji.pochical.v1.ChangesOrBuilder {
    // Construct using tech.chiji.pochical.v1.Changes.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    @java.lang.Override
    public java.util.List<tech.chiji.pochical.v1.Change> getChangesList() {
      return java.util.Collections.unmodifiableList(
          instance.getChangesList());
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    @java.lang.Override
    public int getChangesCount() {
      return instance.getChangesCount();
    }/**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    @java.lang.Override
    public tech.chiji.pochical.v1.Change getChanges(int index) {
      return instance.getChanges(index);
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    public Builder setChanges(
        int index, tech.chiji.pochical.v1.Change value) {
      copyOnWrite();
      instance.setChanges(index, value);
      return this;
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    public Builder setChanges(
        int index, tech.chiji.pochical.v1.Change.Builder builderForValue) {
      copyOnWrite();
      instance.setChanges(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    public Builder addChanges(tech.chiji.pochical.v1.Change value) {
      copyOnWrite();
      instance.addChanges(value);
      return this;
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    public Builder addChanges(
        int index, tech.chiji.pochical.v1.Change value) {
      copyOnWrite();
      instance.addChanges(index, value);
      return this;
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    public Builder addChanges(
        tech.chiji.pochical.v1.Change.Builder builderForValue) {
      copyOnWrite();
      instance.addChanges(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    public Builder addChanges(
        int index, tech.chiji.pochical.v1.Change.Builder builderForValue) {
      copyOnWrite();
      instance.addChanges(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    public Builder addAllChanges(
        java.lang.Iterable<? extends tech.chiji.pochical.v1.Change> values) {
      copyOnWrite();
      instance.addAllChanges(values);
      return this;
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    public Builder clearChanges() {
      copyOnWrite();
      instance.clearChanges();
      return this;
    }
    /**
     * <code>repeated .pochical.v1.Change changes = 1 [json_name = "changes"];</code>
     */
    public Builder removeChanges(int index) {
      copyOnWrite();
      instance.removeChanges(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.Changes)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new tech.chiji.pochical.v1.Changes();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "changes_",
            tech.chiji.pochical.v1.Change.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<tech.chiji.pochical.v1.Changes> parser = PARSER;
        if (parser == null) {
          synchronized (tech.chiji.pochical.v1.Changes.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<tech.chiji.pochical.v1.Changes>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.Changes)
  private static final tech.chiji.pochical.v1.Changes DEFAULT_INSTANCE;
  static {
    Changes defaultInstance = new Changes();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Changes.class, defaultInstance);
  }

  public static tech.chiji.pochical.v1.Changes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Changes> PARSER;

  public static com.google.protobuf.Parser<Changes> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

