// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package tech.chiji.pochical.v1;

@com.google.protobuf.Generated
public interface DayEditsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.DayEdits)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .pochical.v1.DayEdit edits = 1 [json_name = "edits"];</code>
   */
  java.util.List<tech.chiji.pochical.v1.DayEdit> 
      getEditsList();
  /**
   * <code>repeated .pochical.v1.DayEdit edits = 1 [json_name = "edits"];</code>
   */
  tech.chiji.pochical.v1.DayEdit getEdits(int index);
  /**
   * <code>repeated .pochical.v1.DayEdit edits = 1 [json_name = "edits"];</code>
   */
  int getEditsCount();
}
