// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package tech.chiji.pochical.v1;

@com.google.protobuf.Generated
public interface HlcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pochical.v1.Hlc)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 physical_ms = 1 [json_name = "physicalMs"];</code>
   * @return The physicalMs.
   */
  long getPhysicalMs();

  /**
   * <code>uint32 counter = 2 [json_name = "counter"];</code>
   * @return The counter.
   */
  int getCounter();

  /**
   * <code>string device_id = 3 [json_name = "deviceId"];</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 3 [json_name = "deviceId"];</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();
}
