// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pochical/v1/sync.proto
// Protobuf Java Version: 4.36.2

package tech.chiji.pochical.v1;

/**
 * <pre>
 * One field of a member's day, as the group sees it: pattern and times,
 * never the memo.
 * </pre>
 *
 * Protobuf type {@code pochical.v1.MemberDay}
 */
@com.google.protobuf.Generated
public  final class MemberDay extends
    com.google.protobuf.GeneratedMessageLite<
        MemberDay, MemberDay.Builder> implements
    // @@protoc_insertion_point(message_implements:pochical.v1.MemberDay)
    MemberDayOrBuilder {
  private MemberDay() {
    userId_ = "";
  }
  private int bitField0_;
  public static final int USER_ID_FIELD_NUMBER = 1;
  private java.lang.String userId_;
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @param value The userId to set.
   */
  private void setUserId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    userId_ = value;
  }
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   */
  private void clearUserId() {

    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();

  }

  public static final int DAY_FIELD_NUMBER = 2;
  private tech.chiji.pochical.v1.DayValue day_;
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  @java.lang.Override
  public boolean hasDay() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  @java.lang.Override
  public tech.chiji.pochical.v1.DayValue getDay() {
    return day_ == null ? tech.chiji.pochical.v1.DayValue.getDefaultInstance() : day_;
  }
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  private void setDay(tech.chiji.pochical.v1.DayValue value) {
    java.util.Objects.requireNonNull(value);
    day_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeDay(tech.chiji.pochical.v1.DayValue value) {
    java.util.Objects.requireNonNull(value);
    if (day_ != null &&
        day_ != tech.chiji.pochical.v1.DayValue.getDefaultInstance()) {
      day_ =
        tech.chiji.pochical.v1.DayValue.newBuilder(day_).mergeFrom(value).buildPartial();
    } else {
      day_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
   */
  private void clearDay() {
    day_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static tech.chiji.pochical.v1.MemberDay parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.chiji.pochical.v1.MemberDay parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.MemberDay parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.chiji.pochical.v1.MemberDay parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.MemberDay parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.chiji.pochical.v1.MemberDay parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.MemberDay parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.chiji.pochical.v1.MemberDay parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static tech.chiji.pochical.v1.MemberDay parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static tech.chiji.pochical.v1.MemberDay parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static tech.chiji.pochical.v1.MemberDay parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.chiji.pochical.v1.MemberDay parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(tech.chiji.pochical.v1.MemberDay prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * One field of a member's day, as the group sees it: pattern and times,
   * never the memo.
   * </pre>
   *
   * Protobuf type {@code pochical.v1.MemberDay}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        tech.chiji.pochical.v1.MemberDay, Builder> implements
      // @@protoc_insertion_point(builder_implements:pochical.v1.MemberDay)
      tech.chiji.pochical.v1.MemberDayOrBuilder {
    // Construct using tech.chiji.pochical.v1.MemberDay.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    @java.lang.Override
    public boolean hasDay() {
      return instance.hasDay();
    }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    @java.lang.Override
    public tech.chiji.pochical.v1.DayValue getDay() {
      return instance.getDay();
    }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    public Builder setDay(tech.chiji.pochical.v1.DayValue value) {
      copyOnWrite();
      instance.setDay(value);
      return this;
      }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    public Builder setDay(
        tech.chiji.pochical.v1.DayValue.Builder builderForValue) {
      copyOnWrite();
      instance.setDay(builderForValue.build());
      return this;
    }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    public Builder mergeDay(tech.chiji.pochical.v1.DayValue value) {
      copyOnWrite();
      instance.mergeDay(value);
      return this;
    }
    /**
     * <code>.pochical.v1.DayValue day = 2 [json_name = "day"];</code>
     */
    public Builder clearDay() {  copyOnWrite();
      instance.clearDay();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:pochical.v1.MemberDay)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new tech.chiji.pochical.v1.MemberDay();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "userId_",
            "day_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<tech.chiji.pochical.v1.MemberDay> parser = PARSER;
        if (parser == null) {
          synchronized (tech.chiji.pochical.v1.MemberDay.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<tech.chiji.pochical.v1.MemberDay>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:pochical.v1.MemberDay)
  private static final tech.chiji.pochical.v1.MemberDay DEFAULT_INSTANCE;
  static {
    MemberDay defaultInstance = new MemberDay();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MemberDay.class, defaultInstance);
  }

  public static tech.chiji.pochical.v1.MemberDay getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MemberDay> PARSER;

  public static com.google.protobuf.Parser<MemberDay> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

