// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: pochical/v1/user.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// The signed-in user. Every call here needs the session token from
/// better-auth (/api/auth) as `Authorization: Bearer <token>`; without a
/// valid one it fails with UNAUTHENTICATED.
public protocol Pochical_V1_UserServiceClientInterface: Sendable {

    /// Deletes the user's account and everything of it (spec/sync-protocol.md,
    /// Deleting an account): their own values, their place in each group with
    /// every line they wrote taken back, their chat with Pochical's people,
    /// and their sign-ins. A user linked to Sign in with Apple sends a fresh
    /// authorization code, with which the server revokes the app's Apple
    /// tokens as Apple asks; FAILED_PRECONDITION without one Apple takes.
    @available(iOS 13, *)
    func `deleteAccount`(request: Pochical_V1_DeleteAccountRequest, headers: Connect.Headers) async -> ResponseMessage<Pochical_V1_DeleteAccountResponse>

    /// Who the token belongs to, for the apps to check a stored session.
    @available(iOS 13, *)
    func `getMe`(request: Pochical_V1_GetMeRequest, headers: Connect.Headers) async -> ResponseMessage<Pochical_V1_GetMeResponse>

    /// Blocks someone in every group the two share, or unblocks them
    /// (spec/chat.md, Reporting and blocking); their devices hear of it as a
    /// Block change. Blocking oneself is INVALID_ARGUMENT.
    @available(iOS 13, *)
    func `setBlocked`(request: Pochical_V1_SetBlockedRequest, headers: Connect.Headers) async -> ResponseMessage<Pochical_V1_SetBlockedResponse>

    /// Keeps a device's push token for the user's notifications (spec/chat.md,
    /// Notifications); sent each launch, as iOS may change it.
    @available(iOS 13, *)
    func `registerPushToken`(request: Pochical_V1_RegisterPushTokenRequest, headers: Connect.Headers) async -> ResponseMessage<Pochical_V1_RegisterPushTokenResponse>

    /// Turns a chat's notifications off or on again (spec/chat.md,
    /// Notifications); the user's devices hear of it as a ChatMute change.
    /// NOT_FOUND for a group the user is not in or a chat not theirs.
    @available(iOS 13, *)
    func `setChatMuted`(request: Pochical_V1_SetChatMutedRequest, headers: Connect.Headers) async -> ResponseMessage<Pochical_V1_SetChatMutedResponse>

    /// Sets メンションはいつも通知 for the account; the devices hear of it as a
    /// ChatNotifications change.
    @available(iOS 13, *)
    func `setChatNotifications`(request: Pochical_V1_SetChatNotificationsRequest, headers: Connect.Headers) async -> ResponseMessage<Pochical_V1_SetChatNotificationsResponse>
}

/// Concrete implementation of `Pochical_V1_UserServiceClientInterface`.
public final class Pochical_V1_UserServiceClient: Pochical_V1_UserServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `deleteAccount`(request: Pochical_V1_DeleteAccountRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Pochical_V1_DeleteAccountResponse> {
        return await self.client.unary(path: "/pochical.v1.UserService/DeleteAccount", idempotencyLevel: .idempotent, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `getMe`(request: Pochical_V1_GetMeRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Pochical_V1_GetMeResponse> {
        return await self.client.unary(path: "/pochical.v1.UserService/GetMe", idempotencyLevel: .noSideEffects, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `setBlocked`(request: Pochical_V1_SetBlockedRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Pochical_V1_SetBlockedResponse> {
        return await self.client.unary(path: "/pochical.v1.UserService/SetBlocked", idempotencyLevel: .idempotent, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `registerPushToken`(request: Pochical_V1_RegisterPushTokenRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Pochical_V1_RegisterPushTokenResponse> {
        return await self.client.unary(path: "/pochical.v1.UserService/RegisterPushToken", idempotencyLevel: .idempotent, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `setChatMuted`(request: Pochical_V1_SetChatMutedRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Pochical_V1_SetChatMutedResponse> {
        return await self.client.unary(path: "/pochical.v1.UserService/SetChatMuted", idempotencyLevel: .idempotent, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `setChatNotifications`(request: Pochical_V1_SetChatNotificationsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Pochical_V1_SetChatNotificationsResponse> {
        return await self.client.unary(path: "/pochical.v1.UserService/SetChatNotifications", idempotencyLevel: .idempotent, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let deleteAccount = Connect.MethodSpec(name: "DeleteAccount", service: "pochical.v1.UserService", type: .unary)
            public static let getMe = Connect.MethodSpec(name: "GetMe", service: "pochical.v1.UserService", type: .unary)
            public static let setBlocked = Connect.MethodSpec(name: "SetBlocked", service: "pochical.v1.UserService", type: .unary)
            public static let registerPushToken = Connect.MethodSpec(name: "RegisterPushToken", service: "pochical.v1.UserService", type: .unary)
            public static let setChatMuted = Connect.MethodSpec(name: "SetChatMuted", service: "pochical.v1.UserService", type: .unary)
            public static let setChatNotifications = Connect.MethodSpec(name: "SetChatNotifications", service: "pochical.v1.UserService", type: .unary)
        }
    }
}
