// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: pochical/v1/user.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// The signed-in user. Every call here needs the session token from
/// better-auth (/api/auth) as `Authorization: Bearer <token>`; without a
/// valid one it fails with UNAUTHENTICATED.
public protocol Pochical_V1_UserServiceClientInterface: Sendable {

    /// Who the token belongs to, for the apps to check a stored session.
    @available(iOS 13, *)
    func `getMe`(request: Pochical_V1_GetMeRequest, headers: Connect.Headers) async -> ResponseMessage<Pochical_V1_GetMeResponse>

    /// Blocks someone in every group the two share, or unblocks them
    /// (spec/chat.md, Reporting and blocking); their devices hear of it as a
    /// Block change. Blocking oneself is INVALID_ARGUMENT.
    @available(iOS 13, *)
    func `setBlocked`(request: Pochical_V1_SetBlockedRequest, headers: Connect.Headers) async -> ResponseMessage<Pochical_V1_SetBlockedResponse>

    /// Keeps a device's push token for the user's notifications (spec/chat.md,
    /// Notifications); sent each launch, as iOS may change it.
    @available(iOS 13, *)
    func `registerPushToken`(request: Pochical_V1_RegisterPushTokenRequest, headers: Connect.Headers) async -> ResponseMessage<Pochical_V1_RegisterPushTokenResponse>
}

/// Concrete implementation of `Pochical_V1_UserServiceClientInterface`.
public final class Pochical_V1_UserServiceClient: Pochical_V1_UserServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `getMe`(request: Pochical_V1_GetMeRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Pochical_V1_GetMeResponse> {
        return await self.client.unary(path: "/pochical.v1.UserService/GetMe", idempotencyLevel: .noSideEffects, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `setBlocked`(request: Pochical_V1_SetBlockedRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Pochical_V1_SetBlockedResponse> {
        return await self.client.unary(path: "/pochical.v1.UserService/SetBlocked", idempotencyLevel: .idempotent, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `registerPushToken`(request: Pochical_V1_RegisterPushTokenRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Pochical_V1_RegisterPushTokenResponse> {
        return await self.client.unary(path: "/pochical.v1.UserService/RegisterPushToken", idempotencyLevel: .idempotent, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let getMe = Connect.MethodSpec(name: "GetMe", service: "pochical.v1.UserService", type: .unary)
            public static let setBlocked = Connect.MethodSpec(name: "SetBlocked", service: "pochical.v1.UserService", type: .unary)
            public static let registerPushToken = Connect.MethodSpec(name: "RegisterPushToken", service: "pochical.v1.UserService", type: .unary)
        }
    }
}
