// Phrases.swift: BudouX, which the site runs on every Japanese string
// (apps/web/src/jsx), for the iOS app. SwiftUI breaks Japanese in the middle
// of a word (見えるよう／になります), and has nothing like CSS's keep-all, so
// a phrase's letters are joined by WORD JOINER instead. Android breaks
// between phrases itself (LineBreak.WordBreak.Phrase in the text styles).
import { jaModel } from "budoux";

const MODEL_DOC =
  "BudouX's Japanese model (https://github.com/google/budoux, Apache License 2.0), as the site's.";

export const swiftPhrases = (): string[] => [
  "import Foundation",
  "import SwiftUI",
  "",
  "/// Japanese broken between phrases, never in the middle of a word, as the",
  "/// site breaks it: BudouX finds the phrases.",
  "public enum Phrases {",
  `  /// ${MODEL_DOC}`,
  `  private static let modelJSON = #"${JSON.stringify(jaModel)}"#`,
  "",
  "  private static let model: [String: [String: Int]] = {",
  "    guard",
  "      let model = try? JSONDecoder().decode(",
  "        [String: [String: Int]].self, from: Data(modelJSON.utf8))",
  '    else { preconditionFailure("BudouX model") }',
  "    return model",
  "  }()",
  "",
  "  private static let baseScore: Double =",
  "    -0.5 * Double(model.values.flatMap(\\.values).reduce(0, +))",
  "",
  "  /// The text's phrases, in order; together they are the text.",
  "  public static func split(_ text: String) -> [String] {",
  "    let letters = text.map(String.init)",
  "    guard letters.count > 1 else { return [text] }",
  "    // The letters from `from` to `to`, cut to the text as JavaScript's",
  "    // substring cuts them, so the scores match the site's.",
  "    func score(_ feature: String, _ from: Int, _ to: Int) -> Double {",
  "      let start = min(max(from, 0), letters.count)",
  "      let end = min(max(to, 0), letters.count)",
  "      let key = letters[start..<max(start, end)].joined()",
  "      return Double(model[feature]?[key] ?? 0)",
  "    }",
  "    var phrases: [String] = []",
  "    var phrase = letters[0]",
  "    for index in 1..<letters.count {",
  "      let total =",
  "        baseScore",
  '        + score("UW1", index - 3, index - 2)',
  '        + score("UW2", index - 2, index - 1)',
  '        + score("UW3", index - 1, index)',
  '        + score("UW4", index, index + 1)',
  '        + score("UW5", index + 1, index + 2)',
  '        + score("UW6", index + 2, index + 3)',
  '        + score("BW1", index - 2, index)',
  '        + score("BW2", index - 1, index + 1)',
  '        + score("BW3", index, index + 2)',
  '        + score("TW1", index - 3, index)',
  '        + score("TW2", index - 2, index + 1)',
  '        + score("TW3", index - 1, index + 2)',
  '        + score("TW4", index, index + 3)',
  "      if total > 0 {",
  "        phrases.append(phrase)",
  '        phrase = ""',
  "      }",
  "      phrase += letters[index]",
  "    }",
  "    phrases.append(phrase)",
  "    return phrases",
  "  }",
  "",
  "  static func hasJapanese(_ text: String) -> Bool {",
  "    text.unicodeScalars.contains { scalar in",
  "      switch scalar.value {",
  "      // Hiragana, katakana, and the CJK ideographs.",
  "      case 0x3040...0x30FF, 0x3400...0x4DBF, 0x4E00...0x9FFF, 0xF900...0xFAFF: true",
  "      default: false",
  "      }",
  "    }",
  "  }",
  "}",
  "",
  "extension String {",
  "  /// This text for showing, with each Japanese phrase kept whole on a line:",
  "  /// a WORD JOINER (U+2060), which nothing draws, between a phrase's",
  "  /// letters, so a line breaks only between phrases. A phrase too long for",
  "  /// its line still breaks. Keep the text itself as it is; only show this.",
  "  public var phrased: String {",
  "    guard Phrases.hasJapanese(self) else { return self }",
  "    return Phrases.split(self)",
  '      .map { phrase in phrase.map(String.init).joined(separator: "\\u{2060}") }',
  "      .joined()",
  "  }",
  "}",
  "",
  "extension Text {",
  "  /// Text whose Japanese breaks between phrases (String.phrased).",
  "  public init(phrased text: String) {",
  "    self.init(verbatim: text.phrased)",
  "  }",
  "}",
];
