// Code generated from design/ by `mise run gen`. Do not edit.

package app.pochical.design

/** The marks' icons by name, in words, and in the kinds the icon picker sheet sorts them into (design/src/mark-icon-names.ts). */
object MarkIconNames {
  data class Section(val title: String, val icons: List<String>)

  val names: Map<String, String> = mapOf(
    "alarm" to "目覚まし時計",
    "ambulance" to "救急車",
    "baby" to "赤ちゃん",
    "babyCarriage" to "ベビーカー",
    "backpack" to "リュック",
    "balloon" to "風船",
    "bandaids" to "ばんそうこう",
    "bank" to "銀行",
    "baseball" to "野球",
    "basket" to "かご",
    "basketball" to "バスケットボール",
    "bath" to "お風呂",
    "bed" to "ベッド",
    "beer" to "ビール",
    "bell" to "ベル",
    "bicycle" to "自転車",
    "bird" to "鳥",
    "boat" to "船",
    "book" to "本",
    "books" to "本棚",
    "bread" to "パン",
    "briefcase" to "かばん",
    "broom" to "ほうき",
    "building" to "ビル",
    "bus" to "バス",
    "cake" to "ケーキ",
    "calculator" to "電卓",
    "calendarCheck" to "予定",
    "calendarHeart" to "記念日",
    "camera" to "カメラ",
    "car" to "車",
    "cashRegister" to "レジ",
    "cat" to "猫",
    "chart" to "グラフ",
    "chefHat" to "コック帽",
    "clock" to "時計",
    "cloud" to "雲",
    "cloudMoon" to "夜空",
    "cloudSun" to "晴れ",
    "code" to "コード",
    "coffee" to "コーヒー",
    "coins" to "お金",
    "cookingPot" to "鍋",
    "couch" to "ソファ",
    "desktop" to "デスクトップ",
    "dog" to "犬",
    "dumbbell" to "運動",
    "envelope" to "封筒",
    "eyeglasses" to "めがね",
    "factory" to "工場",
    "film" to "映画",
    "fireExtinguisher" to "消火器",
    "fireTruck" to "消防車",
    "firstAid" to "救急箱",
    "fish" to "魚",
    "flower" to "花",
    "folder" to "フォルダ",
    "game" to "ゲーム",
    "gasPump" to "給油",
    "gift" to "プレゼント",
    "graduationCap" to "学位帽",
    "guitar" to "ギター",
    "hammer" to "ハンマー",
    "handHeart" to "手とハート",
    "handshake" to "握手",
    "hardHat" to "ヘルメット",
    "headset" to "ヘッドセット",
    "heart" to "ハート",
    "heartbeat" to "心拍",
    "hospital" to "病院",
    "hourglass" to "砂時計",
    "house" to "家",
    "iceCream" to "アイス",
    "idBadge" to "社員証",
    "island" to "島",
    "laptop" to "パソコン",
    "leaf" to "葉っぱ",
    "letter" to "文字アイコン",
    "lightbulb" to "電球",
    "lightning" to "雷",
    "mapPin" to "地図のピン",
    "megaphone" to "メガホン",
    "microphone" to "マイク",
    "microscope" to "顕微鏡",
    "moon" to "月",
    "moonStar" to "月と星",
    "motorcycle" to "バイク",
    "mountains" to "山",
    "music" to "音楽",
    "needle" to "針",
    "notebook" to "ノート",
    "package" to "荷物",
    "paintBrush" to "筆",
    "palette" to "パレット",
    "partyPopper" to "お祝い",
    "pawPrint" to "足あと",
    "pen" to "ペン",
    "pencil" to "鉛筆",
    "phone" to "電話",
    "pill" to "薬",
    "plane" to "飛行機",
    "policeCar" to "パトカー",
    "popcorn" to "ポップコーン",
    "pottedPlant" to "観葉植物",
    "presentation" to "プレゼン",
    "printer" to "プリンター",
    "rabbit" to "うさぎ",
    "rain" to "雨",
    "rainbow" to "虹",
    "run" to "ランニング",
    "scales" to "天びん",
    "scissors" to "はさみ",
    "shield" to "盾",
    "shieldCheck" to "安全",
    "shoppingBag" to "買い物",
    "shoppingCart" to "カート",
    "siren" to "サイレン",
    "smiley" to "笑顔",
    "sneaker" to "スニーカー",
    "snow" to "雪",
    "soccer" to "サッカー",
    "star" to "星",
    "stethoscope" to "聴診器",
    "storefront" to "お店",
    "subway" to "地下鉄",
    "suitcase" to "スーツケース",
    "sun" to "太陽",
    "sunHorizon" to "地平線の太陽",
    "sunglasses" to "サングラス",
    "swim" to "水泳",
    "syringe" to "注射器",
    "tShirt" to "Tシャツ",
    "taxi" to "タクシー",
    "teacher" to "先生",
    "tennis" to "テニス",
    "tent" to "テント",
    "ticket" to "チケット",
    "timer" to "タイマー",
    "tooth" to "歯",
    "tractor" to "トラクター",
    "train" to "電車",
    "translate" to "語学",
    "tree" to "木",
    "treePalm" to "ヤシの木",
    "trophy" to "トロフィー",
    "truck" to "トラック",
    "users" to "人たち",
    "utensils" to "食事",
    "van" to "ワゴン車",
    "videoCamera" to "ビデオカメラ",
    "warehouse" to "倉庫",
    "washingMachine" to "洗濯機",
    "wheelchair" to "車いす",
    "wine" to "ワイン",
    "wrench" to "工具",
  )

  val words: Map<String, String> = mapOf(
    "alarm" to "早起き 朝",
    "ambulance" to "救急 救命",
    "baby" to "保育 育児 子ども",
    "babyCarriage" to "保育 育児 散歩",
    "backpack" to "通学 遠足 学校",
    "balloon" to "お祝い イベント 誕生日",
    "bandaids" to "けが 処置",
    "bank" to "金融 窓口",
    "baseball" to "部活",
    "basket" to "スーパー 品出し 買い物",
    "basketball" to "部活",
    "bath" to "温泉 銭湯",
    "bed" to "非番 睡眠 寝る",
    "beer" to "飲み会 居酒屋 お酒",
    "bell" to "ナースコール 呼び出し",
    "bicycle" to "配達 通勤",
    "boat" to "フェリー 釣り",
    "book" to "研修 勉強 講習",
    "books" to "図書館 読書 勉強",
    "bread" to "パン屋 ベーカリー",
    "briefcase" to "仕事 出勤 出張",
    "broom" to "清掃 掃除",
    "building" to "会社 オフィス 事務所",
    "bus" to "通勤 送迎",
    "cake" to "誕生日 記念日 お祝い",
    "calculator" to "経理 会計 計算",
    "calendarCheck" to "用事",
    "calendarHeart" to "デート",
    "camera" to "写真 撮影",
    "car" to "運転 ドライブ 外回り",
    "cashRegister" to "会計 販売",
    "cat" to "ペット",
    "chart" to "営業 分析 数字",
    "chefHat" to "調理 料理人 キッチン 厨房",
    "clock" to "残業 時短 時間",
    "cloud" to "曇り",
    "cloudMoon" to "遅番 準夜 夕方 夜",
    "cloudSun" to "早番 朝",
    "code" to "エンジニア プログラミング 開発",
    "coffee" to "休憩 カフェ 喫茶",
    "coins" to "給料 経理",
    "cookingPot" to "調理 料理 給食",
    "couch" to "休み のんびり",
    "desktop" to "事務 デスクワーク",
    "dog" to "ペット 散歩",
    "dumbbell" to "ジム 筋トレ",
    "envelope" to "メール 郵便 手紙",
    "eyeglasses" to "眼科",
    "factory" to "製造 ライン",
    "film" to "動画",
    "fireExtinguisher" to "防災 訓練",
    "fireTruck" to "消防 消防士",
    "firstAid" to "救急 保健室",
    "fish" to "釣り 水族館",
    "flower" to "有休 有給 年休",
    "folder" to "書類 事務",
    "game" to "遊び",
    "gasPump" to "ガソリンスタンド",
    "gift" to "誕生日",
    "graduationCap" to "学校 卒業 大学",
    "guitar" to "バンド 楽器",
    "hammer" to "大工 建設 工事",
    "handHeart" to "介護 ケア 福祉 ボランティア",
    "handshake" to "商談 営業 契約 面接",
    "hardHat" to "建設 工事 現場",
    "headset" to "コールセンター 窓口 受付",
    "heart" to "デート 好き",
    "heartbeat" to "心電図 モニター",
    "hospital" to "病棟 看護 クリニック",
    "hourglass" to "待ち時間",
    "house" to "在宅 自宅",
    "iceCream" to "おやつ デザート",
    "idBadge" to "受付 出勤",
    "island" to "旅行",
    "laptop" to "在宅 リモート テレワーク",
    "leaf" to "休み 公休",
    "lightbulb" to "企画 アイデア",
    "lightning" to "いなずま",
    "mapPin" to "お出かけ 外出 場所",
    "megaphone" to "宣伝 広報 イベント",
    "microphone" to "カラオケ 歌 ライブ",
    "microscope" to "研究 検査 実験",
    "moon" to "夜勤 夜",
    "moonStar" to "深夜 夜",
    "motorcycle" to "配達",
    "mountains" to "登山 ハイキング",
    "music" to "ライブ 習い事",
    "needle" to "裁縫 縫製",
    "notebook" to "授業 勉強",
    "package" to "倉庫 仕分け 発送",
    "paintBrush" to "美術 塗装 デザイン",
    "palette" to "絵 美術 習い事",
    "partyPopper" to "パーティー イベント 飲み会",
    "pawPrint" to "ペット 動物",
    "pen" to "書類 記録",
    "pencil" to "勉強 宿題 試験",
    "phone" to "待機 オンコール 電話番",
    "pill" to "薬局 薬剤師 服薬",
    "plane" to "出張 旅行 空港",
    "policeCar" to "警察 警察官 パトロール",
    "popcorn" to "映画",
    "pottedPlant" to "植物",
    "presentation" to "発表 会議",
    "printer" to "印刷 事務",
    "rabbit" to "ペット",
    "rain" to "天気",
    "run" to "マラソン ジョギング 運動",
    "scales" to "法律 弁護士 裁判",
    "scissors" to "美容 美容師 理容 カット",
    "shield" to "警備 警察 守衛",
    "shieldCheck" to "警備 セキュリティ",
    "shoppingBag" to "ショッピング",
    "shoppingCart" to "買い物 スーパー",
    "siren" to "当番 当直 緊急 消防",
    "smiley" to "楽しい",
    "sneaker" to "散歩 ウォーキング",
    "snow" to "冬",
    "soccer" to "部活",
    "stethoscope" to "医師 看護 診察",
    "storefront" to "店 店舗 販売 コンビニ",
    "subway" to "通勤",
    "suitcase" to "旅行 帰省 出張",
    "sun" to "日勤 昼",
    "sunHorizon" to "明け 夕勤 朝 夕方 日の出 夕日",
    "sunglasses" to "夏 海",
    "swim" to "プール",
    "syringe" to "注射 ワクチン 採血",
    "tShirt" to "アパレル 服 洋服",
    "taxi" to "運転",
    "teacher" to "教師 講師 塾 学校",
    "tennis" to "部活",
    "tent" to "キャンプ アウトドア",
    "ticket" to "ライブ コンサート 観劇",
    "timer" to "時間",
    "tooth" to "歯科 歯医者",
    "tractor" to "農業 畑",
    "train" to "鉄道 通勤 駅",
    "translate" to "英語 英会話",
    "tree" to "公園 自然",
    "treePalm" to "旅行 休暇 バカンス",
    "trophy" to "大会 試合 優勝",
    "truck" to "配送 配達 物流 運送",
    "users" to "会議 ミーティング 打ち合わせ",
    "utensils" to "飲食 レストラン ランチ ごはん",
    "van" to "送迎 配達",
    "videoCamera" to "オンライン会議 撮影 配信",
    "warehouse" to "物流 ピッキング",
    "washingMachine" to "洗濯 家事",
    "wheelchair" to "介助 介護",
    "wine" to "飲み会 ディナー お酒",
    "wrench" to "整備 修理 工場",
  )

  val sections: List<Section> = listOf(
    Section("空と時間", listOf("sunHorizon", "cloudSun", "sun", "cloudMoon", "moon", "moonStar", "star", "clock", "cloud", "rain", "snow", "rainbow", "lightning", "alarm", "hourglass", "timer")),
    Section("休み・お出かけ", listOf("leaf", "flower", "bed", "couch", "coffee", "treePalm", "heart", "bath", "tent", "mountains", "island", "suitcase", "camera", "film", "ticket", "popcorn", "tree", "pottedPlant", "sunglasses", "mapPin", "iceCream", "sneaker", "smiley")),
    Section("仕事", listOf("briefcase", "laptop", "building", "house", "users", "phone", "book", "desktop", "headset", "presentation", "chart", "envelope", "printer", "calculator", "folder", "handshake", "idBadge", "videoCamera", "pen", "bank", "coins", "scales", "megaphone", "lightbulb")),
    Section("職種", listOf("storefront", "utensils", "scissors", "wrench", "truck", "teacher", "chefHat", "cookingPot", "cashRegister", "basket", "bread", "package", "warehouse", "factory", "hardHat", "hammer", "broom", "paintBrush", "tShirt", "tractor", "gasPump", "microscope", "code", "needle")),
    Section("医療・ケア", listOf("hospital", "stethoscope", "syringe", "ambulance", "siren", "shield", "handHeart", "baby", "pill", "firstAid", "heartbeat", "tooth", "eyeglasses", "bandaids", "wheelchair", "babyCarriage", "fireTruck", "policeCar", "fireExtinguisher", "shieldCheck", "bell")),
    Section("学び・趣味", listOf("graduationCap", "music", "dumbbell", "backpack", "pencil", "books", "notebook", "soccer", "basketball", "baseball", "tennis", "run", "swim", "game", "microphone", "guitar", "palette", "translate", "trophy")),
    Section("暮らし", listOf("pawPrint", "shoppingBag", "gift", "partyPopper", "calendarCheck", "cake", "wine", "beer", "shoppingCart", "calendarHeart", "washingMachine", "balloon", "cat", "dog", "rabbit", "bird", "fish")),
    Section("乗り物", listOf("car", "train", "plane", "bus", "subway", "taxi", "van", "bicycle", "motorcycle", "boat")),
  )
}
